/* Generated by Yosys 0.7+574 (git sha1 0fad1570, gcc 6.3.0-18+deb9u1 -fPIC -Os) */

(* top =  1  *)
(* src = "muxesEstructural.v:4" *)
module muxesEstructural(clk_f, clk_2f, clk_4f, reset, data0, data1, data2, data3, outEtapaL2);
  (* src = "muxesEstructural.v:20" *)
  wire [8:0] _000_;
  (* src = "muxesEstructural.v:20" *)
  wire [8:0] _001_;
  (* src = "muxesEstructural.v:20" *)
  wire [8:0] _002_;
  (* src = "muxesEstructural.v:20" *)
  wire [8:0] _003_;
  (* src = "muxesEstructural.v:38" *)
  wire [8:0] _004_;
  (* src = "muxesEstructural.v:38" *)
  wire [8:0] _005_;
  (* src = "muxesEstructural.v:52" *)
  wire [8:0] _006_;
  (* src = "muxesEstructural.v:38" *)
  wire _007_;
  (* src = "muxesEstructural.v:52" *)
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  (* src = "muxesEstructural.v:5" *)
  input clk_2f;
  (* src = "muxesEstructural.v:6" *)
  input clk_4f;
  (* src = "muxesEstructural.v:4" *)
  input clk_f;
  (* src = "muxesEstructural.v:8" *)
  input [8:0] data0;
  (* src = "muxesEstructural.v:9" *)
  input [8:0] data1;
  (* src = "muxesEstructural.v:10" *)
  input [8:0] data2;
  (* src = "muxesEstructural.v:11" *)
  input [8:0] data3;
  (* src = "muxesEstructural.v:17" *)
  wire [8:0] etapa1_preData0;
  (* src = "muxesEstructural.v:17" *)
  wire [8:0] etapa1_preData1;
  (* src = "muxesEstructural.v:17" *)
  wire [8:0] etapa1_preData2;
  (* src = "muxesEstructural.v:17" *)
  wire [8:0] etapa1_preData3;
  (* src = "muxesEstructural.v:18" *)
  wire [8:0] etapa2_preData0;
  (* src = "muxesEstructural.v:18" *)
  wire [8:0] etapa2_preData1;
  (* src = "muxesEstructural.v:12" *)
  output [8:0] outEtapaL2;
  (* src = "muxesEstructural.v:7" *)
  input reset;
  (* src = "muxesEstructural.v:16" *)
  wire selectorL1;
  (* src = "muxesEstructural.v:16" *)
  wire selectorL2;
  NOT _291_ (
    .A(data0[1]),
    .Y(_009_)
  );
  NOT _292_ (
    .A(data0[2]),
    .Y(_010_)
  );
  NOT _293_ (
    .A(data0[3]),
    .Y(_011_)
  );
  NOT _294_ (
    .A(data0[4]),
    .Y(_012_)
  );
  NOT _295_ (
    .A(data0[5]),
    .Y(_013_)
  );
  NOT _296_ (
    .A(data0[6]),
    .Y(_014_)
  );
  NOT _297_ (
    .A(data0[7]),
    .Y(_015_)
  );
  NOT _298_ (
    .A(data1[0]),
    .Y(_016_)
  );
  NOT _299_ (
    .A(data1[1]),
    .Y(_017_)
  );
  NOT _300_ (
    .A(data1[2]),
    .Y(_018_)
  );
  NOT _301_ (
    .A(data1[3]),
    .Y(_019_)
  );
  NOT _302_ (
    .A(data1[4]),
    .Y(_020_)
  );
  NOT _303_ (
    .A(data1[5]),
    .Y(_021_)
  );
  NOT _304_ (
    .A(data1[6]),
    .Y(_022_)
  );
  NOT _305_ (
    .A(data1[7]),
    .Y(_023_)
  );
  NOT _306_ (
    .A(data2[0]),
    .Y(_024_)
  );
  NOT _307_ (
    .A(data2[1]),
    .Y(_025_)
  );
  NOT _308_ (
    .A(data2[2]),
    .Y(_026_)
  );
  NOT _309_ (
    .A(data2[3]),
    .Y(_027_)
  );
  NOT _310_ (
    .A(data2[4]),
    .Y(_028_)
  );
  NOT _311_ (
    .A(data2[5]),
    .Y(_029_)
  );
  NOT _312_ (
    .A(data2[6]),
    .Y(_030_)
  );
  NOT _313_ (
    .A(data2[7]),
    .Y(_031_)
  );
  NOT _314_ (
    .A(data3[0]),
    .Y(_032_)
  );
  NOT _315_ (
    .A(data3[1]),
    .Y(_033_)
  );
  NOT _316_ (
    .A(data3[2]),
    .Y(_034_)
  );
  NOT _317_ (
    .A(data3[3]),
    .Y(_035_)
  );
  NOT _318_ (
    .A(data3[4]),
    .Y(_036_)
  );
  NOT _319_ (
    .A(data3[5]),
    .Y(_037_)
  );
  NOT _320_ (
    .A(data3[6]),
    .Y(_038_)
  );
  NOT _321_ (
    .A(data3[7]),
    .Y(_039_)
  );
  NOT _322_ (
    .A(etapa2_preData0[0]),
    .Y(_040_)
  );
  NOT _323_ (
    .A(etapa2_preData0[1]),
    .Y(_041_)
  );
  NOT _324_ (
    .A(etapa2_preData0[2]),
    .Y(_042_)
  );
  NOT _325_ (
    .A(etapa2_preData0[3]),
    .Y(_043_)
  );
  NOT _326_ (
    .A(etapa2_preData0[4]),
    .Y(_044_)
  );
  NOT _327_ (
    .A(etapa2_preData0[5]),
    .Y(_045_)
  );
  NOT _328_ (
    .A(etapa2_preData0[6]),
    .Y(_046_)
  );
  NOT _329_ (
    .A(etapa2_preData0[7]),
    .Y(_047_)
  );
  NOT _330_ (
    .A(etapa2_preData1[0]),
    .Y(_048_)
  );
  NOT _331_ (
    .A(etapa2_preData1[1]),
    .Y(_049_)
  );
  NOT _332_ (
    .A(etapa2_preData1[2]),
    .Y(_050_)
  );
  NOT _333_ (
    .A(etapa2_preData1[3]),
    .Y(_051_)
  );
  NOT _334_ (
    .A(etapa2_preData1[4]),
    .Y(_052_)
  );
  NOT _335_ (
    .A(etapa2_preData1[5]),
    .Y(_053_)
  );
  NOT _336_ (
    .A(etapa2_preData1[6]),
    .Y(_054_)
  );
  NOT _337_ (
    .A(etapa2_preData1[7]),
    .Y(_055_)
  );
  NOT _338_ (
    .A(selectorL1),
    .Y(_056_)
  );
  NOT _339_ (
    .A(reset),
    .Y(_057_)
  );
  NOT _340_ (
    .A(etapa2_preData1[8]),
    .Y(_058_)
  );
  NOT _341_ (
    .A(data0[0]),
    .Y(_059_)
  );
  NOR _342_ (
    .A(_057_),
    .B(selectorL2),
    .Y(_008_)
  );
  NOR _343_ (
    .A(etapa2_preData0[0]),
    .B(selectorL2),
    .Y(_060_)
  );
  NAND _344_ (
    .A(_048_),
    .B(selectorL2),
    .Y(_061_)
  );
  NAND _345_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NOR _346_ (
    .A(_060_),
    .B(_062_),
    .Y(_006_[0])
  );
  NOR _347_ (
    .A(etapa2_preData0[1]),
    .B(selectorL2),
    .Y(_063_)
  );
  NAND _348_ (
    .A(_049_),
    .B(selectorL2),
    .Y(_064_)
  );
  NAND _349_ (
    .A(reset),
    .B(_064_),
    .Y(_065_)
  );
  NOR _350_ (
    .A(_063_),
    .B(_065_),
    .Y(_006_[1])
  );
  NOR _351_ (
    .A(etapa2_preData0[2]),
    .B(selectorL2),
    .Y(_066_)
  );
  NAND _352_ (
    .A(_050_),
    .B(selectorL2),
    .Y(_067_)
  );
  NAND _353_ (
    .A(reset),
    .B(_067_),
    .Y(_068_)
  );
  NOR _354_ (
    .A(_066_),
    .B(_068_),
    .Y(_006_[2])
  );
  NOR _355_ (
    .A(etapa2_preData0[3]),
    .B(selectorL2),
    .Y(_069_)
  );
  NAND _356_ (
    .A(_051_),
    .B(selectorL2),
    .Y(_070_)
  );
  NAND _357_ (
    .A(reset),
    .B(_070_),
    .Y(_071_)
  );
  NOR _358_ (
    .A(_069_),
    .B(_071_),
    .Y(_006_[3])
  );
  NOR _359_ (
    .A(etapa2_preData0[4]),
    .B(selectorL2),
    .Y(_072_)
  );
  NAND _360_ (
    .A(_052_),
    .B(selectorL2),
    .Y(_073_)
  );
  NAND _361_ (
    .A(reset),
    .B(_073_),
    .Y(_074_)
  );
  NOR _362_ (
    .A(_072_),
    .B(_074_),
    .Y(_006_[4])
  );
  NOR _363_ (
    .A(etapa2_preData0[5]),
    .B(selectorL2),
    .Y(_075_)
  );
  NAND _364_ (
    .A(_053_),
    .B(selectorL2),
    .Y(_076_)
  );
  NAND _365_ (
    .A(reset),
    .B(_076_),
    .Y(_077_)
  );
  NOR _366_ (
    .A(_075_),
    .B(_077_),
    .Y(_006_[5])
  );
  NOR _367_ (
    .A(etapa2_preData0[6]),
    .B(selectorL2),
    .Y(_078_)
  );
  NAND _368_ (
    .A(_054_),
    .B(selectorL2),
    .Y(_079_)
  );
  NAND _369_ (
    .A(reset),
    .B(_079_),
    .Y(_080_)
  );
  NOR _370_ (
    .A(_078_),
    .B(_080_),
    .Y(_006_[6])
  );
  NOR _371_ (
    .A(etapa2_preData0[7]),
    .B(selectorL2),
    .Y(_081_)
  );
  NAND _372_ (
    .A(_055_),
    .B(selectorL2),
    .Y(_082_)
  );
  NAND _373_ (
    .A(reset),
    .B(_082_),
    .Y(_083_)
  );
  NOR _374_ (
    .A(_081_),
    .B(_083_),
    .Y(_006_[7])
  );
  NOR _375_ (
    .A(selectorL2),
    .B(etapa2_preData0[8]),
    .Y(_084_)
  );
  NAND _376_ (
    .A(selectorL2),
    .B(_058_),
    .Y(_085_)
  );
  NAND _377_ (
    .A(reset),
    .B(_085_),
    .Y(_086_)
  );
  NOR _378_ (
    .A(_084_),
    .B(_086_),
    .Y(_006_[8])
  );
  NAND _379_ (
    .A(selectorL1),
    .B(etapa1_preData3[8]),
    .Y(_087_)
  );
  NAND _380_ (
    .A(_056_),
    .B(etapa1_preData2[8]),
    .Y(_088_)
  );
  NAND _381_ (
    .A(_087_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _382_ (
    .A(reset),
    .B(_089_),
    .Y(_090_)
  );
  NOT _383_ (
    .A(_090_),
    .Y(_005_[8])
  );
  NAND _384_ (
    .A(etapa1_preData3[0]),
    .B(selectorL1),
    .Y(_091_)
  );
  NAND _385_ (
    .A(etapa1_preData2[0]),
    .B(_056_),
    .Y(_092_)
  );
  NAND _386_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _387_ (
    .A(_090_),
    .B(_093_),
    .Y(_094_)
  );
  NAND _388_ (
    .A(_048_),
    .B(_090_),
    .Y(_095_)
  );
  NAND _389_ (
    .A(reset),
    .B(_095_),
    .Y(_096_)
  );
  NOR _390_ (
    .A(_094_),
    .B(_096_),
    .Y(_005_[0])
  );
  NAND _391_ (
    .A(etapa1_preData3[1]),
    .B(selectorL1),
    .Y(_097_)
  );
  NAND _392_ (
    .A(etapa1_preData2[1]),
    .B(_056_),
    .Y(_098_)
  );
  NAND _393_ (
    .A(_097_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _394_ (
    .A(_090_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _395_ (
    .A(_049_),
    .B(_090_),
    .Y(_101_)
  );
  NAND _396_ (
    .A(reset),
    .B(_101_),
    .Y(_102_)
  );
  NOR _397_ (
    .A(_100_),
    .B(_102_),
    .Y(_005_[1])
  );
  NAND _398_ (
    .A(etapa1_preData3[2]),
    .B(selectorL1),
    .Y(_103_)
  );
  NAND _399_ (
    .A(etapa1_preData2[2]),
    .B(_056_),
    .Y(_104_)
  );
  NAND _400_ (
    .A(_103_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _401_ (
    .A(_090_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _402_ (
    .A(_050_),
    .B(_090_),
    .Y(_107_)
  );
  NAND _403_ (
    .A(reset),
    .B(_107_),
    .Y(_108_)
  );
  NOR _404_ (
    .A(_106_),
    .B(_108_),
    .Y(_005_[2])
  );
  NAND _405_ (
    .A(etapa1_preData3[3]),
    .B(selectorL1),
    .Y(_109_)
  );
  NAND _406_ (
    .A(etapa1_preData2[3]),
    .B(_056_),
    .Y(_110_)
  );
  NAND _407_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _408_ (
    .A(_090_),
    .B(_111_),
    .Y(_112_)
  );
  NAND _409_ (
    .A(_051_),
    .B(_090_),
    .Y(_113_)
  );
  NAND _410_ (
    .A(reset),
    .B(_113_),
    .Y(_114_)
  );
  NOR _411_ (
    .A(_112_),
    .B(_114_),
    .Y(_005_[3])
  );
  NAND _412_ (
    .A(etapa1_preData3[4]),
    .B(selectorL1),
    .Y(_115_)
  );
  NAND _413_ (
    .A(etapa1_preData2[4]),
    .B(_056_),
    .Y(_116_)
  );
  NAND _414_ (
    .A(_115_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _415_ (
    .A(_090_),
    .B(_117_),
    .Y(_118_)
  );
  NAND _416_ (
    .A(_052_),
    .B(_090_),
    .Y(_119_)
  );
  NAND _417_ (
    .A(reset),
    .B(_119_),
    .Y(_120_)
  );
  NOR _418_ (
    .A(_118_),
    .B(_120_),
    .Y(_005_[4])
  );
  NAND _419_ (
    .A(etapa1_preData3[5]),
    .B(selectorL1),
    .Y(_121_)
  );
  NAND _420_ (
    .A(etapa1_preData2[5]),
    .B(_056_),
    .Y(_122_)
  );
  NAND _421_ (
    .A(_121_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _422_ (
    .A(_090_),
    .B(_123_),
    .Y(_124_)
  );
  NAND _423_ (
    .A(_053_),
    .B(_090_),
    .Y(_125_)
  );
  NAND _424_ (
    .A(reset),
    .B(_125_),
    .Y(_126_)
  );
  NOR _425_ (
    .A(_124_),
    .B(_126_),
    .Y(_005_[5])
  );
  NAND _426_ (
    .A(etapa1_preData3[6]),
    .B(selectorL1),
    .Y(_127_)
  );
  NAND _427_ (
    .A(etapa1_preData2[6]),
    .B(_056_),
    .Y(_128_)
  );
  NAND _428_ (
    .A(_127_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _429_ (
    .A(_090_),
    .B(_129_),
    .Y(_130_)
  );
  NAND _430_ (
    .A(_054_),
    .B(_090_),
    .Y(_131_)
  );
  NAND _431_ (
    .A(reset),
    .B(_131_),
    .Y(_132_)
  );
  NOR _432_ (
    .A(_130_),
    .B(_132_),
    .Y(_005_[6])
  );
  NAND _433_ (
    .A(etapa1_preData3[7]),
    .B(selectorL1),
    .Y(_133_)
  );
  NAND _434_ (
    .A(etapa1_preData2[7]),
    .B(_056_),
    .Y(_134_)
  );
  NAND _435_ (
    .A(_133_),
    .B(_134_),
    .Y(_135_)
  );
  NOR _436_ (
    .A(_090_),
    .B(_135_),
    .Y(_136_)
  );
  NAND _437_ (
    .A(_055_),
    .B(_090_),
    .Y(_137_)
  );
  NAND _438_ (
    .A(reset),
    .B(_137_),
    .Y(_138_)
  );
  NOR _439_ (
    .A(_136_),
    .B(_138_),
    .Y(_005_[7])
  );
  NAND _440_ (
    .A(selectorL1),
    .B(etapa1_preData1[8]),
    .Y(_139_)
  );
  NAND _441_ (
    .A(_056_),
    .B(etapa1_preData0[8]),
    .Y(_140_)
  );
  NAND _442_ (
    .A(_139_),
    .B(_140_),
    .Y(_141_)
  );
  NAND _443_ (
    .A(reset),
    .B(_141_),
    .Y(_142_)
  );
  NOT _444_ (
    .A(_142_),
    .Y(_004_[8])
  );
  NAND _445_ (
    .A(etapa1_preData1[0]),
    .B(selectorL1),
    .Y(_143_)
  );
  NAND _446_ (
    .A(_056_),
    .B(etapa1_preData0[0]),
    .Y(_144_)
  );
  NAND _447_ (
    .A(_143_),
    .B(_144_),
    .Y(_145_)
  );
  NOR _448_ (
    .A(_142_),
    .B(_145_),
    .Y(_146_)
  );
  NAND _449_ (
    .A(_040_),
    .B(_142_),
    .Y(_147_)
  );
  NAND _450_ (
    .A(reset),
    .B(_147_),
    .Y(_148_)
  );
  NOR _451_ (
    .A(_146_),
    .B(_148_),
    .Y(_004_[0])
  );
  NAND _452_ (
    .A(etapa1_preData1[1]),
    .B(selectorL1),
    .Y(_149_)
  );
  NAND _453_ (
    .A(etapa1_preData0[1]),
    .B(_056_),
    .Y(_150_)
  );
  NAND _454_ (
    .A(_149_),
    .B(_150_),
    .Y(_151_)
  );
  NOR _455_ (
    .A(_142_),
    .B(_151_),
    .Y(_152_)
  );
  NAND _456_ (
    .A(_041_),
    .B(_142_),
    .Y(_153_)
  );
  NAND _457_ (
    .A(reset),
    .B(_153_),
    .Y(_154_)
  );
  NOR _458_ (
    .A(_152_),
    .B(_154_),
    .Y(_004_[1])
  );
  NAND _459_ (
    .A(etapa1_preData1[2]),
    .B(selectorL1),
    .Y(_155_)
  );
  NAND _460_ (
    .A(etapa1_preData0[2]),
    .B(_056_),
    .Y(_156_)
  );
  NAND _461_ (
    .A(_155_),
    .B(_156_),
    .Y(_157_)
  );
  NOR _462_ (
    .A(_142_),
    .B(_157_),
    .Y(_158_)
  );
  NAND _463_ (
    .A(_042_),
    .B(_142_),
    .Y(_159_)
  );
  NAND _464_ (
    .A(reset),
    .B(_159_),
    .Y(_160_)
  );
  NOR _465_ (
    .A(_158_),
    .B(_160_),
    .Y(_004_[2])
  );
  NAND _466_ (
    .A(etapa1_preData1[3]),
    .B(selectorL1),
    .Y(_161_)
  );
  NAND _467_ (
    .A(etapa1_preData0[3]),
    .B(_056_),
    .Y(_162_)
  );
  NAND _468_ (
    .A(_161_),
    .B(_162_),
    .Y(_163_)
  );
  NOR _469_ (
    .A(_142_),
    .B(_163_),
    .Y(_164_)
  );
  NAND _470_ (
    .A(_043_),
    .B(_142_),
    .Y(_165_)
  );
  NAND _471_ (
    .A(reset),
    .B(_165_),
    .Y(_166_)
  );
  NOR _472_ (
    .A(_164_),
    .B(_166_),
    .Y(_004_[3])
  );
  NAND _473_ (
    .A(etapa1_preData1[4]),
    .B(selectorL1),
    .Y(_167_)
  );
  NAND _474_ (
    .A(etapa1_preData0[4]),
    .B(_056_),
    .Y(_168_)
  );
  NAND _475_ (
    .A(_167_),
    .B(_168_),
    .Y(_169_)
  );
  NOR _476_ (
    .A(_142_),
    .B(_169_),
    .Y(_170_)
  );
  NAND _477_ (
    .A(_044_),
    .B(_142_),
    .Y(_171_)
  );
  NAND _478_ (
    .A(reset),
    .B(_171_),
    .Y(_172_)
  );
  NOR _479_ (
    .A(_170_),
    .B(_172_),
    .Y(_004_[4])
  );
  NAND _480_ (
    .A(etapa1_preData1[5]),
    .B(selectorL1),
    .Y(_173_)
  );
  NAND _481_ (
    .A(etapa1_preData0[5]),
    .B(_056_),
    .Y(_174_)
  );
  NAND _482_ (
    .A(_173_),
    .B(_174_),
    .Y(_175_)
  );
  NOR _483_ (
    .A(_142_),
    .B(_175_),
    .Y(_176_)
  );
  NAND _484_ (
    .A(_045_),
    .B(_142_),
    .Y(_177_)
  );
  NAND _485_ (
    .A(reset),
    .B(_177_),
    .Y(_178_)
  );
  NOR _486_ (
    .A(_176_),
    .B(_178_),
    .Y(_004_[5])
  );
  NAND _487_ (
    .A(etapa1_preData1[6]),
    .B(selectorL1),
    .Y(_179_)
  );
  NAND _488_ (
    .A(etapa1_preData0[6]),
    .B(_056_),
    .Y(_180_)
  );
  NAND _489_ (
    .A(_179_),
    .B(_180_),
    .Y(_181_)
  );
  NOR _490_ (
    .A(_142_),
    .B(_181_),
    .Y(_182_)
  );
  NAND _491_ (
    .A(_046_),
    .B(_142_),
    .Y(_183_)
  );
  NAND _492_ (
    .A(reset),
    .B(_183_),
    .Y(_184_)
  );
  NOR _493_ (
    .A(_182_),
    .B(_184_),
    .Y(_004_[6])
  );
  NAND _494_ (
    .A(etapa1_preData1[7]),
    .B(selectorL1),
    .Y(_185_)
  );
  NAND _495_ (
    .A(etapa1_preData0[7]),
    .B(_056_),
    .Y(_186_)
  );
  NAND _496_ (
    .A(_185_),
    .B(_186_),
    .Y(_187_)
  );
  NOR _497_ (
    .A(_142_),
    .B(_187_),
    .Y(_188_)
  );
  NAND _498_ (
    .A(_047_),
    .B(_142_),
    .Y(_189_)
  );
  NAND _499_ (
    .A(reset),
    .B(_189_),
    .Y(_190_)
  );
  NOR _500_ (
    .A(_188_),
    .B(_190_),
    .Y(_004_[7])
  );
  NOR _501_ (
    .A(selectorL1),
    .B(_057_),
    .Y(_007_)
  );
  NAND _502_ (
    .A(_032_),
    .B(data3[8]),
    .Y(_191_)
  );
  NAND _503_ (
    .A(reset),
    .B(_191_),
    .Y(_192_)
  );
  NOR _504_ (
    .A(etapa1_preData3[0]),
    .B(data3[8]),
    .Y(_193_)
  );
  NOR _505_ (
    .A(_192_),
    .B(_193_),
    .Y(_003_[0])
  );
  NAND _506_ (
    .A(data3[8]),
    .B(_033_),
    .Y(_194_)
  );
  NAND _507_ (
    .A(reset),
    .B(_194_),
    .Y(_195_)
  );
  NOR _508_ (
    .A(data3[8]),
    .B(etapa1_preData3[1]),
    .Y(_196_)
  );
  NOR _509_ (
    .A(_195_),
    .B(_196_),
    .Y(_003_[1])
  );
  NAND _510_ (
    .A(data3[8]),
    .B(_034_),
    .Y(_197_)
  );
  NAND _511_ (
    .A(reset),
    .B(_197_),
    .Y(_198_)
  );
  NOR _512_ (
    .A(data3[8]),
    .B(etapa1_preData3[2]),
    .Y(_199_)
  );
  NOR _513_ (
    .A(_198_),
    .B(_199_),
    .Y(_003_[2])
  );
  NAND _514_ (
    .A(data3[8]),
    .B(_035_),
    .Y(_200_)
  );
  NAND _515_ (
    .A(reset),
    .B(_200_),
    .Y(_201_)
  );
  NOR _516_ (
    .A(data3[8]),
    .B(etapa1_preData3[3]),
    .Y(_202_)
  );
  NOR _517_ (
    .A(_201_),
    .B(_202_),
    .Y(_003_[3])
  );
  NAND _518_ (
    .A(data3[8]),
    .B(_036_),
    .Y(_203_)
  );
  NAND _519_ (
    .A(reset),
    .B(_203_),
    .Y(_204_)
  );
  NOR _520_ (
    .A(data3[8]),
    .B(etapa1_preData3[4]),
    .Y(_205_)
  );
  NOR _521_ (
    .A(_204_),
    .B(_205_),
    .Y(_003_[4])
  );
  NAND _522_ (
    .A(data3[8]),
    .B(_037_),
    .Y(_206_)
  );
  NAND _523_ (
    .A(reset),
    .B(_206_),
    .Y(_207_)
  );
  NOR _524_ (
    .A(data3[8]),
    .B(etapa1_preData3[5]),
    .Y(_208_)
  );
  NOR _525_ (
    .A(_207_),
    .B(_208_),
    .Y(_003_[5])
  );
  NAND _526_ (
    .A(data3[8]),
    .B(_038_),
    .Y(_209_)
  );
  NAND _527_ (
    .A(reset),
    .B(_209_),
    .Y(_210_)
  );
  NOR _528_ (
    .A(data3[8]),
    .B(etapa1_preData3[6]),
    .Y(_211_)
  );
  NOR _529_ (
    .A(_210_),
    .B(_211_),
    .Y(_003_[6])
  );
  NAND _530_ (
    .A(data3[8]),
    .B(_039_),
    .Y(_212_)
  );
  NAND _531_ (
    .A(reset),
    .B(_212_),
    .Y(_213_)
  );
  NOR _532_ (
    .A(data3[8]),
    .B(etapa1_preData3[7]),
    .Y(_214_)
  );
  NOR _533_ (
    .A(_213_),
    .B(_214_),
    .Y(_003_[7])
  );
  NAND _534_ (
    .A(data3[8]),
    .B(reset),
    .Y(_215_)
  );
  NOT _535_ (
    .A(_215_),
    .Y(_003_[8])
  );
  NAND _536_ (
    .A(_024_),
    .B(data2[8]),
    .Y(_216_)
  );
  NAND _537_ (
    .A(reset),
    .B(_216_),
    .Y(_217_)
  );
  NOR _538_ (
    .A(etapa1_preData2[0]),
    .B(data2[8]),
    .Y(_218_)
  );
  NOR _539_ (
    .A(_217_),
    .B(_218_),
    .Y(_002_[0])
  );
  NAND _540_ (
    .A(data2[8]),
    .B(_025_),
    .Y(_219_)
  );
  NAND _541_ (
    .A(reset),
    .B(_219_),
    .Y(_220_)
  );
  NOR _542_ (
    .A(data2[8]),
    .B(etapa1_preData2[1]),
    .Y(_221_)
  );
  NOR _543_ (
    .A(_220_),
    .B(_221_),
    .Y(_002_[1])
  );
  NAND _544_ (
    .A(data2[8]),
    .B(_026_),
    .Y(_222_)
  );
  NAND _545_ (
    .A(reset),
    .B(_222_),
    .Y(_223_)
  );
  NOR _546_ (
    .A(data2[8]),
    .B(etapa1_preData2[2]),
    .Y(_224_)
  );
  NOR _547_ (
    .A(_223_),
    .B(_224_),
    .Y(_002_[2])
  );
  NAND _548_ (
    .A(data2[8]),
    .B(_027_),
    .Y(_225_)
  );
  NAND _549_ (
    .A(reset),
    .B(_225_),
    .Y(_226_)
  );
  NOR _550_ (
    .A(data2[8]),
    .B(etapa1_preData2[3]),
    .Y(_227_)
  );
  NOR _551_ (
    .A(_226_),
    .B(_227_),
    .Y(_002_[3])
  );
  NAND _552_ (
    .A(data2[8]),
    .B(_028_),
    .Y(_228_)
  );
  NAND _553_ (
    .A(reset),
    .B(_228_),
    .Y(_229_)
  );
  NOR _554_ (
    .A(data2[8]),
    .B(etapa1_preData2[4]),
    .Y(_230_)
  );
  NOR _555_ (
    .A(_229_),
    .B(_230_),
    .Y(_002_[4])
  );
  NAND _556_ (
    .A(data2[8]),
    .B(_029_),
    .Y(_231_)
  );
  NAND _557_ (
    .A(reset),
    .B(_231_),
    .Y(_232_)
  );
  NOR _558_ (
    .A(data2[8]),
    .B(etapa1_preData2[5]),
    .Y(_233_)
  );
  NOR _559_ (
    .A(_232_),
    .B(_233_),
    .Y(_002_[5])
  );
  NAND _560_ (
    .A(data2[8]),
    .B(_030_),
    .Y(_234_)
  );
  NAND _561_ (
    .A(reset),
    .B(_234_),
    .Y(_235_)
  );
  NOR _562_ (
    .A(data2[8]),
    .B(etapa1_preData2[6]),
    .Y(_236_)
  );
  NOR _563_ (
    .A(_235_),
    .B(_236_),
    .Y(_002_[6])
  );
  NAND _564_ (
    .A(data2[8]),
    .B(_031_),
    .Y(_237_)
  );
  NAND _565_ (
    .A(reset),
    .B(_237_),
    .Y(_238_)
  );
  NOR _566_ (
    .A(data2[8]),
    .B(etapa1_preData2[7]),
    .Y(_239_)
  );
  NOR _567_ (
    .A(_238_),
    .B(_239_),
    .Y(_002_[7])
  );
  NAND _568_ (
    .A(data2[8]),
    .B(reset),
    .Y(_240_)
  );
  NOT _569_ (
    .A(_240_),
    .Y(_002_[8])
  );
  NAND _570_ (
    .A(_016_),
    .B(data1[8]),
    .Y(_241_)
  );
  NAND _571_ (
    .A(reset),
    .B(_241_),
    .Y(_242_)
  );
  NOR _572_ (
    .A(etapa1_preData1[0]),
    .B(data1[8]),
    .Y(_243_)
  );
  NOR _573_ (
    .A(_242_),
    .B(_243_),
    .Y(_001_[0])
  );
  NAND _574_ (
    .A(data1[8]),
    .B(_017_),
    .Y(_244_)
  );
  NAND _575_ (
    .A(reset),
    .B(_244_),
    .Y(_245_)
  );
  NOR _576_ (
    .A(data1[8]),
    .B(etapa1_preData1[1]),
    .Y(_246_)
  );
  NOR _577_ (
    .A(_245_),
    .B(_246_),
    .Y(_001_[1])
  );
  NAND _578_ (
    .A(data1[8]),
    .B(_018_),
    .Y(_247_)
  );
  NAND _579_ (
    .A(reset),
    .B(_247_),
    .Y(_248_)
  );
  NOR _580_ (
    .A(data1[8]),
    .B(etapa1_preData1[2]),
    .Y(_249_)
  );
  NOR _581_ (
    .A(_248_),
    .B(_249_),
    .Y(_001_[2])
  );
  NAND _582_ (
    .A(data1[8]),
    .B(_019_),
    .Y(_250_)
  );
  NAND _583_ (
    .A(reset),
    .B(_250_),
    .Y(_251_)
  );
  NOR _584_ (
    .A(data1[8]),
    .B(etapa1_preData1[3]),
    .Y(_252_)
  );
  NOR _585_ (
    .A(_251_),
    .B(_252_),
    .Y(_001_[3])
  );
  NAND _586_ (
    .A(data1[8]),
    .B(_020_),
    .Y(_253_)
  );
  NAND _587_ (
    .A(reset),
    .B(_253_),
    .Y(_254_)
  );
  NOR _588_ (
    .A(data1[8]),
    .B(etapa1_preData1[4]),
    .Y(_255_)
  );
  NOR _589_ (
    .A(_254_),
    .B(_255_),
    .Y(_001_[4])
  );
  NAND _590_ (
    .A(data1[8]),
    .B(_021_),
    .Y(_256_)
  );
  NAND _591_ (
    .A(reset),
    .B(_256_),
    .Y(_257_)
  );
  NOR _592_ (
    .A(data1[8]),
    .B(etapa1_preData1[5]),
    .Y(_258_)
  );
  NOR _593_ (
    .A(_257_),
    .B(_258_),
    .Y(_001_[5])
  );
  NAND _594_ (
    .A(data1[8]),
    .B(_022_),
    .Y(_259_)
  );
  NAND _595_ (
    .A(reset),
    .B(_259_),
    .Y(_260_)
  );
  NOR _596_ (
    .A(data1[8]),
    .B(etapa1_preData1[6]),
    .Y(_261_)
  );
  NOR _597_ (
    .A(_260_),
    .B(_261_),
    .Y(_001_[6])
  );
  NAND _598_ (
    .A(data1[8]),
    .B(_023_),
    .Y(_262_)
  );
  NAND _599_ (
    .A(reset),
    .B(_262_),
    .Y(_263_)
  );
  NOR _600_ (
    .A(data1[8]),
    .B(etapa1_preData1[7]),
    .Y(_264_)
  );
  NOR _601_ (
    .A(_263_),
    .B(_264_),
    .Y(_001_[7])
  );
  NAND _602_ (
    .A(data1[8]),
    .B(reset),
    .Y(_265_)
  );
  NOT _603_ (
    .A(_265_),
    .Y(_001_[8])
  );
  NAND _604_ (
    .A(data0[8]),
    .B(_059_),
    .Y(_266_)
  );
  NAND _605_ (
    .A(reset),
    .B(_266_),
    .Y(_267_)
  );
  NOR _606_ (
    .A(data0[8]),
    .B(etapa1_preData0[0]),
    .Y(_268_)
  );
  NOR _607_ (
    .A(_267_),
    .B(_268_),
    .Y(_000_[0])
  );
  NAND _608_ (
    .A(_009_),
    .B(data0[8]),
    .Y(_269_)
  );
  NAND _609_ (
    .A(reset),
    .B(_269_),
    .Y(_270_)
  );
  NOR _610_ (
    .A(etapa1_preData0[1]),
    .B(data0[8]),
    .Y(_271_)
  );
  NOR _611_ (
    .A(_270_),
    .B(_271_),
    .Y(_000_[1])
  );
  NAND _612_ (
    .A(data0[8]),
    .B(_010_),
    .Y(_272_)
  );
  NAND _613_ (
    .A(reset),
    .B(_272_),
    .Y(_273_)
  );
  NOR _614_ (
    .A(data0[8]),
    .B(etapa1_preData0[2]),
    .Y(_274_)
  );
  NOR _615_ (
    .A(_273_),
    .B(_274_),
    .Y(_000_[2])
  );
  NAND _616_ (
    .A(data0[8]),
    .B(_011_),
    .Y(_275_)
  );
  NAND _617_ (
    .A(reset),
    .B(_275_),
    .Y(_276_)
  );
  NOR _618_ (
    .A(data0[8]),
    .B(etapa1_preData0[3]),
    .Y(_277_)
  );
  NOR _619_ (
    .A(_276_),
    .B(_277_),
    .Y(_000_[3])
  );
  NAND _620_ (
    .A(data0[8]),
    .B(_012_),
    .Y(_278_)
  );
  NAND _621_ (
    .A(reset),
    .B(_278_),
    .Y(_279_)
  );
  NOR _622_ (
    .A(data0[8]),
    .B(etapa1_preData0[4]),
    .Y(_280_)
  );
  NOR _623_ (
    .A(_279_),
    .B(_280_),
    .Y(_000_[4])
  );
  NAND _624_ (
    .A(data0[8]),
    .B(_013_),
    .Y(_281_)
  );
  NAND _625_ (
    .A(reset),
    .B(_281_),
    .Y(_282_)
  );
  NOR _626_ (
    .A(data0[8]),
    .B(etapa1_preData0[5]),
    .Y(_283_)
  );
  NOR _627_ (
    .A(_282_),
    .B(_283_),
    .Y(_000_[5])
  );
  NAND _628_ (
    .A(data0[8]),
    .B(_014_),
    .Y(_284_)
  );
  NAND _629_ (
    .A(reset),
    .B(_284_),
    .Y(_285_)
  );
  NOR _630_ (
    .A(data0[8]),
    .B(etapa1_preData0[6]),
    .Y(_286_)
  );
  NOR _631_ (
    .A(_285_),
    .B(_286_),
    .Y(_000_[6])
  );
  NAND _632_ (
    .A(data0[8]),
    .B(_015_),
    .Y(_287_)
  );
  NAND _633_ (
    .A(reset),
    .B(_287_),
    .Y(_288_)
  );
  NOR _634_ (
    .A(data0[8]),
    .B(etapa1_preData0[7]),
    .Y(_289_)
  );
  NOR _635_ (
    .A(_288_),
    .B(_289_),
    .Y(_000_[7])
  );
  NAND _636_ (
    .A(data0[8]),
    .B(reset),
    .Y(_290_)
  );
  NOT _637_ (
    .A(_290_),
    .Y(_000_[8])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _638_ (
    .C(clk_4f),
    .D(_006_[0]),
    .Q(outEtapaL2[0])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _639_ (
    .C(clk_4f),
    .D(_006_[1]),
    .Q(outEtapaL2[1])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _640_ (
    .C(clk_4f),
    .D(_006_[2]),
    .Q(outEtapaL2[2])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _641_ (
    .C(clk_4f),
    .D(_006_[3]),
    .Q(outEtapaL2[3])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _642_ (
    .C(clk_4f),
    .D(_006_[4]),
    .Q(outEtapaL2[4])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _643_ (
    .C(clk_4f),
    .D(_006_[5]),
    .Q(outEtapaL2[5])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _644_ (
    .C(clk_4f),
    .D(_006_[6]),
    .Q(outEtapaL2[6])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _645_ (
    .C(clk_4f),
    .D(_006_[7]),
    .Q(outEtapaL2[7])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _646_ (
    .C(clk_4f),
    .D(_006_[8]),
    .Q(outEtapaL2[8])
  );
  (* src = "muxesEstructural.v:52" *)
  DFF _647_ (
    .C(clk_4f),
    .D(_008_),
    .Q(selectorL2)
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _648_ (
    .C(clk_2f),
    .D(_007_),
    .Q(selectorL1)
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _649_ (
    .C(clk_2f),
    .D(_004_[0]),
    .Q(etapa2_preData0[0])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _650_ (
    .C(clk_2f),
    .D(_004_[1]),
    .Q(etapa2_preData0[1])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _651_ (
    .C(clk_2f),
    .D(_004_[2]),
    .Q(etapa2_preData0[2])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _652_ (
    .C(clk_2f),
    .D(_004_[3]),
    .Q(etapa2_preData0[3])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _653_ (
    .C(clk_2f),
    .D(_004_[4]),
    .Q(etapa2_preData0[4])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _654_ (
    .C(clk_2f),
    .D(_004_[5]),
    .Q(etapa2_preData0[5])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _655_ (
    .C(clk_2f),
    .D(_004_[6]),
    .Q(etapa2_preData0[6])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _656_ (
    .C(clk_2f),
    .D(_004_[7]),
    .Q(etapa2_preData0[7])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _657_ (
    .C(clk_2f),
    .D(_004_[8]),
    .Q(etapa2_preData0[8])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _658_ (
    .C(clk_2f),
    .D(_005_[0]),
    .Q(etapa2_preData1[0])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _659_ (
    .C(clk_2f),
    .D(_005_[1]),
    .Q(etapa2_preData1[1])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _660_ (
    .C(clk_2f),
    .D(_005_[2]),
    .Q(etapa2_preData1[2])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _661_ (
    .C(clk_2f),
    .D(_005_[3]),
    .Q(etapa2_preData1[3])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _662_ (
    .C(clk_2f),
    .D(_005_[4]),
    .Q(etapa2_preData1[4])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _663_ (
    .C(clk_2f),
    .D(_005_[5]),
    .Q(etapa2_preData1[5])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _664_ (
    .C(clk_2f),
    .D(_005_[6]),
    .Q(etapa2_preData1[6])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _665_ (
    .C(clk_2f),
    .D(_005_[7]),
    .Q(etapa2_preData1[7])
  );
  (* src = "muxesEstructural.v:38" *)
  DFF _666_ (
    .C(clk_2f),
    .D(_005_[8]),
    .Q(etapa2_preData1[8])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _667_ (
    .C(clk_f),
    .D(_000_[0]),
    .Q(etapa1_preData0[0])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _668_ (
    .C(clk_f),
    .D(_000_[1]),
    .Q(etapa1_preData0[1])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _669_ (
    .C(clk_f),
    .D(_000_[2]),
    .Q(etapa1_preData0[2])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _670_ (
    .C(clk_f),
    .D(_000_[3]),
    .Q(etapa1_preData0[3])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _671_ (
    .C(clk_f),
    .D(_000_[4]),
    .Q(etapa1_preData0[4])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _672_ (
    .C(clk_f),
    .D(_000_[5]),
    .Q(etapa1_preData0[5])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _673_ (
    .C(clk_f),
    .D(_000_[6]),
    .Q(etapa1_preData0[6])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _674_ (
    .C(clk_f),
    .D(_000_[7]),
    .Q(etapa1_preData0[7])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _675_ (
    .C(clk_f),
    .D(_000_[8]),
    .Q(etapa1_preData0[8])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _676_ (
    .C(clk_f),
    .D(_001_[0]),
    .Q(etapa1_preData1[0])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _677_ (
    .C(clk_f),
    .D(_001_[1]),
    .Q(etapa1_preData1[1])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _678_ (
    .C(clk_f),
    .D(_001_[2]),
    .Q(etapa1_preData1[2])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _679_ (
    .C(clk_f),
    .D(_001_[3]),
    .Q(etapa1_preData1[3])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _680_ (
    .C(clk_f),
    .D(_001_[4]),
    .Q(etapa1_preData1[4])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _681_ (
    .C(clk_f),
    .D(_001_[5]),
    .Q(etapa1_preData1[5])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _682_ (
    .C(clk_f),
    .D(_001_[6]),
    .Q(etapa1_preData1[6])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _683_ (
    .C(clk_f),
    .D(_001_[7]),
    .Q(etapa1_preData1[7])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _684_ (
    .C(clk_f),
    .D(_001_[8]),
    .Q(etapa1_preData1[8])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _685_ (
    .C(clk_f),
    .D(_002_[0]),
    .Q(etapa1_preData2[0])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _686_ (
    .C(clk_f),
    .D(_002_[1]),
    .Q(etapa1_preData2[1])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _687_ (
    .C(clk_f),
    .D(_002_[2]),
    .Q(etapa1_preData2[2])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _688_ (
    .C(clk_f),
    .D(_002_[3]),
    .Q(etapa1_preData2[3])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _689_ (
    .C(clk_f),
    .D(_002_[4]),
    .Q(etapa1_preData2[4])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _690_ (
    .C(clk_f),
    .D(_002_[5]),
    .Q(etapa1_preData2[5])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _691_ (
    .C(clk_f),
    .D(_002_[6]),
    .Q(etapa1_preData2[6])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _692_ (
    .C(clk_f),
    .D(_002_[7]),
    .Q(etapa1_preData2[7])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _693_ (
    .C(clk_f),
    .D(_002_[8]),
    .Q(etapa1_preData2[8])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _694_ (
    .C(clk_f),
    .D(_003_[0]),
    .Q(etapa1_preData3[0])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _695_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(etapa1_preData3[1])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _696_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(etapa1_preData3[2])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _697_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(etapa1_preData3[3])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _698_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(etapa1_preData3[4])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _699_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(etapa1_preData3[5])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _700_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(etapa1_preData3[6])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _701_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(etapa1_preData3[7])
  );
  (* src = "muxesEstructural.v:20" *)
  DFF _702_ (
    .C(clk_f),
    .D(_003_[8]),
    .Q(etapa1_preData3[8])
  );
endmodule
