/* Generated by Yosys 0.7+574 (git sha1 0fad1570, gcc 6.3.0-18+deb9u1 -fPIC -Os) */

(* top =  1  *)
(* src = "phy_tx.v:4" *)
module phy_tx(clk_f, clk_2f, clk_4f, reset, data0, data1, data2, data3, outEtapaL2);
  (* src = "phy_tx.v:20" *)
  wire [8:0] _000_;
  (* src = "phy_tx.v:20" *)
  wire [8:0] _001_;
  (* src = "phy_tx.v:20" *)
  wire [8:0] _002_;
  (* src = "phy_tx.v:20" *)
  wire [8:0] _003_;
  (* src = "phy_tx.v:41" *)
  wire [8:0] _004_;
  (* src = "phy_tx.v:41" *)
  wire [8:0] _005_;
  (* src = "phy_tx.v:20" *)
  wire _006_;
  (* src = "phy_tx.v:41" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  (* src = "phy_tx.v:5" *)
  input clk_2f;
  (* src = "phy_tx.v:6" *)
  input clk_4f;
  (* src = "phy_tx.v:4" *)
  input clk_f;
  (* src = "phy_tx.v:8" *)
  input [8:0] data0;
  (* src = "phy_tx.v:9" *)
  input [8:0] data1;
  (* src = "phy_tx.v:10" *)
  input [8:0] data2;
  (* src = "phy_tx.v:11" *)
  input [8:0] data3;
  (* src = "phy_tx.v:17" *)
  wire [8:0] etapa1_preData0;
  (* src = "phy_tx.v:17" *)
  wire [8:0] etapa1_preData1;
  (* src = "phy_tx.v:17" *)
  wire [8:0] etapa1_preData2;
  (* src = "phy_tx.v:17" *)
  wire [8:0] etapa1_preData3;
  (* src = "phy_tx.v:18" *)
  wire [8:0] etapa2_preData0;
  (* src = "phy_tx.v:18" *)
  wire [8:0] etapa2_preData1;
  (* src = "phy_tx.v:12" *)
  output [8:0] outEtapaL2;
  (* src = "phy_tx.v:7" *)
  input reset;
  (* src = "phy_tx.v:16" *)
  wire selectorL1;
  (* src = "phy_tx.v:16" *)
  wire selectorL2;
  NOT _403_ (
    .A(data0[1]),
    .Y(_008_)
  );
  NOT _404_ (
    .A(data0[8]),
    .Y(_009_)
  );
  NOT _405_ (
    .A(data0[2]),
    .Y(_010_)
  );
  NOT _406_ (
    .A(data0[3]),
    .Y(_011_)
  );
  NOT _407_ (
    .A(data0[4]),
    .Y(_012_)
  );
  NOT _408_ (
    .A(data0[5]),
    .Y(_013_)
  );
  NOT _409_ (
    .A(data0[6]),
    .Y(_014_)
  );
  NOT _410_ (
    .A(data0[7]),
    .Y(_015_)
  );
  NOT _411_ (
    .A(data1[0]),
    .Y(_016_)
  );
  NOT _412_ (
    .A(data1[8]),
    .Y(_017_)
  );
  NOT _413_ (
    .A(data1[1]),
    .Y(_018_)
  );
  NOT _414_ (
    .A(data1[2]),
    .Y(_019_)
  );
  NOT _415_ (
    .A(data1[3]),
    .Y(_020_)
  );
  NOT _416_ (
    .A(data1[4]),
    .Y(_021_)
  );
  NOT _417_ (
    .A(data1[5]),
    .Y(_022_)
  );
  NOT _418_ (
    .A(data1[6]),
    .Y(_023_)
  );
  NOT _419_ (
    .A(data1[7]),
    .Y(_024_)
  );
  NOT _420_ (
    .A(data2[0]),
    .Y(_025_)
  );
  NOT _421_ (
    .A(data2[8]),
    .Y(_026_)
  );
  NOT _422_ (
    .A(data2[1]),
    .Y(_027_)
  );
  NOT _423_ (
    .A(data2[2]),
    .Y(_028_)
  );
  NOT _424_ (
    .A(data2[3]),
    .Y(_029_)
  );
  NOT _425_ (
    .A(data2[4]),
    .Y(_030_)
  );
  NOT _426_ (
    .A(data2[5]),
    .Y(_031_)
  );
  NOT _427_ (
    .A(data2[6]),
    .Y(_032_)
  );
  NOT _428_ (
    .A(data2[7]),
    .Y(_033_)
  );
  NOT _429_ (
    .A(data3[0]),
    .Y(_034_)
  );
  NOT _430_ (
    .A(data3[8]),
    .Y(_035_)
  );
  NOT _431_ (
    .A(data3[1]),
    .Y(_036_)
  );
  NOT _432_ (
    .A(data3[2]),
    .Y(_037_)
  );
  NOT _433_ (
    .A(data3[3]),
    .Y(_038_)
  );
  NOT _434_ (
    .A(data3[4]),
    .Y(_039_)
  );
  NOT _435_ (
    .A(data3[5]),
    .Y(_040_)
  );
  NOT _436_ (
    .A(data3[6]),
    .Y(_041_)
  );
  NOT _437_ (
    .A(data3[7]),
    .Y(_042_)
  );
  NOT _438_ (
    .A(etapa1_preData1[8]),
    .Y(_043_)
  );
  NOT _439_ (
    .A(etapa1_preData3[8]),
    .Y(_044_)
  );
  NOT _440_ (
    .A(data0[0]),
    .Y(_045_)
  );
  NOT _441_ (
    .A(etapa1_preData0[8]),
    .Y(_046_)
  );
  NOT _442_ (
    .A(etapa1_preData2[8]),
    .Y(_047_)
  );
  NOT _443_ (
    .A(selectorL2),
    .Y(_048_)
  );
  NOT _444_ (
    .A(selectorL1),
    .Y(_049_)
  );
  NOT _445_ (
    .A(reset),
    .Y(_050_)
  );
  NOR _446_ (
    .A(selectorL2),
    .B(_050_),
    .Y(_007_)
  );
  NOT _447_ (
    .A(_007_),
    .Y(_051_)
  );
  NOR _448_ (
    .A(data0[1]),
    .B(_046_),
    .Y(_052_)
  );
  NAND _449_ (
    .A(data0[1]),
    .B(data0[8]),
    .Y(_053_)
  );
  NOT _450_ (
    .A(_053_),
    .Y(_054_)
  );
  NOR _451_ (
    .A(_052_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _452_ (
    .A(_049_),
    .B(reset),
    .Y(_056_)
  );
  NOT _453_ (
    .A(_056_),
    .Y(_006_)
  );
  NOR _454_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _455_ (
    .A(data1[1]),
    .B(_043_),
    .Y(_058_)
  );
  NAND _456_ (
    .A(data1[8]),
    .B(data1[1]),
    .Y(_059_)
  );
  NOT _457_ (
    .A(_059_),
    .Y(_060_)
  );
  NOR _458_ (
    .A(_058_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _459_ (
    .A(selectorL1),
    .B(reset),
    .Y(_062_)
  );
  NOR _460_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _461_ (
    .A(_057_),
    .B(_063_),
    .Y(_064_)
  );
  NOT _462_ (
    .A(_064_),
    .Y(_004_[8])
  );
  NAND _463_ (
    .A(data1[0]),
    .B(data1[1]),
    .Y(_065_)
  );
  NAND _464_ (
    .A(etapa1_preData1[0]),
    .B(_018_),
    .Y(_066_)
  );
  NAND _465_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _466_ (
    .A(selectorL1),
    .B(_067_),
    .Y(_068_)
  );
  NAND _467_ (
    .A(data0[1]),
    .B(data0[0]),
    .Y(_069_)
  );
  NAND _468_ (
    .A(_008_),
    .B(etapa1_preData0[0]),
    .Y(_070_)
  );
  NAND _469_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _470_ (
    .A(_049_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _471_ (
    .A(_068_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _472_ (
    .A(_004_[8]),
    .B(_073_),
    .Y(_074_)
  );
  NAND _473_ (
    .A(etapa2_preData0[0]),
    .B(_064_),
    .Y(_075_)
  );
  NAND _474_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  NAND _475_ (
    .A(_007_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _476_ (
    .A(_048_),
    .B(_050_),
    .Y(_078_)
  );
  NAND _477_ (
    .A(selectorL2),
    .B(reset),
    .Y(_079_)
  );
  NOR _478_ (
    .A(data2[1]),
    .B(_047_),
    .Y(_080_)
  );
  NAND _479_ (
    .A(data2[8]),
    .B(data2[1]),
    .Y(_081_)
  );
  NOT _480_ (
    .A(_081_),
    .Y(_082_)
  );
  NOR _481_ (
    .A(_080_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _482_ (
    .A(_056_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _483_ (
    .A(data3[1]),
    .B(_044_),
    .Y(_085_)
  );
  NAND _484_ (
    .A(data3[8]),
    .B(data3[1]),
    .Y(_086_)
  );
  NOT _485_ (
    .A(_086_),
    .Y(_087_)
  );
  NOR _486_ (
    .A(_085_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _487_ (
    .A(_062_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _488_ (
    .A(_084_),
    .B(_089_),
    .Y(_090_)
  );
  NOT _489_ (
    .A(_090_),
    .Y(_005_[8])
  );
  NAND _490_ (
    .A(data3[0]),
    .B(data3[1]),
    .Y(_091_)
  );
  NAND _491_ (
    .A(etapa1_preData3[0]),
    .B(_036_),
    .Y(_092_)
  );
  NAND _492_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _493_ (
    .A(selectorL1),
    .B(_093_),
    .Y(_094_)
  );
  NAND _494_ (
    .A(data2[0]),
    .B(data2[1]),
    .Y(_095_)
  );
  NAND _495_ (
    .A(etapa1_preData2[0]),
    .B(_027_),
    .Y(_096_)
  );
  NAND _496_ (
    .A(_095_),
    .B(_096_),
    .Y(_097_)
  );
  NAND _497_ (
    .A(_049_),
    .B(_097_),
    .Y(_098_)
  );
  NAND _498_ (
    .A(_094_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _499_ (
    .A(_005_[8]),
    .B(_099_),
    .Y(_100_)
  );
  NAND _500_ (
    .A(etapa2_preData1[0]),
    .B(_090_),
    .Y(_101_)
  );
  NAND _501_ (
    .A(_100_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _502_ (
    .A(_078_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _503_ (
    .A(_077_),
    .B(_103_),
    .Y(outEtapaL2[0])
  );
  NOR _504_ (
    .A(etapa1_preData1[1]),
    .B(data1[1]),
    .Y(_104_)
  );
  NOT _505_ (
    .A(_104_),
    .Y(_105_)
  );
  NAND _506_ (
    .A(selectorL1),
    .B(_105_),
    .Y(_106_)
  );
  NOR _507_ (
    .A(etapa1_preData0[1]),
    .B(data0[1]),
    .Y(_107_)
  );
  NOR _508_ (
    .A(selectorL1),
    .B(_107_),
    .Y(_108_)
  );
  NOT _509_ (
    .A(_108_),
    .Y(_109_)
  );
  NAND _510_ (
    .A(_106_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _511_ (
    .A(_004_[8]),
    .B(_110_),
    .Y(_111_)
  );
  NAND _512_ (
    .A(etapa2_preData0[1]),
    .B(_064_),
    .Y(_112_)
  );
  NAND _513_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _514_ (
    .A(_007_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _515_ (
    .A(etapa1_preData3[1]),
    .B(data3[1]),
    .Y(_115_)
  );
  NOT _516_ (
    .A(_115_),
    .Y(_116_)
  );
  NAND _517_ (
    .A(selectorL1),
    .B(_116_),
    .Y(_117_)
  );
  NOR _518_ (
    .A(etapa1_preData2[1]),
    .B(data2[1]),
    .Y(_118_)
  );
  NOR _519_ (
    .A(selectorL1),
    .B(_118_),
    .Y(_119_)
  );
  NOT _520_ (
    .A(_119_),
    .Y(_120_)
  );
  NAND _521_ (
    .A(_117_),
    .B(_120_),
    .Y(_121_)
  );
  NAND _522_ (
    .A(_005_[8]),
    .B(_121_),
    .Y(_122_)
  );
  NAND _523_ (
    .A(etapa2_preData1[1]),
    .B(_090_),
    .Y(_123_)
  );
  NAND _524_ (
    .A(_122_),
    .B(_123_),
    .Y(_124_)
  );
  NAND _525_ (
    .A(_078_),
    .B(_124_),
    .Y(_125_)
  );
  NAND _526_ (
    .A(_114_),
    .B(_125_),
    .Y(outEtapaL2[1])
  );
  NAND _527_ (
    .A(data1[1]),
    .B(data1[2]),
    .Y(_126_)
  );
  NAND _528_ (
    .A(_018_),
    .B(etapa1_preData1[2]),
    .Y(_127_)
  );
  NAND _529_ (
    .A(_126_),
    .B(_127_),
    .Y(_128_)
  );
  NAND _530_ (
    .A(selectorL1),
    .B(_128_),
    .Y(_129_)
  );
  NAND _531_ (
    .A(data0[1]),
    .B(data0[2]),
    .Y(_130_)
  );
  NAND _532_ (
    .A(_008_),
    .B(etapa1_preData0[2]),
    .Y(_131_)
  );
  NAND _533_ (
    .A(_130_),
    .B(_131_),
    .Y(_132_)
  );
  NAND _534_ (
    .A(_049_),
    .B(_132_),
    .Y(_133_)
  );
  NAND _535_ (
    .A(_129_),
    .B(_133_),
    .Y(_134_)
  );
  NAND _536_ (
    .A(_004_[8]),
    .B(_134_),
    .Y(_135_)
  );
  NAND _537_ (
    .A(etapa2_preData0[2]),
    .B(_064_),
    .Y(_136_)
  );
  NAND _538_ (
    .A(_135_),
    .B(_136_),
    .Y(_137_)
  );
  NAND _539_ (
    .A(_007_),
    .B(_137_),
    .Y(_138_)
  );
  NAND _540_ (
    .A(data3[1]),
    .B(data3[2]),
    .Y(_139_)
  );
  NAND _541_ (
    .A(_036_),
    .B(etapa1_preData3[2]),
    .Y(_140_)
  );
  NAND _542_ (
    .A(_139_),
    .B(_140_),
    .Y(_141_)
  );
  NAND _543_ (
    .A(selectorL1),
    .B(_141_),
    .Y(_142_)
  );
  NAND _544_ (
    .A(data2[1]),
    .B(data2[2]),
    .Y(_143_)
  );
  NAND _545_ (
    .A(_027_),
    .B(etapa1_preData2[2]),
    .Y(_144_)
  );
  NAND _546_ (
    .A(_143_),
    .B(_144_),
    .Y(_145_)
  );
  NAND _547_ (
    .A(_049_),
    .B(_145_),
    .Y(_146_)
  );
  NAND _548_ (
    .A(_142_),
    .B(_146_),
    .Y(_147_)
  );
  NAND _549_ (
    .A(_005_[8]),
    .B(_147_),
    .Y(_148_)
  );
  NAND _550_ (
    .A(etapa2_preData1[2]),
    .B(_090_),
    .Y(_149_)
  );
  NAND _551_ (
    .A(_148_),
    .B(_149_),
    .Y(_150_)
  );
  NAND _552_ (
    .A(_078_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _553_ (
    .A(_138_),
    .B(_151_),
    .Y(outEtapaL2[2])
  );
  NAND _554_ (
    .A(data1[1]),
    .B(data1[3]),
    .Y(_152_)
  );
  NAND _555_ (
    .A(_018_),
    .B(etapa1_preData1[3]),
    .Y(_153_)
  );
  NAND _556_ (
    .A(_152_),
    .B(_153_),
    .Y(_154_)
  );
  NAND _557_ (
    .A(selectorL1),
    .B(_154_),
    .Y(_155_)
  );
  NAND _558_ (
    .A(data0[1]),
    .B(data0[3]),
    .Y(_156_)
  );
  NAND _559_ (
    .A(_008_),
    .B(etapa1_preData0[3]),
    .Y(_157_)
  );
  NAND _560_ (
    .A(_156_),
    .B(_157_),
    .Y(_158_)
  );
  NAND _561_ (
    .A(_049_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _562_ (
    .A(_155_),
    .B(_159_),
    .Y(_160_)
  );
  NAND _563_ (
    .A(_004_[8]),
    .B(_160_),
    .Y(_161_)
  );
  NAND _564_ (
    .A(etapa2_preData0[3]),
    .B(_064_),
    .Y(_162_)
  );
  NAND _565_ (
    .A(_161_),
    .B(_162_),
    .Y(_163_)
  );
  NAND _566_ (
    .A(_007_),
    .B(_163_),
    .Y(_164_)
  );
  NAND _567_ (
    .A(data3[1]),
    .B(data3[3]),
    .Y(_165_)
  );
  NAND _568_ (
    .A(_036_),
    .B(etapa1_preData3[3]),
    .Y(_166_)
  );
  NAND _569_ (
    .A(_165_),
    .B(_166_),
    .Y(_167_)
  );
  NAND _570_ (
    .A(selectorL1),
    .B(_167_),
    .Y(_168_)
  );
  NAND _571_ (
    .A(data2[1]),
    .B(data2[3]),
    .Y(_169_)
  );
  NAND _572_ (
    .A(_027_),
    .B(etapa1_preData2[3]),
    .Y(_170_)
  );
  NAND _573_ (
    .A(_169_),
    .B(_170_),
    .Y(_171_)
  );
  NAND _574_ (
    .A(_049_),
    .B(_171_),
    .Y(_172_)
  );
  NAND _575_ (
    .A(_168_),
    .B(_172_),
    .Y(_173_)
  );
  NAND _576_ (
    .A(_005_[8]),
    .B(_173_),
    .Y(_174_)
  );
  NAND _577_ (
    .A(etapa2_preData1[3]),
    .B(_090_),
    .Y(_175_)
  );
  NAND _578_ (
    .A(_174_),
    .B(_175_),
    .Y(_176_)
  );
  NAND _579_ (
    .A(_078_),
    .B(_176_),
    .Y(_177_)
  );
  NAND _580_ (
    .A(_164_),
    .B(_177_),
    .Y(outEtapaL2[3])
  );
  NAND _581_ (
    .A(data1[1]),
    .B(data1[4]),
    .Y(_178_)
  );
  NAND _582_ (
    .A(_018_),
    .B(etapa1_preData1[4]),
    .Y(_179_)
  );
  NAND _583_ (
    .A(_178_),
    .B(_179_),
    .Y(_180_)
  );
  NAND _584_ (
    .A(selectorL1),
    .B(_180_),
    .Y(_181_)
  );
  NAND _585_ (
    .A(data0[1]),
    .B(data0[4]),
    .Y(_182_)
  );
  NAND _586_ (
    .A(_008_),
    .B(etapa1_preData0[4]),
    .Y(_183_)
  );
  NAND _587_ (
    .A(_182_),
    .B(_183_),
    .Y(_184_)
  );
  NAND _588_ (
    .A(_049_),
    .B(_184_),
    .Y(_185_)
  );
  NAND _589_ (
    .A(_181_),
    .B(_185_),
    .Y(_186_)
  );
  NAND _590_ (
    .A(_004_[8]),
    .B(_186_),
    .Y(_187_)
  );
  NAND _591_ (
    .A(etapa2_preData0[4]),
    .B(_064_),
    .Y(_188_)
  );
  NAND _592_ (
    .A(_187_),
    .B(_188_),
    .Y(_189_)
  );
  NAND _593_ (
    .A(_007_),
    .B(_189_),
    .Y(_190_)
  );
  NAND _594_ (
    .A(data3[1]),
    .B(data3[4]),
    .Y(_191_)
  );
  NAND _595_ (
    .A(_036_),
    .B(etapa1_preData3[4]),
    .Y(_192_)
  );
  NAND _596_ (
    .A(_191_),
    .B(_192_),
    .Y(_193_)
  );
  NAND _597_ (
    .A(selectorL1),
    .B(_193_),
    .Y(_194_)
  );
  NAND _598_ (
    .A(data2[1]),
    .B(data2[4]),
    .Y(_195_)
  );
  NAND _599_ (
    .A(_027_),
    .B(etapa1_preData2[4]),
    .Y(_196_)
  );
  NAND _600_ (
    .A(_195_),
    .B(_196_),
    .Y(_197_)
  );
  NAND _601_ (
    .A(_049_),
    .B(_197_),
    .Y(_198_)
  );
  NAND _602_ (
    .A(_194_),
    .B(_198_),
    .Y(_199_)
  );
  NAND _603_ (
    .A(_005_[8]),
    .B(_199_),
    .Y(_200_)
  );
  NAND _604_ (
    .A(etapa2_preData1[4]),
    .B(_090_),
    .Y(_201_)
  );
  NAND _605_ (
    .A(_200_),
    .B(_201_),
    .Y(_202_)
  );
  NAND _606_ (
    .A(_078_),
    .B(_202_),
    .Y(_203_)
  );
  NAND _607_ (
    .A(_190_),
    .B(_203_),
    .Y(outEtapaL2[4])
  );
  NAND _608_ (
    .A(data1[1]),
    .B(data1[5]),
    .Y(_204_)
  );
  NAND _609_ (
    .A(_018_),
    .B(etapa1_preData1[5]),
    .Y(_205_)
  );
  NAND _610_ (
    .A(_204_),
    .B(_205_),
    .Y(_206_)
  );
  NAND _611_ (
    .A(selectorL1),
    .B(_206_),
    .Y(_207_)
  );
  NAND _612_ (
    .A(data0[1]),
    .B(data0[5]),
    .Y(_208_)
  );
  NAND _613_ (
    .A(_008_),
    .B(etapa1_preData0[5]),
    .Y(_209_)
  );
  NAND _614_ (
    .A(_208_),
    .B(_209_),
    .Y(_210_)
  );
  NAND _615_ (
    .A(_049_),
    .B(_210_),
    .Y(_211_)
  );
  NAND _616_ (
    .A(_207_),
    .B(_211_),
    .Y(_212_)
  );
  NAND _617_ (
    .A(_004_[8]),
    .B(_212_),
    .Y(_213_)
  );
  NAND _618_ (
    .A(etapa2_preData0[5]),
    .B(_064_),
    .Y(_214_)
  );
  NAND _619_ (
    .A(_213_),
    .B(_214_),
    .Y(_215_)
  );
  NAND _620_ (
    .A(_007_),
    .B(_215_),
    .Y(_216_)
  );
  NAND _621_ (
    .A(data3[1]),
    .B(data3[5]),
    .Y(_217_)
  );
  NAND _622_ (
    .A(_036_),
    .B(etapa1_preData3[5]),
    .Y(_218_)
  );
  NAND _623_ (
    .A(_217_),
    .B(_218_),
    .Y(_219_)
  );
  NAND _624_ (
    .A(selectorL1),
    .B(_219_),
    .Y(_220_)
  );
  NAND _625_ (
    .A(data2[1]),
    .B(data2[5]),
    .Y(_221_)
  );
  NAND _626_ (
    .A(_027_),
    .B(etapa1_preData2[5]),
    .Y(_222_)
  );
  NAND _627_ (
    .A(_221_),
    .B(_222_),
    .Y(_223_)
  );
  NAND _628_ (
    .A(_049_),
    .B(_223_),
    .Y(_224_)
  );
  NAND _629_ (
    .A(_220_),
    .B(_224_),
    .Y(_225_)
  );
  NAND _630_ (
    .A(_005_[8]),
    .B(_225_),
    .Y(_226_)
  );
  NAND _631_ (
    .A(etapa2_preData1[5]),
    .B(_090_),
    .Y(_227_)
  );
  NAND _632_ (
    .A(_226_),
    .B(_227_),
    .Y(_228_)
  );
  NAND _633_ (
    .A(_078_),
    .B(_228_),
    .Y(_229_)
  );
  NAND _634_ (
    .A(_216_),
    .B(_229_),
    .Y(outEtapaL2[5])
  );
  NAND _635_ (
    .A(data1[1]),
    .B(data1[6]),
    .Y(_230_)
  );
  NAND _636_ (
    .A(_018_),
    .B(etapa1_preData1[6]),
    .Y(_231_)
  );
  NAND _637_ (
    .A(_230_),
    .B(_231_),
    .Y(_232_)
  );
  NAND _638_ (
    .A(selectorL1),
    .B(_232_),
    .Y(_233_)
  );
  NAND _639_ (
    .A(data0[1]),
    .B(data0[6]),
    .Y(_234_)
  );
  NAND _640_ (
    .A(_008_),
    .B(etapa1_preData0[6]),
    .Y(_235_)
  );
  NAND _641_ (
    .A(_234_),
    .B(_235_),
    .Y(_236_)
  );
  NAND _642_ (
    .A(_049_),
    .B(_236_),
    .Y(_237_)
  );
  NAND _643_ (
    .A(_233_),
    .B(_237_),
    .Y(_238_)
  );
  NAND _644_ (
    .A(_004_[8]),
    .B(_238_),
    .Y(_239_)
  );
  NAND _645_ (
    .A(etapa2_preData0[6]),
    .B(_064_),
    .Y(_240_)
  );
  NAND _646_ (
    .A(_239_),
    .B(_240_),
    .Y(_241_)
  );
  NAND _647_ (
    .A(_007_),
    .B(_241_),
    .Y(_242_)
  );
  NAND _648_ (
    .A(data3[1]),
    .B(data3[6]),
    .Y(_243_)
  );
  NAND _649_ (
    .A(_036_),
    .B(etapa1_preData3[6]),
    .Y(_244_)
  );
  NAND _650_ (
    .A(_243_),
    .B(_244_),
    .Y(_245_)
  );
  NAND _651_ (
    .A(selectorL1),
    .B(_245_),
    .Y(_246_)
  );
  NAND _652_ (
    .A(data2[1]),
    .B(data2[6]),
    .Y(_247_)
  );
  NAND _653_ (
    .A(_027_),
    .B(etapa1_preData2[6]),
    .Y(_248_)
  );
  NAND _654_ (
    .A(_247_),
    .B(_248_),
    .Y(_249_)
  );
  NAND _655_ (
    .A(_049_),
    .B(_249_),
    .Y(_250_)
  );
  NAND _656_ (
    .A(_246_),
    .B(_250_),
    .Y(_251_)
  );
  NAND _657_ (
    .A(_005_[8]),
    .B(_251_),
    .Y(_252_)
  );
  NAND _658_ (
    .A(etapa2_preData1[6]),
    .B(_090_),
    .Y(_253_)
  );
  NAND _659_ (
    .A(_252_),
    .B(_253_),
    .Y(_254_)
  );
  NAND _660_ (
    .A(_078_),
    .B(_254_),
    .Y(_255_)
  );
  NAND _661_ (
    .A(_242_),
    .B(_255_),
    .Y(outEtapaL2[6])
  );
  NAND _662_ (
    .A(data1[1]),
    .B(data1[7]),
    .Y(_256_)
  );
  NAND _663_ (
    .A(_018_),
    .B(etapa1_preData1[7]),
    .Y(_257_)
  );
  NAND _664_ (
    .A(_256_),
    .B(_257_),
    .Y(_258_)
  );
  NAND _665_ (
    .A(selectorL1),
    .B(_258_),
    .Y(_259_)
  );
  NAND _666_ (
    .A(data0[1]),
    .B(data0[7]),
    .Y(_260_)
  );
  NAND _667_ (
    .A(_008_),
    .B(etapa1_preData0[7]),
    .Y(_261_)
  );
  NAND _668_ (
    .A(_260_),
    .B(_261_),
    .Y(_262_)
  );
  NAND _669_ (
    .A(_049_),
    .B(_262_),
    .Y(_263_)
  );
  NAND _670_ (
    .A(_259_),
    .B(_263_),
    .Y(_264_)
  );
  NAND _671_ (
    .A(_004_[8]),
    .B(_264_),
    .Y(_265_)
  );
  NAND _672_ (
    .A(etapa2_preData0[7]),
    .B(_064_),
    .Y(_266_)
  );
  NAND _673_ (
    .A(_265_),
    .B(_266_),
    .Y(_267_)
  );
  NAND _674_ (
    .A(_007_),
    .B(_267_),
    .Y(_268_)
  );
  NAND _675_ (
    .A(data3[1]),
    .B(data3[7]),
    .Y(_269_)
  );
  NAND _676_ (
    .A(_036_),
    .B(etapa1_preData3[7]),
    .Y(_270_)
  );
  NAND _677_ (
    .A(_269_),
    .B(_270_),
    .Y(_271_)
  );
  NAND _678_ (
    .A(selectorL1),
    .B(_271_),
    .Y(_272_)
  );
  NAND _679_ (
    .A(data2[1]),
    .B(data2[7]),
    .Y(_273_)
  );
  NAND _680_ (
    .A(_027_),
    .B(etapa1_preData2[7]),
    .Y(_274_)
  );
  NAND _681_ (
    .A(_273_),
    .B(_274_),
    .Y(_275_)
  );
  NAND _682_ (
    .A(_049_),
    .B(_275_),
    .Y(_276_)
  );
  NAND _683_ (
    .A(_272_),
    .B(_276_),
    .Y(_277_)
  );
  NAND _684_ (
    .A(_005_[8]),
    .B(_277_),
    .Y(_278_)
  );
  NAND _685_ (
    .A(etapa2_preData1[7]),
    .B(_090_),
    .Y(_279_)
  );
  NAND _686_ (
    .A(_278_),
    .B(_279_),
    .Y(_280_)
  );
  NAND _687_ (
    .A(_078_),
    .B(_280_),
    .Y(_281_)
  );
  NAND _688_ (
    .A(_268_),
    .B(_281_),
    .Y(outEtapaL2[7])
  );
  NOR _689_ (
    .A(etapa2_preData0[8]),
    .B(_004_[8]),
    .Y(_282_)
  );
  NOR _690_ (
    .A(_051_),
    .B(_282_),
    .Y(_283_)
  );
  NOR _691_ (
    .A(etapa2_preData1[8]),
    .B(_005_[8]),
    .Y(_284_)
  );
  NOR _692_ (
    .A(_079_),
    .B(_284_),
    .Y(_285_)
  );
  NOR _693_ (
    .A(_283_),
    .B(_285_),
    .Y(_286_)
  );
  NOT _694_ (
    .A(_286_),
    .Y(outEtapaL2[8])
  );
  NAND _695_ (
    .A(reset),
    .B(_102_),
    .Y(_287_)
  );
  NOT _696_ (
    .A(_287_),
    .Y(_005_[0])
  );
  NAND _697_ (
    .A(reset),
    .B(_124_),
    .Y(_288_)
  );
  NOT _698_ (
    .A(_288_),
    .Y(_005_[1])
  );
  NAND _699_ (
    .A(reset),
    .B(_150_),
    .Y(_289_)
  );
  NOT _700_ (
    .A(_289_),
    .Y(_005_[2])
  );
  NAND _701_ (
    .A(reset),
    .B(_176_),
    .Y(_290_)
  );
  NOT _702_ (
    .A(_290_),
    .Y(_005_[3])
  );
  NAND _703_ (
    .A(reset),
    .B(_202_),
    .Y(_291_)
  );
  NOT _704_ (
    .A(_291_),
    .Y(_005_[4])
  );
  NAND _705_ (
    .A(reset),
    .B(_228_),
    .Y(_292_)
  );
  NOT _706_ (
    .A(_292_),
    .Y(_005_[5])
  );
  NAND _707_ (
    .A(reset),
    .B(_254_),
    .Y(_293_)
  );
  NOT _708_ (
    .A(_293_),
    .Y(_005_[6])
  );
  NAND _709_ (
    .A(reset),
    .B(_280_),
    .Y(_294_)
  );
  NOT _710_ (
    .A(_294_),
    .Y(_005_[7])
  );
  NAND _711_ (
    .A(reset),
    .B(_076_),
    .Y(_295_)
  );
  NOT _712_ (
    .A(_295_),
    .Y(_004_[0])
  );
  NAND _713_ (
    .A(reset),
    .B(_113_),
    .Y(_296_)
  );
  NOT _714_ (
    .A(_296_),
    .Y(_004_[1])
  );
  NAND _715_ (
    .A(reset),
    .B(_137_),
    .Y(_297_)
  );
  NOT _716_ (
    .A(_297_),
    .Y(_004_[2])
  );
  NAND _717_ (
    .A(reset),
    .B(_163_),
    .Y(_298_)
  );
  NOT _718_ (
    .A(_298_),
    .Y(_004_[3])
  );
  NAND _719_ (
    .A(reset),
    .B(_189_),
    .Y(_299_)
  );
  NOT _720_ (
    .A(_299_),
    .Y(_004_[4])
  );
  NAND _721_ (
    .A(reset),
    .B(_215_),
    .Y(_300_)
  );
  NOT _722_ (
    .A(_300_),
    .Y(_004_[5])
  );
  NAND _723_ (
    .A(reset),
    .B(_241_),
    .Y(_301_)
  );
  NOT _724_ (
    .A(_301_),
    .Y(_004_[6])
  );
  NAND _725_ (
    .A(reset),
    .B(_267_),
    .Y(_302_)
  );
  NOT _726_ (
    .A(_302_),
    .Y(_004_[7])
  );
  NAND _727_ (
    .A(_034_),
    .B(data3[8]),
    .Y(_303_)
  );
  NAND _728_ (
    .A(reset),
    .B(_303_),
    .Y(_304_)
  );
  NOR _729_ (
    .A(etapa1_preData3[0]),
    .B(data3[8]),
    .Y(_305_)
  );
  NOR _730_ (
    .A(_304_),
    .B(_305_),
    .Y(_003_[0])
  );
  NAND _731_ (
    .A(_035_),
    .B(etapa1_preData3[1]),
    .Y(_306_)
  );
  NAND _732_ (
    .A(_086_),
    .B(_306_),
    .Y(_307_)
  );
  NAND _733_ (
    .A(reset),
    .B(_307_),
    .Y(_308_)
  );
  NOT _734_ (
    .A(_308_),
    .Y(_003_[1])
  );
  NAND _735_ (
    .A(data3[8]),
    .B(_037_),
    .Y(_309_)
  );
  NAND _736_ (
    .A(reset),
    .B(_309_),
    .Y(_310_)
  );
  NOR _737_ (
    .A(data3[8]),
    .B(etapa1_preData3[2]),
    .Y(_311_)
  );
  NOR _738_ (
    .A(_310_),
    .B(_311_),
    .Y(_003_[2])
  );
  NAND _739_ (
    .A(data3[8]),
    .B(_038_),
    .Y(_312_)
  );
  NAND _740_ (
    .A(reset),
    .B(_312_),
    .Y(_313_)
  );
  NOR _741_ (
    .A(data3[8]),
    .B(etapa1_preData3[3]),
    .Y(_314_)
  );
  NOR _742_ (
    .A(_313_),
    .B(_314_),
    .Y(_003_[3])
  );
  NAND _743_ (
    .A(data3[8]),
    .B(_039_),
    .Y(_315_)
  );
  NAND _744_ (
    .A(reset),
    .B(_315_),
    .Y(_316_)
  );
  NOR _745_ (
    .A(data3[8]),
    .B(etapa1_preData3[4]),
    .Y(_317_)
  );
  NOR _746_ (
    .A(_316_),
    .B(_317_),
    .Y(_003_[4])
  );
  NAND _747_ (
    .A(data3[8]),
    .B(_040_),
    .Y(_318_)
  );
  NAND _748_ (
    .A(reset),
    .B(_318_),
    .Y(_319_)
  );
  NOR _749_ (
    .A(data3[8]),
    .B(etapa1_preData3[5]),
    .Y(_320_)
  );
  NOR _750_ (
    .A(_319_),
    .B(_320_),
    .Y(_003_[5])
  );
  NAND _751_ (
    .A(data3[8]),
    .B(_041_),
    .Y(_321_)
  );
  NAND _752_ (
    .A(reset),
    .B(_321_),
    .Y(_322_)
  );
  NOR _753_ (
    .A(data3[8]),
    .B(etapa1_preData3[6]),
    .Y(_323_)
  );
  NOR _754_ (
    .A(_322_),
    .B(_323_),
    .Y(_003_[6])
  );
  NAND _755_ (
    .A(data3[8]),
    .B(_042_),
    .Y(_324_)
  );
  NAND _756_ (
    .A(reset),
    .B(_324_),
    .Y(_325_)
  );
  NOR _757_ (
    .A(data3[8]),
    .B(etapa1_preData3[7]),
    .Y(_326_)
  );
  NOR _758_ (
    .A(_325_),
    .B(_326_),
    .Y(_003_[7])
  );
  NAND _759_ (
    .A(data3[8]),
    .B(reset),
    .Y(_327_)
  );
  NOT _760_ (
    .A(_327_),
    .Y(_003_[8])
  );
  NAND _761_ (
    .A(_025_),
    .B(data2[8]),
    .Y(_328_)
  );
  NAND _762_ (
    .A(reset),
    .B(_328_),
    .Y(_329_)
  );
  NOR _763_ (
    .A(etapa1_preData2[0]),
    .B(data2[8]),
    .Y(_330_)
  );
  NOR _764_ (
    .A(_329_),
    .B(_330_),
    .Y(_002_[0])
  );
  NAND _765_ (
    .A(_026_),
    .B(etapa1_preData2[1]),
    .Y(_331_)
  );
  NAND _766_ (
    .A(_081_),
    .B(_331_),
    .Y(_332_)
  );
  NAND _767_ (
    .A(reset),
    .B(_332_),
    .Y(_333_)
  );
  NOT _768_ (
    .A(_333_),
    .Y(_002_[1])
  );
  NAND _769_ (
    .A(data2[8]),
    .B(_028_),
    .Y(_334_)
  );
  NAND _770_ (
    .A(reset),
    .B(_334_),
    .Y(_335_)
  );
  NOR _771_ (
    .A(data2[8]),
    .B(etapa1_preData2[2]),
    .Y(_336_)
  );
  NOR _772_ (
    .A(_335_),
    .B(_336_),
    .Y(_002_[2])
  );
  NAND _773_ (
    .A(data2[8]),
    .B(_029_),
    .Y(_337_)
  );
  NAND _774_ (
    .A(reset),
    .B(_337_),
    .Y(_338_)
  );
  NOR _775_ (
    .A(data2[8]),
    .B(etapa1_preData2[3]),
    .Y(_339_)
  );
  NOR _776_ (
    .A(_338_),
    .B(_339_),
    .Y(_002_[3])
  );
  NAND _777_ (
    .A(data2[8]),
    .B(_030_),
    .Y(_340_)
  );
  NAND _778_ (
    .A(reset),
    .B(_340_),
    .Y(_341_)
  );
  NOR _779_ (
    .A(data2[8]),
    .B(etapa1_preData2[4]),
    .Y(_342_)
  );
  NOR _780_ (
    .A(_341_),
    .B(_342_),
    .Y(_002_[4])
  );
  NAND _781_ (
    .A(data2[8]),
    .B(_031_),
    .Y(_343_)
  );
  NAND _782_ (
    .A(reset),
    .B(_343_),
    .Y(_344_)
  );
  NOR _783_ (
    .A(data2[8]),
    .B(etapa1_preData2[5]),
    .Y(_345_)
  );
  NOR _784_ (
    .A(_344_),
    .B(_345_),
    .Y(_002_[5])
  );
  NAND _785_ (
    .A(data2[8]),
    .B(_032_),
    .Y(_346_)
  );
  NAND _786_ (
    .A(reset),
    .B(_346_),
    .Y(_347_)
  );
  NOR _787_ (
    .A(data2[8]),
    .B(etapa1_preData2[6]),
    .Y(_348_)
  );
  NOR _788_ (
    .A(_347_),
    .B(_348_),
    .Y(_002_[6])
  );
  NAND _789_ (
    .A(data2[8]),
    .B(_033_),
    .Y(_349_)
  );
  NAND _790_ (
    .A(reset),
    .B(_349_),
    .Y(_350_)
  );
  NOR _791_ (
    .A(data2[8]),
    .B(etapa1_preData2[7]),
    .Y(_351_)
  );
  NOR _792_ (
    .A(_350_),
    .B(_351_),
    .Y(_002_[7])
  );
  NAND _793_ (
    .A(data2[8]),
    .B(reset),
    .Y(_352_)
  );
  NOT _794_ (
    .A(_352_),
    .Y(_002_[8])
  );
  NAND _795_ (
    .A(_016_),
    .B(data1[8]),
    .Y(_353_)
  );
  NAND _796_ (
    .A(reset),
    .B(_353_),
    .Y(_354_)
  );
  NOR _797_ (
    .A(etapa1_preData1[0]),
    .B(data1[8]),
    .Y(_355_)
  );
  NOR _798_ (
    .A(_354_),
    .B(_355_),
    .Y(_001_[0])
  );
  NAND _799_ (
    .A(_017_),
    .B(etapa1_preData1[1]),
    .Y(_356_)
  );
  NAND _800_ (
    .A(_059_),
    .B(_356_),
    .Y(_357_)
  );
  NAND _801_ (
    .A(reset),
    .B(_357_),
    .Y(_358_)
  );
  NOT _802_ (
    .A(_358_),
    .Y(_001_[1])
  );
  NAND _803_ (
    .A(data1[8]),
    .B(_019_),
    .Y(_359_)
  );
  NAND _804_ (
    .A(reset),
    .B(_359_),
    .Y(_360_)
  );
  NOR _805_ (
    .A(data1[8]),
    .B(etapa1_preData1[2]),
    .Y(_361_)
  );
  NOR _806_ (
    .A(_360_),
    .B(_361_),
    .Y(_001_[2])
  );
  NAND _807_ (
    .A(data1[8]),
    .B(_020_),
    .Y(_362_)
  );
  NAND _808_ (
    .A(reset),
    .B(_362_),
    .Y(_363_)
  );
  NOR _809_ (
    .A(data1[8]),
    .B(etapa1_preData1[3]),
    .Y(_364_)
  );
  NOR _810_ (
    .A(_363_),
    .B(_364_),
    .Y(_001_[3])
  );
  NAND _811_ (
    .A(data1[8]),
    .B(_021_),
    .Y(_365_)
  );
  NAND _812_ (
    .A(reset),
    .B(_365_),
    .Y(_366_)
  );
  NOR _813_ (
    .A(data1[8]),
    .B(etapa1_preData1[4]),
    .Y(_367_)
  );
  NOR _814_ (
    .A(_366_),
    .B(_367_),
    .Y(_001_[4])
  );
  NAND _815_ (
    .A(data1[8]),
    .B(_022_),
    .Y(_368_)
  );
  NAND _816_ (
    .A(reset),
    .B(_368_),
    .Y(_369_)
  );
  NOR _817_ (
    .A(data1[8]),
    .B(etapa1_preData1[5]),
    .Y(_370_)
  );
  NOR _818_ (
    .A(_369_),
    .B(_370_),
    .Y(_001_[5])
  );
  NAND _819_ (
    .A(data1[8]),
    .B(_023_),
    .Y(_371_)
  );
  NAND _820_ (
    .A(reset),
    .B(_371_),
    .Y(_372_)
  );
  NOR _821_ (
    .A(data1[8]),
    .B(etapa1_preData1[6]),
    .Y(_373_)
  );
  NOR _822_ (
    .A(_372_),
    .B(_373_),
    .Y(_001_[6])
  );
  NAND _823_ (
    .A(data1[8]),
    .B(_024_),
    .Y(_374_)
  );
  NAND _824_ (
    .A(reset),
    .B(_374_),
    .Y(_375_)
  );
  NOR _825_ (
    .A(data1[8]),
    .B(etapa1_preData1[7]),
    .Y(_376_)
  );
  NOR _826_ (
    .A(_375_),
    .B(_376_),
    .Y(_001_[7])
  );
  NAND _827_ (
    .A(data1[8]),
    .B(reset),
    .Y(_377_)
  );
  NOT _828_ (
    .A(_377_),
    .Y(_001_[8])
  );
  NAND _829_ (
    .A(data0[8]),
    .B(_045_),
    .Y(_378_)
  );
  NAND _830_ (
    .A(reset),
    .B(_378_),
    .Y(_379_)
  );
  NOR _831_ (
    .A(data0[8]),
    .B(etapa1_preData0[0]),
    .Y(_380_)
  );
  NOR _832_ (
    .A(_379_),
    .B(_380_),
    .Y(_000_[0])
  );
  NAND _833_ (
    .A(etapa1_preData0[1]),
    .B(_009_),
    .Y(_381_)
  );
  NAND _834_ (
    .A(_053_),
    .B(_381_),
    .Y(_382_)
  );
  NAND _835_ (
    .A(reset),
    .B(_382_),
    .Y(_383_)
  );
  NOT _836_ (
    .A(_383_),
    .Y(_000_[1])
  );
  NAND _837_ (
    .A(data0[8]),
    .B(_010_),
    .Y(_384_)
  );
  NAND _838_ (
    .A(reset),
    .B(_384_),
    .Y(_385_)
  );
  NOR _839_ (
    .A(data0[8]),
    .B(etapa1_preData0[2]),
    .Y(_386_)
  );
  NOR _840_ (
    .A(_385_),
    .B(_386_),
    .Y(_000_[2])
  );
  NAND _841_ (
    .A(data0[8]),
    .B(_011_),
    .Y(_387_)
  );
  NAND _842_ (
    .A(reset),
    .B(_387_),
    .Y(_388_)
  );
  NOR _843_ (
    .A(data0[8]),
    .B(etapa1_preData0[3]),
    .Y(_389_)
  );
  NOR _844_ (
    .A(_388_),
    .B(_389_),
    .Y(_000_[3])
  );
  NAND _845_ (
    .A(data0[8]),
    .B(_012_),
    .Y(_390_)
  );
  NAND _846_ (
    .A(reset),
    .B(_390_),
    .Y(_391_)
  );
  NOR _847_ (
    .A(data0[8]),
    .B(etapa1_preData0[4]),
    .Y(_392_)
  );
  NOR _848_ (
    .A(_391_),
    .B(_392_),
    .Y(_000_[4])
  );
  NAND _849_ (
    .A(data0[8]),
    .B(_013_),
    .Y(_393_)
  );
  NAND _850_ (
    .A(reset),
    .B(_393_),
    .Y(_394_)
  );
  NOR _851_ (
    .A(data0[8]),
    .B(etapa1_preData0[5]),
    .Y(_395_)
  );
  NOR _852_ (
    .A(_394_),
    .B(_395_),
    .Y(_000_[5])
  );
  NAND _853_ (
    .A(data0[8]),
    .B(_014_),
    .Y(_396_)
  );
  NAND _854_ (
    .A(reset),
    .B(_396_),
    .Y(_397_)
  );
  NOR _855_ (
    .A(data0[8]),
    .B(etapa1_preData0[6]),
    .Y(_398_)
  );
  NOR _856_ (
    .A(_397_),
    .B(_398_),
    .Y(_000_[6])
  );
  NAND _857_ (
    .A(data0[8]),
    .B(_015_),
    .Y(_399_)
  );
  NAND _858_ (
    .A(reset),
    .B(_399_),
    .Y(_400_)
  );
  NOR _859_ (
    .A(data0[8]),
    .B(etapa1_preData0[7]),
    .Y(_401_)
  );
  NOR _860_ (
    .A(_400_),
    .B(_401_),
    .Y(_000_[7])
  );
  NAND _861_ (
    .A(data0[8]),
    .B(reset),
    .Y(_402_)
  );
  NOT _862_ (
    .A(_402_),
    .Y(_000_[8])
  );
  (* src = "phy_tx.v:41" *)
  DFF _863_ (
    .C(clk_2f),
    .D(_007_),
    .Q(selectorL2)
  );
  (* src = "phy_tx.v:41" *)
  DFF _864_ (
    .C(clk_2f),
    .D(_004_[0]),
    .Q(etapa2_preData0[0])
  );
  (* src = "phy_tx.v:41" *)
  DFF _865_ (
    .C(clk_2f),
    .D(_004_[1]),
    .Q(etapa2_preData0[1])
  );
  (* src = "phy_tx.v:41" *)
  DFF _866_ (
    .C(clk_2f),
    .D(_004_[2]),
    .Q(etapa2_preData0[2])
  );
  (* src = "phy_tx.v:41" *)
  DFF _867_ (
    .C(clk_2f),
    .D(_004_[3]),
    .Q(etapa2_preData0[3])
  );
  (* src = "phy_tx.v:41" *)
  DFF _868_ (
    .C(clk_2f),
    .D(_004_[4]),
    .Q(etapa2_preData0[4])
  );
  (* src = "phy_tx.v:41" *)
  DFF _869_ (
    .C(clk_2f),
    .D(_004_[5]),
    .Q(etapa2_preData0[5])
  );
  (* src = "phy_tx.v:41" *)
  DFF _870_ (
    .C(clk_2f),
    .D(_004_[6]),
    .Q(etapa2_preData0[6])
  );
  (* src = "phy_tx.v:41" *)
  DFF _871_ (
    .C(clk_2f),
    .D(_004_[7]),
    .Q(etapa2_preData0[7])
  );
  (* src = "phy_tx.v:41" *)
  DFF _872_ (
    .C(clk_2f),
    .D(_004_[8]),
    .Q(etapa2_preData0[8])
  );
  (* src = "phy_tx.v:41" *)
  DFF _873_ (
    .C(clk_2f),
    .D(_005_[0]),
    .Q(etapa2_preData1[0])
  );
  (* src = "phy_tx.v:41" *)
  DFF _874_ (
    .C(clk_2f),
    .D(_005_[1]),
    .Q(etapa2_preData1[1])
  );
  (* src = "phy_tx.v:41" *)
  DFF _875_ (
    .C(clk_2f),
    .D(_005_[2]),
    .Q(etapa2_preData1[2])
  );
  (* src = "phy_tx.v:41" *)
  DFF _876_ (
    .C(clk_2f),
    .D(_005_[3]),
    .Q(etapa2_preData1[3])
  );
  (* src = "phy_tx.v:41" *)
  DFF _877_ (
    .C(clk_2f),
    .D(_005_[4]),
    .Q(etapa2_preData1[4])
  );
  (* src = "phy_tx.v:41" *)
  DFF _878_ (
    .C(clk_2f),
    .D(_005_[5]),
    .Q(etapa2_preData1[5])
  );
  (* src = "phy_tx.v:41" *)
  DFF _879_ (
    .C(clk_2f),
    .D(_005_[6]),
    .Q(etapa2_preData1[6])
  );
  (* src = "phy_tx.v:41" *)
  DFF _880_ (
    .C(clk_2f),
    .D(_005_[7]),
    .Q(etapa2_preData1[7])
  );
  (* src = "phy_tx.v:41" *)
  DFF _881_ (
    .C(clk_2f),
    .D(_005_[8]),
    .Q(etapa2_preData1[8])
  );
  (* src = "phy_tx.v:20" *)
  DFF _882_ (
    .C(clk_f),
    .D(_006_),
    .Q(selectorL1)
  );
  (* src = "phy_tx.v:20" *)
  DFF _883_ (
    .C(clk_f),
    .D(_000_[0]),
    .Q(etapa1_preData0[0])
  );
  (* src = "phy_tx.v:20" *)
  DFF _884_ (
    .C(clk_f),
    .D(_000_[1]),
    .Q(etapa1_preData0[1])
  );
  (* src = "phy_tx.v:20" *)
  DFF _885_ (
    .C(clk_f),
    .D(_000_[2]),
    .Q(etapa1_preData0[2])
  );
  (* src = "phy_tx.v:20" *)
  DFF _886_ (
    .C(clk_f),
    .D(_000_[3]),
    .Q(etapa1_preData0[3])
  );
  (* src = "phy_tx.v:20" *)
  DFF _887_ (
    .C(clk_f),
    .D(_000_[4]),
    .Q(etapa1_preData0[4])
  );
  (* src = "phy_tx.v:20" *)
  DFF _888_ (
    .C(clk_f),
    .D(_000_[5]),
    .Q(etapa1_preData0[5])
  );
  (* src = "phy_tx.v:20" *)
  DFF _889_ (
    .C(clk_f),
    .D(_000_[6]),
    .Q(etapa1_preData0[6])
  );
  (* src = "phy_tx.v:20" *)
  DFF _890_ (
    .C(clk_f),
    .D(_000_[7]),
    .Q(etapa1_preData0[7])
  );
  (* src = "phy_tx.v:20" *)
  DFF _891_ (
    .C(clk_f),
    .D(_000_[8]),
    .Q(etapa1_preData0[8])
  );
  (* src = "phy_tx.v:20" *)
  DFF _892_ (
    .C(clk_f),
    .D(_001_[0]),
    .Q(etapa1_preData1[0])
  );
  (* src = "phy_tx.v:20" *)
  DFF _893_ (
    .C(clk_f),
    .D(_001_[1]),
    .Q(etapa1_preData1[1])
  );
  (* src = "phy_tx.v:20" *)
  DFF _894_ (
    .C(clk_f),
    .D(_001_[2]),
    .Q(etapa1_preData1[2])
  );
  (* src = "phy_tx.v:20" *)
  DFF _895_ (
    .C(clk_f),
    .D(_001_[3]),
    .Q(etapa1_preData1[3])
  );
  (* src = "phy_tx.v:20" *)
  DFF _896_ (
    .C(clk_f),
    .D(_001_[4]),
    .Q(etapa1_preData1[4])
  );
  (* src = "phy_tx.v:20" *)
  DFF _897_ (
    .C(clk_f),
    .D(_001_[5]),
    .Q(etapa1_preData1[5])
  );
  (* src = "phy_tx.v:20" *)
  DFF _898_ (
    .C(clk_f),
    .D(_001_[6]),
    .Q(etapa1_preData1[6])
  );
  (* src = "phy_tx.v:20" *)
  DFF _899_ (
    .C(clk_f),
    .D(_001_[7]),
    .Q(etapa1_preData1[7])
  );
  (* src = "phy_tx.v:20" *)
  DFF _900_ (
    .C(clk_f),
    .D(_001_[8]),
    .Q(etapa1_preData1[8])
  );
  (* src = "phy_tx.v:20" *)
  DFF _901_ (
    .C(clk_f),
    .D(_002_[0]),
    .Q(etapa1_preData2[0])
  );
  (* src = "phy_tx.v:20" *)
  DFF _902_ (
    .C(clk_f),
    .D(_002_[1]),
    .Q(etapa1_preData2[1])
  );
  (* src = "phy_tx.v:20" *)
  DFF _903_ (
    .C(clk_f),
    .D(_002_[2]),
    .Q(etapa1_preData2[2])
  );
  (* src = "phy_tx.v:20" *)
  DFF _904_ (
    .C(clk_f),
    .D(_002_[3]),
    .Q(etapa1_preData2[3])
  );
  (* src = "phy_tx.v:20" *)
  DFF _905_ (
    .C(clk_f),
    .D(_002_[4]),
    .Q(etapa1_preData2[4])
  );
  (* src = "phy_tx.v:20" *)
  DFF _906_ (
    .C(clk_f),
    .D(_002_[5]),
    .Q(etapa1_preData2[5])
  );
  (* src = "phy_tx.v:20" *)
  DFF _907_ (
    .C(clk_f),
    .D(_002_[6]),
    .Q(etapa1_preData2[6])
  );
  (* src = "phy_tx.v:20" *)
  DFF _908_ (
    .C(clk_f),
    .D(_002_[7]),
    .Q(etapa1_preData2[7])
  );
  (* src = "phy_tx.v:20" *)
  DFF _909_ (
    .C(clk_f),
    .D(_002_[8]),
    .Q(etapa1_preData2[8])
  );
  (* src = "phy_tx.v:20" *)
  DFF _910_ (
    .C(clk_f),
    .D(_003_[0]),
    .Q(etapa1_preData3[0])
  );
  (* src = "phy_tx.v:20" *)
  DFF _911_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(etapa1_preData3[1])
  );
  (* src = "phy_tx.v:20" *)
  DFF _912_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(etapa1_preData3[2])
  );
  (* src = "phy_tx.v:20" *)
  DFF _913_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(etapa1_preData3[3])
  );
  (* src = "phy_tx.v:20" *)
  DFF _914_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(etapa1_preData3[4])
  );
  (* src = "phy_tx.v:20" *)
  DFF _915_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(etapa1_preData3[5])
  );
  (* src = "phy_tx.v:20" *)
  DFF _916_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(etapa1_preData3[6])
  );
  (* src = "phy_tx.v:20" *)
  DFF _917_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(etapa1_preData3[7])
  );
  (* src = "phy_tx.v:20" *)
  DFF _918_ (
    .C(clk_f),
    .D(_003_[8]),
    .Q(etapa1_preData3[8])
  );
endmodule
