/* Generated by Yosys 0.7+659 (git sha1 51f1bbe, clang 3.5.0-10 -fPIC -Os) */

module ClkGeneratorEstructural(clk16f, reset_L, clk4f, clk2f, clkf);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [1:0] _04_;
  wire [2:0] _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  input clk16f;
  output clk2f;
  output clk4f;
  output clkf;
  wire counter1;
  wire [1:0] counter2;
  wire [2:0] counter3;
  input reset_L;
  NOT _35_ (
    .A(counter3[0]),
    .Y(_06_)
  );
  NOT _36_ (
    .A(counter3[1]),
    .Y(_07_)
  );
  NOT _37_ (
    .A(counter3[2]),
    .Y(_08_)
  );
  NOT _38_ (
    .A(reset_L),
    .Y(_09_)
  );
  NOR _39_ (
    .A(counter3[0]),
    .B(_09_),
    .Y(_05_[0])
  );
  NOR _40_ (
    .A(_06_),
    .B(_07_),
    .Y(_10_)
  );
  NAND _41_ (
    .A(counter3[0]),
    .B(counter3[1]),
    .Y(_11_)
  );
  NOR _42_ (
    .A(counter3[0]),
    .B(counter3[1]),
    .Y(_12_)
  );
  NOT _43_ (
    .A(_12_),
    .Y(_13_)
  );
  NAND _44_ (
    .A(reset_L),
    .B(_13_),
    .Y(_14_)
  );
  NOR _45_ (
    .A(_10_),
    .B(_14_),
    .Y(_05_[1])
  );
  NAND _46_ (
    .A(counter3[2]),
    .B(_10_),
    .Y(_15_)
  );
  NOT _47_ (
    .A(_15_),
    .Y(_16_)
  );
  NAND _48_ (
    .A(_08_),
    .B(_11_),
    .Y(_17_)
  );
  NAND _49_ (
    .A(reset_L),
    .B(_17_),
    .Y(_18_)
  );
  NOR _50_ (
    .A(_16_),
    .B(_18_),
    .Y(_05_[2])
  );
  NOR _51_ (
    .A(_09_),
    .B(counter2[0]),
    .Y(_04_[0])
  );
  NAND _52_ (
    .A(counter2[0]),
    .B(counter2[1]),
    .Y(_19_)
  );
  NOT _53_ (
    .A(_19_),
    .Y(_20_)
  );
  NOR _54_ (
    .A(counter2[0]),
    .B(counter2[1]),
    .Y(_21_)
  );
  NOT _55_ (
    .A(_21_),
    .Y(_22_)
  );
  NAND _56_ (
    .A(reset_L),
    .B(_22_),
    .Y(_23_)
  );
  NOR _57_ (
    .A(_20_),
    .B(_23_),
    .Y(_04_[1])
  );
  NOR _58_ (
    .A(_09_),
    .B(counter1),
    .Y(_03_)
  );
  NAND _59_ (
    .A(clkf),
    .B(_15_),
    .Y(_24_)
  );
  NOR _60_ (
    .A(clkf),
    .B(_15_),
    .Y(_25_)
  );
  NOR _61_ (
    .A(_09_),
    .B(_25_),
    .Y(_26_)
  );
  NAND _62_ (
    .A(_24_),
    .B(_26_),
    .Y(_02_)
  );
  NOR _63_ (
    .A(clk2f),
    .B(_19_),
    .Y(_27_)
  );
  NAND _64_ (
    .A(clk2f),
    .B(_19_),
    .Y(_28_)
  );
  NOT _65_ (
    .A(_28_),
    .Y(_29_)
  );
  NOR _66_ (
    .A(_27_),
    .B(_29_),
    .Y(_30_)
  );
  NAND _67_ (
    .A(reset_L),
    .B(_30_),
    .Y(_00_)
  );
  NOR _68_ (
    .A(counter1),
    .B(clk4f),
    .Y(_31_)
  );
  NOT _69_ (
    .A(_31_),
    .Y(_32_)
  );
  NAND _70_ (
    .A(counter1),
    .B(clk4f),
    .Y(_33_)
  );
  NAND _71_ (
    .A(_32_),
    .B(_33_),
    .Y(_34_)
  );
  NAND _72_ (
    .A(reset_L),
    .B(_34_),
    .Y(_01_)
  );
  DFF _73_ (
    .C(clk16f),
    .D(_01_),
    .Q(clk4f)
  );
  DFF _74_ (
    .C(clk16f),
    .D(_00_),
    .Q(clk2f)
  );
  DFF _75_ (
    .C(clk16f),
    .D(_02_),
    .Q(clkf)
  );
  DFF _76_ (
    .C(clk16f),
    .D(_03_),
    .Q(counter1)
  );
  DFF _77_ (
    .C(clk16f),
    .D(_04_[0]),
    .Q(counter2[0])
  );
  DFF _78_ (
    .C(clk16f),
    .D(_04_[1]),
    .Q(counter2[1])
  );
  DFF _79_ (
    .C(clk16f),
    .D(_05_[0]),
    .Q(counter3[0])
  );
  DFF _80_ (
    .C(clk16f),
    .D(_05_[1]),
    .Q(counter3[1])
  );
  DFF _81_ (
    .C(clk16f),
    .D(_05_[2]),
    .Q(counter3[2])
  );
endmodule
