/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-10 -O2 -fdebug-prefix-map=/build/yosys-0DEyT5/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "ParaleloSerialEst.v:1" *)
module ParaleloSerialEst(clk16f, clk4f, reset, reset_L, paralelo, serial);
  (* src = "ParaleloSerialEst.v:12" *)
  wire [1:0] _00_;
  (* src = "ParaleloSerialEst.v:12" *)
  wire [1:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  (* src = "ParaleloSerialEst.v:2" *)
  input clk16f;
  (* src = "ParaleloSerialEst.v:3" *)
  input clk4f;
  (* src = "ParaleloSerialEst.v:9" *)
  wire [1:0] counterbc;
  (* src = "ParaleloSerialEst.v:10" *)
  wire [1:0] counterdata;
  (* src = "ParaleloSerialEst.v:6" *)
  input [8:0] paralelo;
  (* src = "ParaleloSerialEst.v:4" *)
  input reset;
  (* src = "ParaleloSerialEst.v:5" *)
  input reset_L;
  (* src = "ParaleloSerialEst.v:7" *)
  output [1:0] serial;
  NOR _46_ (
    .A(counterbc[1]),
    .B(counterbc[0]),
    .Y(_02_)
  );
  NOT _47_ (
    .A(paralelo[8]),
    .Y(_03_)
  );
  NAND _48_ (
    .A(counterbc[1]),
    .B(counterbc[0]),
    .Y(_04_)
  );
  NAND _49_ (
    .A(_04_),
    .B(_03_),
    .Y(_05_)
  );
  NOR _50_ (
    .A(_05_),
    .B(_02_),
    .Y(_06_)
  );
  NOT _51_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR _52_ (
    .A(counterdata[1]),
    .B(counterdata[0]),
    .Y(_08_)
  );
  NAND _53_ (
    .A(_08_),
    .B(paralelo[6]),
    .Y(_09_)
  );
  NOT _54_ (
    .A(counterdata[1]),
    .Y(_10_)
  );
  NOR _55_ (
    .A(paralelo[2]),
    .B(counterdata[0]),
    .Y(_11_)
  );
  NOR _56_ (
    .A(_11_),
    .B(_10_),
    .Y(_12_)
  );
  NOT _57_ (
    .A(counterdata[0]),
    .Y(_13_)
  );
  NOT _58_ (
    .A(paralelo[4]),
    .Y(_14_)
  );
  NOR _59_ (
    .A(_14_),
    .B(_13_),
    .Y(_15_)
  );
  NOR _60_ (
    .A(_15_),
    .B(_12_),
    .Y(_16_)
  );
  NAND _61_ (
    .A(_16_),
    .B(_09_),
    .Y(_17_)
  );
  NAND _62_ (
    .A(counterdata[1]),
    .B(counterdata[0]),
    .Y(_18_)
  );
  NOR _63_ (
    .A(_18_),
    .B(paralelo[0]),
    .Y(_19_)
  );
  NOR _64_ (
    .A(_19_),
    .B(_03_),
    .Y(_20_)
  );
  NAND _65_ (
    .A(_20_),
    .B(_17_),
    .Y(_21_)
  );
  NAND _66_ (
    .A(_21_),
    .B(_07_),
    .Y(serial[0])
  );
  NAND _67_ (
    .A(_08_),
    .B(paralelo[7]),
    .Y(_22_)
  );
  NOT _68_ (
    .A(paralelo[3]),
    .Y(_23_)
  );
  NAND _69_ (
    .A(_23_),
    .B(_13_),
    .Y(_24_)
  );
  NAND _70_ (
    .A(paralelo[5]),
    .B(counterdata[0]),
    .Y(_25_)
  );
  NAND _71_ (
    .A(_25_),
    .B(_10_),
    .Y(_26_)
  );
  NAND _72_ (
    .A(_26_),
    .B(_24_),
    .Y(_27_)
  );
  NAND _73_ (
    .A(_27_),
    .B(_22_),
    .Y(_28_)
  );
  NOR _74_ (
    .A(_18_),
    .B(paralelo[1]),
    .Y(_29_)
  );
  NOR _75_ (
    .A(_29_),
    .B(_03_),
    .Y(_30_)
  );
  NAND _76_ (
    .A(_30_),
    .B(_28_),
    .Y(_31_)
  );
  NAND _77_ (
    .A(_31_),
    .B(_05_),
    .Y(serial[1])
  );
  NAND _78_ (
    .A(paralelo[8]),
    .B(counterdata[0]),
    .Y(_32_)
  );
  NOT _79_ (
    .A(_32_),
    .Y(_33_)
  );
  NAND _80_ (
    .A(_03_),
    .B(_13_),
    .Y(_34_)
  );
  NAND _81_ (
    .A(_34_),
    .B(reset_L),
    .Y(_35_)
  );
  NOR _82_ (
    .A(_35_),
    .B(_33_),
    .Y(_01_[0])
  );
  NOT _83_ (
    .A(reset_L),
    .Y(_36_)
  );
  NOR _84_ (
    .A(_33_),
    .B(_10_),
    .Y(_37_)
  );
  NOR _85_ (
    .A(_32_),
    .B(counterdata[1]),
    .Y(_38_)
  );
  NOR _86_ (
    .A(_38_),
    .B(_37_),
    .Y(_39_)
  );
  NOR _87_ (
    .A(_39_),
    .B(_36_),
    .Y(_01_[1])
  );
  NOR _88_ (
    .A(_03_),
    .B(counterbc[0]),
    .Y(_40_)
  );
  NAND _89_ (
    .A(_03_),
    .B(counterbc[0]),
    .Y(_41_)
  );
  NAND _90_ (
    .A(_41_),
    .B(reset_L),
    .Y(_42_)
  );
  NOR _91_ (
    .A(_42_),
    .B(_40_),
    .Y(_00_[0])
  );
  NOT _92_ (
    .A(counterbc[1]),
    .Y(_43_)
  );
  NOR _93_ (
    .A(_03_),
    .B(_43_),
    .Y(_44_)
  );
  NOR _94_ (
    .A(_44_),
    .B(_06_),
    .Y(_45_)
  );
  NOR _95_ (
    .A(_45_),
    .B(_36_),
    .Y(_00_[1])
  );
  DFF _96_ (
    .C(clk16f),
    .D(_00_[0]),
    .Q(counterbc[0])
  );
  DFF _97_ (
    .C(clk16f),
    .D(_00_[1]),
    .Q(counterbc[1])
  );
  DFF _98_ (
    .C(clk16f),
    .D(_01_[0]),
    .Q(counterdata[0])
  );
  DFF _99_ (
    .C(clk16f),
    .D(_01_[1]),
    .Q(counterdata[1])
  );
endmodule

(* src = "demuxEst.v:3" *)
module demuxEst(clk_f, clk_2f, clk_4f, reset, inEtapaL2, data0, data1, data2, data3);
  (* src = "demuxEst.v:67" *)
  wire [8:0] _000_;
  (* src = "demuxEst.v:67" *)
  wire [8:0] _001_;
  (* src = "demuxEst.v:67" *)
  wire [8:0] _002_;
  (* src = "demuxEst.v:67" *)
  wire [8:0] _003_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _004_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _005_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _006_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _007_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _008_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _009_;
  (* src = "demuxEst.v:18" *)
  wire [8:0] _010_;
  (* src = "demuxEst.v:18" *)
  wire [8:0] _011_;
  (* src = "demuxEst.v:36" *)
  wire _012_;
  (* src = "demuxEst.v:18" *)
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  (* src = "demuxEst.v:4" *)
  input clk_2f;
  (* src = "demuxEst.v:5" *)
  input clk_4f;
  (* src = "demuxEst.v:3" *)
  input clk_f;
  (* src = "demuxEst.v:8" *)
  output [8:0] data0;
  (* src = "demuxEst.v:9" *)
  output [8:0] data1;
  (* src = "demuxEst.v:10" *)
  output [8:0] data2;
  (* src = "demuxEst.v:11" *)
  output [8:0] data3;
  (* src = "demuxEst.v:15" *)
  wire [8:0] etapa1_inData0;
  (* src = "demuxEst.v:15" *)
  wire [8:0] etapa1_inData1;
  (* src = "demuxEst.v:15" *)
  wire [8:0] etapa1_inData2;
  (* src = "demuxEst.v:15" *)
  wire [8:0] etapa1_inData3;
  (* src = "demuxEst.v:16" *)
  wire [8:0] etapa2_inData0;
  (* src = "demuxEst.v:16" *)
  wire [8:0] etapa2_inData1;
  (* src = "demuxEst.v:7" *)
  input [8:0] inEtapaL2;
  (* src = "demuxEst.v:13" *)
  wire [8:0] outEtapaL1L2_0;
  (* src = "demuxEst.v:13" *)
  wire [8:0] outEtapaL1L2_1;
  (* src = "demuxEst.v:6" *)
  input reset;
  (* src = "demuxEst.v:14" *)
  wire selectorL1;
  (* src = "demuxEst.v:14" *)
  wire selectorL2;
  NOT _233_ (
    .A(etapa1_inData3[1]),
    .Y(_014_)
  );
  NOT _234_ (
    .A(reset),
    .Y(_015_)
  );
  NOR _235_ (
    .A(_015_),
    .B(_014_),
    .Y(_003_[1])
  );
  NOT _236_ (
    .A(etapa1_inData3[2]),
    .Y(_016_)
  );
  NOR _237_ (
    .A(_016_),
    .B(_015_),
    .Y(_003_[2])
  );
  NOT _238_ (
    .A(etapa1_inData3[3]),
    .Y(_017_)
  );
  NOR _239_ (
    .A(_017_),
    .B(_015_),
    .Y(_003_[3])
  );
  NOT _240_ (
    .A(etapa1_inData3[4]),
    .Y(_018_)
  );
  NOR _241_ (
    .A(_018_),
    .B(_015_),
    .Y(_003_[4])
  );
  NOT _242_ (
    .A(etapa1_inData3[5]),
    .Y(_019_)
  );
  NOR _243_ (
    .A(_019_),
    .B(_015_),
    .Y(_003_[5])
  );
  NOT _244_ (
    .A(etapa1_inData3[6]),
    .Y(_020_)
  );
  NOR _245_ (
    .A(_020_),
    .B(_015_),
    .Y(_003_[6])
  );
  NOT _246_ (
    .A(etapa1_inData3[7]),
    .Y(_021_)
  );
  NOR _247_ (
    .A(_021_),
    .B(_015_),
    .Y(_003_[7])
  );
  NOT _248_ (
    .A(etapa1_inData3[8]),
    .Y(_022_)
  );
  NOR _249_ (
    .A(_022_),
    .B(_015_),
    .Y(_003_[8])
  );
  NOT _250_ (
    .A(etapa1_inData2[0]),
    .Y(_023_)
  );
  NOR _251_ (
    .A(_023_),
    .B(_015_),
    .Y(_002_[0])
  );
  NOT _252_ (
    .A(etapa1_inData2[1]),
    .Y(_024_)
  );
  NOR _253_ (
    .A(_024_),
    .B(_015_),
    .Y(_002_[1])
  );
  NOT _254_ (
    .A(etapa1_inData2[2]),
    .Y(_025_)
  );
  NOR _255_ (
    .A(_025_),
    .B(_015_),
    .Y(_002_[2])
  );
  NOT _256_ (
    .A(etapa1_inData2[3]),
    .Y(_026_)
  );
  NOR _257_ (
    .A(_026_),
    .B(_015_),
    .Y(_002_[3])
  );
  NOT _258_ (
    .A(etapa1_inData2[4]),
    .Y(_027_)
  );
  NOR _259_ (
    .A(_027_),
    .B(_015_),
    .Y(_002_[4])
  );
  NOT _260_ (
    .A(etapa1_inData2[5]),
    .Y(_028_)
  );
  NOR _261_ (
    .A(_028_),
    .B(_015_),
    .Y(_002_[5])
  );
  NOT _262_ (
    .A(etapa1_inData2[6]),
    .Y(_029_)
  );
  NOR _263_ (
    .A(_029_),
    .B(_015_),
    .Y(_002_[6])
  );
  NOT _264_ (
    .A(etapa1_inData2[7]),
    .Y(_030_)
  );
  NOR _265_ (
    .A(_030_),
    .B(_015_),
    .Y(_002_[7])
  );
  NOT _266_ (
    .A(etapa1_inData2[8]),
    .Y(_031_)
  );
  NOR _267_ (
    .A(_031_),
    .B(_015_),
    .Y(_002_[8])
  );
  NOT _268_ (
    .A(etapa1_inData1[0]),
    .Y(_032_)
  );
  NOR _269_ (
    .A(_032_),
    .B(_015_),
    .Y(_001_[0])
  );
  NOT _270_ (
    .A(etapa1_inData1[1]),
    .Y(_033_)
  );
  NOR _271_ (
    .A(_033_),
    .B(_015_),
    .Y(_001_[1])
  );
  NOT _272_ (
    .A(etapa1_inData1[2]),
    .Y(_034_)
  );
  NOR _273_ (
    .A(_034_),
    .B(_015_),
    .Y(_001_[2])
  );
  NOT _274_ (
    .A(etapa1_inData1[3]),
    .Y(_035_)
  );
  NOR _275_ (
    .A(_035_),
    .B(_015_),
    .Y(_001_[3])
  );
  NOT _276_ (
    .A(etapa1_inData1[4]),
    .Y(_036_)
  );
  NOR _277_ (
    .A(_036_),
    .B(_015_),
    .Y(_001_[4])
  );
  NOT _278_ (
    .A(etapa1_inData1[5]),
    .Y(_037_)
  );
  NOR _279_ (
    .A(_037_),
    .B(_015_),
    .Y(_001_[5])
  );
  NOT _280_ (
    .A(etapa1_inData1[6]),
    .Y(_038_)
  );
  NOR _281_ (
    .A(_038_),
    .B(_015_),
    .Y(_001_[6])
  );
  NOT _282_ (
    .A(etapa1_inData1[7]),
    .Y(_039_)
  );
  NOR _283_ (
    .A(_039_),
    .B(_015_),
    .Y(_001_[7])
  );
  NOT _284_ (
    .A(etapa1_inData1[8]),
    .Y(_040_)
  );
  NOR _285_ (
    .A(_040_),
    .B(_015_),
    .Y(_001_[8])
  );
  NOT _286_ (
    .A(etapa1_inData0[0]),
    .Y(_041_)
  );
  NOR _287_ (
    .A(_041_),
    .B(_015_),
    .Y(_000_[0])
  );
  NOT _288_ (
    .A(etapa1_inData0[1]),
    .Y(_042_)
  );
  NOR _289_ (
    .A(_042_),
    .B(_015_),
    .Y(_000_[1])
  );
  NOT _290_ (
    .A(etapa1_inData0[2]),
    .Y(_043_)
  );
  NOR _291_ (
    .A(_043_),
    .B(_015_),
    .Y(_000_[2])
  );
  NOT _292_ (
    .A(etapa1_inData0[3]),
    .Y(_044_)
  );
  NOR _293_ (
    .A(_044_),
    .B(_015_),
    .Y(_000_[3])
  );
  NOT _294_ (
    .A(etapa1_inData0[4]),
    .Y(_045_)
  );
  NOR _295_ (
    .A(_045_),
    .B(_015_),
    .Y(_000_[4])
  );
  NOT _296_ (
    .A(etapa1_inData0[5]),
    .Y(_046_)
  );
  NOR _297_ (
    .A(_046_),
    .B(_015_),
    .Y(_000_[5])
  );
  NOT _298_ (
    .A(etapa1_inData0[6]),
    .Y(_047_)
  );
  NOR _299_ (
    .A(_047_),
    .B(_015_),
    .Y(_000_[6])
  );
  NOT _300_ (
    .A(etapa1_inData0[7]),
    .Y(_048_)
  );
  NOR _301_ (
    .A(_048_),
    .B(_015_),
    .Y(_000_[7])
  );
  NOT _302_ (
    .A(etapa1_inData0[8]),
    .Y(_049_)
  );
  NOR _303_ (
    .A(_049_),
    .B(_015_),
    .Y(_000_[8])
  );
  NOT _304_ (
    .A(outEtapaL1L2_1[0]),
    .Y(_050_)
  );
  NOR _305_ (
    .A(_050_),
    .B(_015_),
    .Y(_009_[0])
  );
  NOT _306_ (
    .A(outEtapaL1L2_1[1]),
    .Y(_051_)
  );
  NOR _307_ (
    .A(_051_),
    .B(_015_),
    .Y(_009_[1])
  );
  NOT _308_ (
    .A(outEtapaL1L2_1[2]),
    .Y(_052_)
  );
  NOR _309_ (
    .A(_052_),
    .B(_015_),
    .Y(_009_[2])
  );
  NOT _310_ (
    .A(outEtapaL1L2_1[3]),
    .Y(_053_)
  );
  NOR _311_ (
    .A(_053_),
    .B(_015_),
    .Y(_009_[3])
  );
  NOT _312_ (
    .A(outEtapaL1L2_1[4]),
    .Y(_054_)
  );
  NOR _313_ (
    .A(_054_),
    .B(_015_),
    .Y(_009_[4])
  );
  NOT _314_ (
    .A(outEtapaL1L2_1[5]),
    .Y(_055_)
  );
  NOR _315_ (
    .A(_055_),
    .B(_015_),
    .Y(_009_[5])
  );
  NOT _316_ (
    .A(outEtapaL1L2_1[6]),
    .Y(_056_)
  );
  NOR _317_ (
    .A(_056_),
    .B(_015_),
    .Y(_009_[6])
  );
  NOT _318_ (
    .A(outEtapaL1L2_1[7]),
    .Y(_057_)
  );
  NOR _319_ (
    .A(_057_),
    .B(_015_),
    .Y(_009_[7])
  );
  NOT _320_ (
    .A(outEtapaL1L2_1[8]),
    .Y(_058_)
  );
  NOR _321_ (
    .A(_058_),
    .B(_015_),
    .Y(_009_[8])
  );
  NOT _322_ (
    .A(outEtapaL1L2_0[0]),
    .Y(_059_)
  );
  NOR _323_ (
    .A(_059_),
    .B(_015_),
    .Y(_008_[0])
  );
  NOT _324_ (
    .A(outEtapaL1L2_0[1]),
    .Y(_060_)
  );
  NOR _325_ (
    .A(_060_),
    .B(_015_),
    .Y(_008_[1])
  );
  NOT _326_ (
    .A(outEtapaL1L2_0[2]),
    .Y(_061_)
  );
  NOR _327_ (
    .A(_061_),
    .B(_015_),
    .Y(_008_[2])
  );
  NOT _328_ (
    .A(outEtapaL1L2_0[3]),
    .Y(_062_)
  );
  NOR _329_ (
    .A(_062_),
    .B(_015_),
    .Y(_008_[3])
  );
  NOT _330_ (
    .A(outEtapaL1L2_0[4]),
    .Y(_063_)
  );
  NOR _331_ (
    .A(_063_),
    .B(_015_),
    .Y(_008_[4])
  );
  NOT _332_ (
    .A(outEtapaL1L2_0[5]),
    .Y(_064_)
  );
  NOR _333_ (
    .A(_064_),
    .B(_015_),
    .Y(_008_[5])
  );
  NOT _334_ (
    .A(outEtapaL1L2_0[6]),
    .Y(_065_)
  );
  NOR _335_ (
    .A(_065_),
    .B(_015_),
    .Y(_008_[6])
  );
  NOT _336_ (
    .A(outEtapaL1L2_0[7]),
    .Y(_066_)
  );
  NOR _337_ (
    .A(_066_),
    .B(_015_),
    .Y(_008_[7])
  );
  NOT _338_ (
    .A(outEtapaL1L2_0[8]),
    .Y(_067_)
  );
  NOR _339_ (
    .A(_067_),
    .B(_015_),
    .Y(_008_[8])
  );
  NOT _340_ (
    .A(etapa2_inData1[0]),
    .Y(_068_)
  );
  NOT _341_ (
    .A(selectorL1),
    .Y(_069_)
  );
  NOR _342_ (
    .A(_069_),
    .B(_068_),
    .Y(_070_)
  );
  NOT _343_ (
    .A(etapa1_inData3[0]),
    .Y(_071_)
  );
  NOR _344_ (
    .A(selectorL1),
    .B(_071_),
    .Y(_072_)
  );
  NOR _345_ (
    .A(_072_),
    .B(_070_),
    .Y(_073_)
  );
  NOR _346_ (
    .A(_073_),
    .B(_015_),
    .Y(_007_[0])
  );
  NOT _347_ (
    .A(etapa2_inData1[1]),
    .Y(_074_)
  );
  NOR _348_ (
    .A(_074_),
    .B(_069_),
    .Y(_075_)
  );
  NOR _349_ (
    .A(selectorL1),
    .B(_014_),
    .Y(_076_)
  );
  NOR _350_ (
    .A(_076_),
    .B(_075_),
    .Y(_077_)
  );
  NOR _351_ (
    .A(_077_),
    .B(_015_),
    .Y(_007_[1])
  );
  NOT _352_ (
    .A(etapa2_inData1[2]),
    .Y(_078_)
  );
  NOR _353_ (
    .A(_078_),
    .B(_069_),
    .Y(_079_)
  );
  NOR _354_ (
    .A(selectorL1),
    .B(_016_),
    .Y(_080_)
  );
  NOR _355_ (
    .A(_080_),
    .B(_079_),
    .Y(_081_)
  );
  NOR _356_ (
    .A(_081_),
    .B(_015_),
    .Y(_007_[2])
  );
  NOT _357_ (
    .A(etapa2_inData1[3]),
    .Y(_082_)
  );
  NOR _358_ (
    .A(_082_),
    .B(_069_),
    .Y(_083_)
  );
  NOR _359_ (
    .A(selectorL1),
    .B(_017_),
    .Y(_084_)
  );
  NOR _360_ (
    .A(_084_),
    .B(_083_),
    .Y(_085_)
  );
  NOR _361_ (
    .A(_085_),
    .B(_015_),
    .Y(_007_[3])
  );
  NOT _362_ (
    .A(etapa2_inData1[4]),
    .Y(_086_)
  );
  NOR _363_ (
    .A(_086_),
    .B(_069_),
    .Y(_087_)
  );
  NOR _364_ (
    .A(selectorL1),
    .B(_018_),
    .Y(_088_)
  );
  NOR _365_ (
    .A(_088_),
    .B(_087_),
    .Y(_089_)
  );
  NOR _366_ (
    .A(_089_),
    .B(_015_),
    .Y(_007_[4])
  );
  NOT _367_ (
    .A(etapa2_inData1[5]),
    .Y(_090_)
  );
  NOR _368_ (
    .A(_090_),
    .B(_069_),
    .Y(_091_)
  );
  NOR _369_ (
    .A(selectorL1),
    .B(_019_),
    .Y(_092_)
  );
  NOR _370_ (
    .A(_092_),
    .B(_091_),
    .Y(_093_)
  );
  NOR _371_ (
    .A(_093_),
    .B(_015_),
    .Y(_007_[5])
  );
  NOT _372_ (
    .A(etapa2_inData1[6]),
    .Y(_094_)
  );
  NOR _373_ (
    .A(_094_),
    .B(_069_),
    .Y(_095_)
  );
  NOR _374_ (
    .A(selectorL1),
    .B(_020_),
    .Y(_096_)
  );
  NOR _375_ (
    .A(_096_),
    .B(_095_),
    .Y(_097_)
  );
  NOR _376_ (
    .A(_097_),
    .B(_015_),
    .Y(_007_[6])
  );
  NOT _377_ (
    .A(etapa2_inData1[7]),
    .Y(_098_)
  );
  NOR _378_ (
    .A(_098_),
    .B(_069_),
    .Y(_099_)
  );
  NOR _379_ (
    .A(selectorL1),
    .B(_021_),
    .Y(_100_)
  );
  NOR _380_ (
    .A(_100_),
    .B(_099_),
    .Y(_101_)
  );
  NOR _381_ (
    .A(_101_),
    .B(_015_),
    .Y(_007_[7])
  );
  NOT _382_ (
    .A(etapa2_inData1[8]),
    .Y(_102_)
  );
  NOR _383_ (
    .A(_102_),
    .B(_069_),
    .Y(_103_)
  );
  NOR _384_ (
    .A(selectorL1),
    .B(_022_),
    .Y(_104_)
  );
  NOR _385_ (
    .A(_104_),
    .B(_103_),
    .Y(_105_)
  );
  NOR _386_ (
    .A(_105_),
    .B(_015_),
    .Y(_007_[8])
  );
  NOR _387_ (
    .A(selectorL1),
    .B(etapa2_inData1[0]),
    .Y(_106_)
  );
  NOR _388_ (
    .A(selectorL1),
    .B(_015_),
    .Y(_012_)
  );
  NOR _389_ (
    .A(_012_),
    .B(_002_[0]),
    .Y(_107_)
  );
  NOR _390_ (
    .A(_107_),
    .B(_106_),
    .Y(_006_[0])
  );
  NOR _391_ (
    .A(etapa2_inData1[1]),
    .B(selectorL1),
    .Y(_108_)
  );
  NOR _392_ (
    .A(_012_),
    .B(_002_[1]),
    .Y(_109_)
  );
  NOR _393_ (
    .A(_109_),
    .B(_108_),
    .Y(_006_[1])
  );
  NOR _394_ (
    .A(etapa2_inData1[2]),
    .B(selectorL1),
    .Y(_110_)
  );
  NOR _395_ (
    .A(_012_),
    .B(_002_[2]),
    .Y(_111_)
  );
  NOR _396_ (
    .A(_111_),
    .B(_110_),
    .Y(_006_[2])
  );
  NOR _397_ (
    .A(etapa2_inData1[3]),
    .B(selectorL1),
    .Y(_112_)
  );
  NOR _398_ (
    .A(_012_),
    .B(_002_[3]),
    .Y(_113_)
  );
  NOR _399_ (
    .A(_113_),
    .B(_112_),
    .Y(_006_[3])
  );
  NOR _400_ (
    .A(etapa2_inData1[4]),
    .B(selectorL1),
    .Y(_114_)
  );
  NOR _401_ (
    .A(_012_),
    .B(_002_[4]),
    .Y(_115_)
  );
  NOR _402_ (
    .A(_115_),
    .B(_114_),
    .Y(_006_[4])
  );
  NOR _403_ (
    .A(etapa2_inData1[5]),
    .B(selectorL1),
    .Y(_116_)
  );
  NOR _404_ (
    .A(_012_),
    .B(_002_[5]),
    .Y(_117_)
  );
  NOR _405_ (
    .A(_117_),
    .B(_116_),
    .Y(_006_[5])
  );
  NOR _406_ (
    .A(etapa2_inData1[6]),
    .B(selectorL1),
    .Y(_118_)
  );
  NOR _407_ (
    .A(_012_),
    .B(_002_[6]),
    .Y(_119_)
  );
  NOR _408_ (
    .A(_119_),
    .B(_118_),
    .Y(_006_[6])
  );
  NOR _409_ (
    .A(etapa2_inData1[7]),
    .B(selectorL1),
    .Y(_120_)
  );
  NOR _410_ (
    .A(_012_),
    .B(_002_[7]),
    .Y(_121_)
  );
  NOR _411_ (
    .A(_121_),
    .B(_120_),
    .Y(_006_[7])
  );
  NOR _412_ (
    .A(etapa2_inData1[8]),
    .B(selectorL1),
    .Y(_122_)
  );
  NOR _413_ (
    .A(_012_),
    .B(_002_[8]),
    .Y(_123_)
  );
  NOR _414_ (
    .A(_123_),
    .B(_122_),
    .Y(_006_[8])
  );
  NOT _415_ (
    .A(etapa2_inData0[0]),
    .Y(_124_)
  );
  NOR _416_ (
    .A(_124_),
    .B(_069_),
    .Y(_125_)
  );
  NOR _417_ (
    .A(selectorL1),
    .B(_032_),
    .Y(_126_)
  );
  NOR _418_ (
    .A(_126_),
    .B(_125_),
    .Y(_127_)
  );
  NOR _419_ (
    .A(_127_),
    .B(_015_),
    .Y(_005_[0])
  );
  NOT _420_ (
    .A(etapa2_inData0[1]),
    .Y(_128_)
  );
  NOR _421_ (
    .A(_128_),
    .B(_069_),
    .Y(_129_)
  );
  NOR _422_ (
    .A(selectorL1),
    .B(_033_),
    .Y(_130_)
  );
  NOR _423_ (
    .A(_130_),
    .B(_129_),
    .Y(_131_)
  );
  NOR _424_ (
    .A(_131_),
    .B(_015_),
    .Y(_005_[1])
  );
  NOT _425_ (
    .A(etapa2_inData0[2]),
    .Y(_132_)
  );
  NOR _426_ (
    .A(_132_),
    .B(_069_),
    .Y(_133_)
  );
  NOR _427_ (
    .A(selectorL1),
    .B(_034_),
    .Y(_134_)
  );
  NOR _428_ (
    .A(_134_),
    .B(_133_),
    .Y(_135_)
  );
  NOR _429_ (
    .A(_135_),
    .B(_015_),
    .Y(_005_[2])
  );
  NOT _430_ (
    .A(etapa2_inData0[3]),
    .Y(_136_)
  );
  NOR _431_ (
    .A(_136_),
    .B(_069_),
    .Y(_137_)
  );
  NOR _432_ (
    .A(selectorL1),
    .B(_035_),
    .Y(_138_)
  );
  NOR _433_ (
    .A(_138_),
    .B(_137_),
    .Y(_139_)
  );
  NOR _434_ (
    .A(_139_),
    .B(_015_),
    .Y(_005_[3])
  );
  NOT _435_ (
    .A(etapa2_inData0[4]),
    .Y(_140_)
  );
  NOR _436_ (
    .A(_140_),
    .B(_069_),
    .Y(_141_)
  );
  NOR _437_ (
    .A(selectorL1),
    .B(_036_),
    .Y(_142_)
  );
  NOR _438_ (
    .A(_142_),
    .B(_141_),
    .Y(_143_)
  );
  NOR _439_ (
    .A(_143_),
    .B(_015_),
    .Y(_005_[4])
  );
  NOT _440_ (
    .A(etapa2_inData0[5]),
    .Y(_144_)
  );
  NOR _441_ (
    .A(_144_),
    .B(_069_),
    .Y(_145_)
  );
  NOR _442_ (
    .A(selectorL1),
    .B(_037_),
    .Y(_146_)
  );
  NOR _443_ (
    .A(_146_),
    .B(_145_),
    .Y(_147_)
  );
  NOR _444_ (
    .A(_147_),
    .B(_015_),
    .Y(_005_[5])
  );
  NOT _445_ (
    .A(etapa2_inData0[6]),
    .Y(_148_)
  );
  NOR _446_ (
    .A(_148_),
    .B(_069_),
    .Y(_149_)
  );
  NOR _447_ (
    .A(selectorL1),
    .B(_038_),
    .Y(_150_)
  );
  NOR _448_ (
    .A(_150_),
    .B(_149_),
    .Y(_151_)
  );
  NOR _449_ (
    .A(_151_),
    .B(_015_),
    .Y(_005_[6])
  );
  NOT _450_ (
    .A(etapa2_inData0[7]),
    .Y(_152_)
  );
  NOR _451_ (
    .A(_152_),
    .B(_069_),
    .Y(_153_)
  );
  NOR _452_ (
    .A(selectorL1),
    .B(_039_),
    .Y(_154_)
  );
  NOR _453_ (
    .A(_154_),
    .B(_153_),
    .Y(_155_)
  );
  NOR _454_ (
    .A(_155_),
    .B(_015_),
    .Y(_005_[7])
  );
  NOT _455_ (
    .A(etapa2_inData0[8]),
    .Y(_156_)
  );
  NOR _456_ (
    .A(_156_),
    .B(_069_),
    .Y(_157_)
  );
  NOR _457_ (
    .A(selectorL1),
    .B(_040_),
    .Y(_158_)
  );
  NOR _458_ (
    .A(_158_),
    .B(_157_),
    .Y(_159_)
  );
  NOR _459_ (
    .A(_159_),
    .B(_015_),
    .Y(_005_[8])
  );
  NOR _460_ (
    .A(etapa2_inData0[0]),
    .B(selectorL1),
    .Y(_160_)
  );
  NOR _461_ (
    .A(_012_),
    .B(_000_[0]),
    .Y(_161_)
  );
  NOR _462_ (
    .A(_161_),
    .B(_160_),
    .Y(_004_[0])
  );
  NOR _463_ (
    .A(etapa2_inData0[1]),
    .B(selectorL1),
    .Y(_162_)
  );
  NOR _464_ (
    .A(_012_),
    .B(_000_[1]),
    .Y(_163_)
  );
  NOR _465_ (
    .A(_163_),
    .B(_162_),
    .Y(_004_[1])
  );
  NOR _466_ (
    .A(etapa2_inData0[2]),
    .B(selectorL1),
    .Y(_164_)
  );
  NOR _467_ (
    .A(_012_),
    .B(_000_[2]),
    .Y(_165_)
  );
  NOR _468_ (
    .A(_165_),
    .B(_164_),
    .Y(_004_[2])
  );
  NOR _469_ (
    .A(etapa2_inData0[3]),
    .B(selectorL1),
    .Y(_166_)
  );
  NOR _470_ (
    .A(_012_),
    .B(_000_[3]),
    .Y(_167_)
  );
  NOR _471_ (
    .A(_167_),
    .B(_166_),
    .Y(_004_[3])
  );
  NOR _472_ (
    .A(etapa2_inData0[4]),
    .B(selectorL1),
    .Y(_168_)
  );
  NOR _473_ (
    .A(_012_),
    .B(_000_[4]),
    .Y(_169_)
  );
  NOR _474_ (
    .A(_169_),
    .B(_168_),
    .Y(_004_[4])
  );
  NOR _475_ (
    .A(etapa2_inData0[5]),
    .B(selectorL1),
    .Y(_170_)
  );
  NOR _476_ (
    .A(_012_),
    .B(_000_[5]),
    .Y(_171_)
  );
  NOR _477_ (
    .A(_171_),
    .B(_170_),
    .Y(_004_[5])
  );
  NOR _478_ (
    .A(etapa2_inData0[6]),
    .B(selectorL1),
    .Y(_172_)
  );
  NOR _479_ (
    .A(_012_),
    .B(_000_[6]),
    .Y(_173_)
  );
  NOR _480_ (
    .A(_173_),
    .B(_172_),
    .Y(_004_[6])
  );
  NOR _481_ (
    .A(etapa2_inData0[7]),
    .B(selectorL1),
    .Y(_174_)
  );
  NOR _482_ (
    .A(_012_),
    .B(_000_[7]),
    .Y(_175_)
  );
  NOR _483_ (
    .A(_175_),
    .B(_174_),
    .Y(_004_[7])
  );
  NOR _484_ (
    .A(etapa2_inData0[8]),
    .B(selectorL1),
    .Y(_176_)
  );
  NOR _485_ (
    .A(_012_),
    .B(_000_[8]),
    .Y(_177_)
  );
  NOR _486_ (
    .A(_177_),
    .B(_176_),
    .Y(_004_[8])
  );
  NOR _487_ (
    .A(selectorL2),
    .B(_015_),
    .Y(_013_)
  );
  NOT _488_ (
    .A(inEtapaL2[0]),
    .Y(_178_)
  );
  NOT _489_ (
    .A(selectorL2),
    .Y(_179_)
  );
  NOR _490_ (
    .A(_179_),
    .B(_178_),
    .Y(_180_)
  );
  NOR _491_ (
    .A(selectorL2),
    .B(_050_),
    .Y(_181_)
  );
  NOR _492_ (
    .A(_181_),
    .B(_180_),
    .Y(_182_)
  );
  NOR _493_ (
    .A(_182_),
    .B(_015_),
    .Y(_011_[0])
  );
  NOT _494_ (
    .A(inEtapaL2[1]),
    .Y(_183_)
  );
  NOR _495_ (
    .A(_183_),
    .B(_179_),
    .Y(_184_)
  );
  NOR _496_ (
    .A(selectorL2),
    .B(_051_),
    .Y(_185_)
  );
  NOR _497_ (
    .A(_185_),
    .B(_184_),
    .Y(_186_)
  );
  NOR _498_ (
    .A(_186_),
    .B(_015_),
    .Y(_011_[1])
  );
  NOT _499_ (
    .A(inEtapaL2[2]),
    .Y(_187_)
  );
  NOR _500_ (
    .A(_187_),
    .B(_179_),
    .Y(_188_)
  );
  NOR _501_ (
    .A(selectorL2),
    .B(_052_),
    .Y(_189_)
  );
  NOR _502_ (
    .A(_189_),
    .B(_188_),
    .Y(_190_)
  );
  NOR _503_ (
    .A(_190_),
    .B(_015_),
    .Y(_011_[2])
  );
  NOT _504_ (
    .A(inEtapaL2[3]),
    .Y(_191_)
  );
  NOR _505_ (
    .A(_191_),
    .B(_179_),
    .Y(_192_)
  );
  NOR _506_ (
    .A(selectorL2),
    .B(_053_),
    .Y(_193_)
  );
  NOR _507_ (
    .A(_193_),
    .B(_192_),
    .Y(_194_)
  );
  NOR _508_ (
    .A(_194_),
    .B(_015_),
    .Y(_011_[3])
  );
  NOT _509_ (
    .A(inEtapaL2[4]),
    .Y(_195_)
  );
  NOR _510_ (
    .A(_195_),
    .B(_179_),
    .Y(_196_)
  );
  NOR _511_ (
    .A(selectorL2),
    .B(_054_),
    .Y(_197_)
  );
  NOR _512_ (
    .A(_197_),
    .B(_196_),
    .Y(_198_)
  );
  NOR _513_ (
    .A(_198_),
    .B(_015_),
    .Y(_011_[4])
  );
  NOT _514_ (
    .A(inEtapaL2[5]),
    .Y(_199_)
  );
  NOR _515_ (
    .A(_199_),
    .B(_179_),
    .Y(_200_)
  );
  NOR _516_ (
    .A(selectorL2),
    .B(_055_),
    .Y(_201_)
  );
  NOR _517_ (
    .A(_201_),
    .B(_200_),
    .Y(_202_)
  );
  NOR _518_ (
    .A(_202_),
    .B(_015_),
    .Y(_011_[5])
  );
  NOT _519_ (
    .A(inEtapaL2[6]),
    .Y(_203_)
  );
  NOR _520_ (
    .A(_203_),
    .B(_179_),
    .Y(_204_)
  );
  NOR _521_ (
    .A(selectorL2),
    .B(_056_),
    .Y(_205_)
  );
  NOR _522_ (
    .A(_205_),
    .B(_204_),
    .Y(_206_)
  );
  NOR _523_ (
    .A(_206_),
    .B(_015_),
    .Y(_011_[6])
  );
  NOT _524_ (
    .A(inEtapaL2[7]),
    .Y(_207_)
  );
  NOR _525_ (
    .A(_207_),
    .B(_179_),
    .Y(_208_)
  );
  NOR _526_ (
    .A(selectorL2),
    .B(_057_),
    .Y(_209_)
  );
  NOR _527_ (
    .A(_209_),
    .B(_208_),
    .Y(_210_)
  );
  NOR _528_ (
    .A(_210_),
    .B(_015_),
    .Y(_011_[7])
  );
  NOT _529_ (
    .A(inEtapaL2[8]),
    .Y(_211_)
  );
  NOR _530_ (
    .A(_211_),
    .B(_179_),
    .Y(_212_)
  );
  NOR _531_ (
    .A(selectorL2),
    .B(_058_),
    .Y(_213_)
  );
  NOR _532_ (
    .A(_213_),
    .B(_212_),
    .Y(_214_)
  );
  NOR _533_ (
    .A(_214_),
    .B(_015_),
    .Y(_011_[8])
  );
  NOR _534_ (
    .A(selectorL2),
    .B(inEtapaL2[0]),
    .Y(_215_)
  );
  NOR _535_ (
    .A(_013_),
    .B(_008_[0]),
    .Y(_216_)
  );
  NOR _536_ (
    .A(_216_),
    .B(_215_),
    .Y(_010_[0])
  );
  NOR _537_ (
    .A(inEtapaL2[1]),
    .B(selectorL2),
    .Y(_217_)
  );
  NOR _538_ (
    .A(_013_),
    .B(_008_[1]),
    .Y(_218_)
  );
  NOR _539_ (
    .A(_218_),
    .B(_217_),
    .Y(_010_[1])
  );
  NOR _540_ (
    .A(inEtapaL2[2]),
    .B(selectorL2),
    .Y(_219_)
  );
  NOR _541_ (
    .A(_013_),
    .B(_008_[2]),
    .Y(_220_)
  );
  NOR _542_ (
    .A(_220_),
    .B(_219_),
    .Y(_010_[2])
  );
  NOR _543_ (
    .A(inEtapaL2[3]),
    .B(selectorL2),
    .Y(_221_)
  );
  NOR _544_ (
    .A(_013_),
    .B(_008_[3]),
    .Y(_222_)
  );
  NOR _545_ (
    .A(_222_),
    .B(_221_),
    .Y(_010_[3])
  );
  NOR _546_ (
    .A(inEtapaL2[4]),
    .B(selectorL2),
    .Y(_223_)
  );
  NOR _547_ (
    .A(_013_),
    .B(_008_[4]),
    .Y(_224_)
  );
  NOR _548_ (
    .A(_224_),
    .B(_223_),
    .Y(_010_[4])
  );
  NOR _549_ (
    .A(inEtapaL2[5]),
    .B(selectorL2),
    .Y(_225_)
  );
  NOR _550_ (
    .A(_013_),
    .B(_008_[5]),
    .Y(_226_)
  );
  NOR _551_ (
    .A(_226_),
    .B(_225_),
    .Y(_010_[5])
  );
  NOR _552_ (
    .A(inEtapaL2[6]),
    .B(selectorL2),
    .Y(_227_)
  );
  NOR _553_ (
    .A(_013_),
    .B(_008_[6]),
    .Y(_228_)
  );
  NOR _554_ (
    .A(_228_),
    .B(_227_),
    .Y(_010_[6])
  );
  NOR _555_ (
    .A(inEtapaL2[7]),
    .B(selectorL2),
    .Y(_229_)
  );
  NOR _556_ (
    .A(_013_),
    .B(_008_[7]),
    .Y(_230_)
  );
  NOR _557_ (
    .A(_230_),
    .B(_229_),
    .Y(_010_[7])
  );
  NOR _558_ (
    .A(inEtapaL2[8]),
    .B(selectorL2),
    .Y(_231_)
  );
  NOR _559_ (
    .A(_013_),
    .B(_008_[8]),
    .Y(_232_)
  );
  NOR _560_ (
    .A(_232_),
    .B(_231_),
    .Y(_010_[8])
  );
  NOR _561_ (
    .A(_071_),
    .B(_015_),
    .Y(_003_[0])
  );
  DFF _562_ (
    .C(clk_f),
    .D(_000_[0]),
    .Q(data0[0])
  );
  DFF _563_ (
    .C(clk_f),
    .D(_000_[1]),
    .Q(data0[1])
  );
  DFF _564_ (
    .C(clk_f),
    .D(_000_[2]),
    .Q(data0[2])
  );
  DFF _565_ (
    .C(clk_f),
    .D(_000_[3]),
    .Q(data0[3])
  );
  DFF _566_ (
    .C(clk_f),
    .D(_000_[4]),
    .Q(data0[4])
  );
  DFF _567_ (
    .C(clk_f),
    .D(_000_[5]),
    .Q(data0[5])
  );
  DFF _568_ (
    .C(clk_f),
    .D(_000_[6]),
    .Q(data0[6])
  );
  DFF _569_ (
    .C(clk_f),
    .D(_000_[7]),
    .Q(data0[7])
  );
  DFF _570_ (
    .C(clk_f),
    .D(_000_[8]),
    .Q(data0[8])
  );
  DFF _571_ (
    .C(clk_f),
    .D(_001_[0]),
    .Q(data1[0])
  );
  DFF _572_ (
    .C(clk_f),
    .D(_001_[1]),
    .Q(data1[1])
  );
  DFF _573_ (
    .C(clk_f),
    .D(_001_[2]),
    .Q(data1[2])
  );
  DFF _574_ (
    .C(clk_f),
    .D(_001_[3]),
    .Q(data1[3])
  );
  DFF _575_ (
    .C(clk_f),
    .D(_001_[4]),
    .Q(data1[4])
  );
  DFF _576_ (
    .C(clk_f),
    .D(_001_[5]),
    .Q(data1[5])
  );
  DFF _577_ (
    .C(clk_f),
    .D(_001_[6]),
    .Q(data1[6])
  );
  DFF _578_ (
    .C(clk_f),
    .D(_001_[7]),
    .Q(data1[7])
  );
  DFF _579_ (
    .C(clk_f),
    .D(_001_[8]),
    .Q(data1[8])
  );
  DFF _580_ (
    .C(clk_f),
    .D(_002_[0]),
    .Q(data2[0])
  );
  DFF _581_ (
    .C(clk_f),
    .D(_002_[1]),
    .Q(data2[1])
  );
  DFF _582_ (
    .C(clk_f),
    .D(_002_[2]),
    .Q(data2[2])
  );
  DFF _583_ (
    .C(clk_f),
    .D(_002_[3]),
    .Q(data2[3])
  );
  DFF _584_ (
    .C(clk_f),
    .D(_002_[4]),
    .Q(data2[4])
  );
  DFF _585_ (
    .C(clk_f),
    .D(_002_[5]),
    .Q(data2[5])
  );
  DFF _586_ (
    .C(clk_f),
    .D(_002_[6]),
    .Q(data2[6])
  );
  DFF _587_ (
    .C(clk_f),
    .D(_002_[7]),
    .Q(data2[7])
  );
  DFF _588_ (
    .C(clk_f),
    .D(_002_[8]),
    .Q(data2[8])
  );
  DFF _589_ (
    .C(clk_f),
    .D(_003_[0]),
    .Q(data3[0])
  );
  DFF _590_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(data3[1])
  );
  DFF _591_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(data3[2])
  );
  DFF _592_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(data3[3])
  );
  DFF _593_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(data3[4])
  );
  DFF _594_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(data3[5])
  );
  DFF _595_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(data3[6])
  );
  DFF _596_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(data3[7])
  );
  DFF _597_ (
    .C(clk_f),
    .D(_003_[8]),
    .Q(data3[8])
  );
  DFF _598_ (
    .C(clk_2f),
    .D(_012_),
    .Q(selectorL1)
  );
  DFF _599_ (
    .C(clk_2f),
    .D(_004_[0]),
    .Q(etapa1_inData0[0])
  );
  DFF _600_ (
    .C(clk_2f),
    .D(_004_[1]),
    .Q(etapa1_inData0[1])
  );
  DFF _601_ (
    .C(clk_2f),
    .D(_004_[2]),
    .Q(etapa1_inData0[2])
  );
  DFF _602_ (
    .C(clk_2f),
    .D(_004_[3]),
    .Q(etapa1_inData0[3])
  );
  DFF _603_ (
    .C(clk_2f),
    .D(_004_[4]),
    .Q(etapa1_inData0[4])
  );
  DFF _604_ (
    .C(clk_2f),
    .D(_004_[5]),
    .Q(etapa1_inData0[5])
  );
  DFF _605_ (
    .C(clk_2f),
    .D(_004_[6]),
    .Q(etapa1_inData0[6])
  );
  DFF _606_ (
    .C(clk_2f),
    .D(_004_[7]),
    .Q(etapa1_inData0[7])
  );
  DFF _607_ (
    .C(clk_2f),
    .D(_004_[8]),
    .Q(etapa1_inData0[8])
  );
  DFF _608_ (
    .C(clk_2f),
    .D(_005_[0]),
    .Q(etapa1_inData1[0])
  );
  DFF _609_ (
    .C(clk_2f),
    .D(_005_[1]),
    .Q(etapa1_inData1[1])
  );
  DFF _610_ (
    .C(clk_2f),
    .D(_005_[2]),
    .Q(etapa1_inData1[2])
  );
  DFF _611_ (
    .C(clk_2f),
    .D(_005_[3]),
    .Q(etapa1_inData1[3])
  );
  DFF _612_ (
    .C(clk_2f),
    .D(_005_[4]),
    .Q(etapa1_inData1[4])
  );
  DFF _613_ (
    .C(clk_2f),
    .D(_005_[5]),
    .Q(etapa1_inData1[5])
  );
  DFF _614_ (
    .C(clk_2f),
    .D(_005_[6]),
    .Q(etapa1_inData1[6])
  );
  DFF _615_ (
    .C(clk_2f),
    .D(_005_[7]),
    .Q(etapa1_inData1[7])
  );
  DFF _616_ (
    .C(clk_2f),
    .D(_005_[8]),
    .Q(etapa1_inData1[8])
  );
  DFF _617_ (
    .C(clk_2f),
    .D(_006_[0]),
    .Q(etapa1_inData2[0])
  );
  DFF _618_ (
    .C(clk_2f),
    .D(_006_[1]),
    .Q(etapa1_inData2[1])
  );
  DFF _619_ (
    .C(clk_2f),
    .D(_006_[2]),
    .Q(etapa1_inData2[2])
  );
  DFF _620_ (
    .C(clk_2f),
    .D(_006_[3]),
    .Q(etapa1_inData2[3])
  );
  DFF _621_ (
    .C(clk_2f),
    .D(_006_[4]),
    .Q(etapa1_inData2[4])
  );
  DFF _622_ (
    .C(clk_2f),
    .D(_006_[5]),
    .Q(etapa1_inData2[5])
  );
  DFF _623_ (
    .C(clk_2f),
    .D(_006_[6]),
    .Q(etapa1_inData2[6])
  );
  DFF _624_ (
    .C(clk_2f),
    .D(_006_[7]),
    .Q(etapa1_inData2[7])
  );
  DFF _625_ (
    .C(clk_2f),
    .D(_006_[8]),
    .Q(etapa1_inData2[8])
  );
  DFF _626_ (
    .C(clk_2f),
    .D(_007_[0]),
    .Q(etapa1_inData3[0])
  );
  DFF _627_ (
    .C(clk_2f),
    .D(_007_[1]),
    .Q(etapa1_inData3[1])
  );
  DFF _628_ (
    .C(clk_2f),
    .D(_007_[2]),
    .Q(etapa1_inData3[2])
  );
  DFF _629_ (
    .C(clk_2f),
    .D(_007_[3]),
    .Q(etapa1_inData3[3])
  );
  DFF _630_ (
    .C(clk_2f),
    .D(_007_[4]),
    .Q(etapa1_inData3[4])
  );
  DFF _631_ (
    .C(clk_2f),
    .D(_007_[5]),
    .Q(etapa1_inData3[5])
  );
  DFF _632_ (
    .C(clk_2f),
    .D(_007_[6]),
    .Q(etapa1_inData3[6])
  );
  DFF _633_ (
    .C(clk_2f),
    .D(_007_[7]),
    .Q(etapa1_inData3[7])
  );
  DFF _634_ (
    .C(clk_2f),
    .D(_007_[8]),
    .Q(etapa1_inData3[8])
  );
  DFF _635_ (
    .C(clk_2f),
    .D(_008_[0]),
    .Q(etapa2_inData0[0])
  );
  DFF _636_ (
    .C(clk_2f),
    .D(_008_[1]),
    .Q(etapa2_inData0[1])
  );
  DFF _637_ (
    .C(clk_2f),
    .D(_008_[2]),
    .Q(etapa2_inData0[2])
  );
  DFF _638_ (
    .C(clk_2f),
    .D(_008_[3]),
    .Q(etapa2_inData0[3])
  );
  DFF _639_ (
    .C(clk_2f),
    .D(_008_[4]),
    .Q(etapa2_inData0[4])
  );
  DFF _640_ (
    .C(clk_2f),
    .D(_008_[5]),
    .Q(etapa2_inData0[5])
  );
  DFF _641_ (
    .C(clk_2f),
    .D(_008_[6]),
    .Q(etapa2_inData0[6])
  );
  DFF _642_ (
    .C(clk_2f),
    .D(_008_[7]),
    .Q(etapa2_inData0[7])
  );
  DFF _643_ (
    .C(clk_2f),
    .D(_008_[8]),
    .Q(etapa2_inData0[8])
  );
  DFF _644_ (
    .C(clk_2f),
    .D(_009_[0]),
    .Q(etapa2_inData1[0])
  );
  DFF _645_ (
    .C(clk_2f),
    .D(_009_[1]),
    .Q(etapa2_inData1[1])
  );
  DFF _646_ (
    .C(clk_2f),
    .D(_009_[2]),
    .Q(etapa2_inData1[2])
  );
  DFF _647_ (
    .C(clk_2f),
    .D(_009_[3]),
    .Q(etapa2_inData1[3])
  );
  DFF _648_ (
    .C(clk_2f),
    .D(_009_[4]),
    .Q(etapa2_inData1[4])
  );
  DFF _649_ (
    .C(clk_2f),
    .D(_009_[5]),
    .Q(etapa2_inData1[5])
  );
  DFF _650_ (
    .C(clk_2f),
    .D(_009_[6]),
    .Q(etapa2_inData1[6])
  );
  DFF _651_ (
    .C(clk_2f),
    .D(_009_[7]),
    .Q(etapa2_inData1[7])
  );
  DFF _652_ (
    .C(clk_2f),
    .D(_009_[8]),
    .Q(etapa2_inData1[8])
  );
  DFF _653_ (
    .C(clk_4f),
    .D(_010_[0]),
    .Q(outEtapaL1L2_0[0])
  );
  DFF _654_ (
    .C(clk_4f),
    .D(_010_[1]),
    .Q(outEtapaL1L2_0[1])
  );
  DFF _655_ (
    .C(clk_4f),
    .D(_010_[2]),
    .Q(outEtapaL1L2_0[2])
  );
  DFF _656_ (
    .C(clk_4f),
    .D(_010_[3]),
    .Q(outEtapaL1L2_0[3])
  );
  DFF _657_ (
    .C(clk_4f),
    .D(_010_[4]),
    .Q(outEtapaL1L2_0[4])
  );
  DFF _658_ (
    .C(clk_4f),
    .D(_010_[5]),
    .Q(outEtapaL1L2_0[5])
  );
  DFF _659_ (
    .C(clk_4f),
    .D(_010_[6]),
    .Q(outEtapaL1L2_0[6])
  );
  DFF _660_ (
    .C(clk_4f),
    .D(_010_[7]),
    .Q(outEtapaL1L2_0[7])
  );
  DFF _661_ (
    .C(clk_4f),
    .D(_010_[8]),
    .Q(outEtapaL1L2_0[8])
  );
  DFF _662_ (
    .C(clk_4f),
    .D(_011_[0]),
    .Q(outEtapaL1L2_1[0])
  );
  DFF _663_ (
    .C(clk_4f),
    .D(_011_[1]),
    .Q(outEtapaL1L2_1[1])
  );
  DFF _664_ (
    .C(clk_4f),
    .D(_011_[2]),
    .Q(outEtapaL1L2_1[2])
  );
  DFF _665_ (
    .C(clk_4f),
    .D(_011_[3]),
    .Q(outEtapaL1L2_1[3])
  );
  DFF _666_ (
    .C(clk_4f),
    .D(_011_[4]),
    .Q(outEtapaL1L2_1[4])
  );
  DFF _667_ (
    .C(clk_4f),
    .D(_011_[5]),
    .Q(outEtapaL1L2_1[5])
  );
  DFF _668_ (
    .C(clk_4f),
    .D(_011_[6]),
    .Q(outEtapaL1L2_1[6])
  );
  DFF _669_ (
    .C(clk_4f),
    .D(_011_[7]),
    .Q(outEtapaL1L2_1[7])
  );
  DFF _670_ (
    .C(clk_4f),
    .D(_011_[8]),
    .Q(outEtapaL1L2_1[8])
  );
  DFF _671_ (
    .C(clk_4f),
    .D(_013_),
    .Q(selectorL2)
  );
endmodule

(* src = "muxesEst.v:1" *)
module muxesEst(clk_f, clk_2f, clk_4f, reset, data0, data1, data2, data3, outEtapaL2);
  (* src = "muxesEst.v:18" *)
  wire [8:0] _000_;
  (* src = "muxesEst.v:18" *)
  wire [8:0] _001_;
  (* src = "muxesEst.v:18" *)
  wire [8:0] _002_;
  (* src = "muxesEst.v:18" *)
  wire [8:0] _003_;
  (* src = "muxesEst.v:35" *)
  wire [8:0] _004_;
  (* src = "muxesEst.v:35" *)
  wire [8:0] _005_;
  (* src = "muxesEst.v:49" *)
  wire [8:0] _006_;
  (* src = "muxesEst.v:35" *)
  wire _007_;
  (* src = "muxesEst.v:49" *)
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  (* src = "muxesEst.v:3" *)
  input clk_2f;
  (* src = "muxesEst.v:4" *)
  input clk_4f;
  (* src = "muxesEst.v:2" *)
  input clk_f;
  (* src = "muxesEst.v:6" *)
  input [8:0] data0;
  (* src = "muxesEst.v:7" *)
  input [8:0] data1;
  (* src = "muxesEst.v:8" *)
  input [8:0] data2;
  (* src = "muxesEst.v:9" *)
  input [8:0] data3;
  (* src = "muxesEst.v:15" *)
  wire [8:0] etapa1_preData0;
  (* src = "muxesEst.v:15" *)
  wire [8:0] etapa1_preData1;
  (* src = "muxesEst.v:15" *)
  wire [8:0] etapa1_preData2;
  (* src = "muxesEst.v:15" *)
  wire [8:0] etapa1_preData3;
  (* src = "muxesEst.v:16" *)
  wire [8:0] etapa2_preData0;
  (* src = "muxesEst.v:16" *)
  wire [8:0] etapa2_preData1;
  (* src = "muxesEst.v:10" *)
  output [8:0] outEtapaL2;
  (* src = "muxesEst.v:5" *)
  input reset;
  (* src = "muxesEst.v:14" *)
  wire selectorL1;
  (* src = "muxesEst.v:14" *)
  wire selectorL2;
  NOR _267_ (
    .A(selectorL2),
    .B(etapa2_preData0[0]),
    .Y(_009_)
  );
  NOT _268_ (
    .A(etapa2_preData1[0]),
    .Y(_010_)
  );
  NAND _269_ (
    .A(selectorL2),
    .B(_010_),
    .Y(_011_)
  );
  NAND _270_ (
    .A(_011_),
    .B(reset),
    .Y(_012_)
  );
  NOR _271_ (
    .A(_012_),
    .B(_009_),
    .Y(_006_[0])
  );
  NOR _272_ (
    .A(etapa2_preData0[1]),
    .B(selectorL2),
    .Y(_013_)
  );
  NOT _273_ (
    .A(etapa2_preData1[1]),
    .Y(_014_)
  );
  NAND _274_ (
    .A(_014_),
    .B(selectorL2),
    .Y(_015_)
  );
  NAND _275_ (
    .A(_015_),
    .B(reset),
    .Y(_016_)
  );
  NOR _276_ (
    .A(_016_),
    .B(_013_),
    .Y(_006_[1])
  );
  NOR _277_ (
    .A(etapa2_preData0[2]),
    .B(selectorL2),
    .Y(_017_)
  );
  NOT _278_ (
    .A(etapa2_preData1[2]),
    .Y(_018_)
  );
  NAND _279_ (
    .A(_018_),
    .B(selectorL2),
    .Y(_019_)
  );
  NAND _280_ (
    .A(_019_),
    .B(reset),
    .Y(_020_)
  );
  NOR _281_ (
    .A(_020_),
    .B(_017_),
    .Y(_006_[2])
  );
  NOR _282_ (
    .A(etapa2_preData0[3]),
    .B(selectorL2),
    .Y(_021_)
  );
  NOT _283_ (
    .A(etapa2_preData1[3]),
    .Y(_022_)
  );
  NAND _284_ (
    .A(_022_),
    .B(selectorL2),
    .Y(_023_)
  );
  NAND _285_ (
    .A(_023_),
    .B(reset),
    .Y(_024_)
  );
  NOR _286_ (
    .A(_024_),
    .B(_021_),
    .Y(_006_[3])
  );
  NOR _287_ (
    .A(etapa2_preData0[4]),
    .B(selectorL2),
    .Y(_025_)
  );
  NOT _288_ (
    .A(etapa2_preData1[4]),
    .Y(_026_)
  );
  NAND _289_ (
    .A(_026_),
    .B(selectorL2),
    .Y(_027_)
  );
  NAND _290_ (
    .A(_027_),
    .B(reset),
    .Y(_028_)
  );
  NOR _291_ (
    .A(_028_),
    .B(_025_),
    .Y(_006_[4])
  );
  NOR _292_ (
    .A(etapa2_preData0[5]),
    .B(selectorL2),
    .Y(_029_)
  );
  NOT _293_ (
    .A(etapa2_preData1[5]),
    .Y(_030_)
  );
  NAND _294_ (
    .A(_030_),
    .B(selectorL2),
    .Y(_031_)
  );
  NAND _295_ (
    .A(_031_),
    .B(reset),
    .Y(_032_)
  );
  NOR _296_ (
    .A(_032_),
    .B(_029_),
    .Y(_006_[5])
  );
  NOR _297_ (
    .A(etapa2_preData0[6]),
    .B(selectorL2),
    .Y(_033_)
  );
  NOT _298_ (
    .A(etapa2_preData1[6]),
    .Y(_034_)
  );
  NAND _299_ (
    .A(_034_),
    .B(selectorL2),
    .Y(_035_)
  );
  NAND _300_ (
    .A(_035_),
    .B(reset),
    .Y(_036_)
  );
  NOR _301_ (
    .A(_036_),
    .B(_033_),
    .Y(_006_[6])
  );
  NOR _302_ (
    .A(etapa2_preData0[7]),
    .B(selectorL2),
    .Y(_037_)
  );
  NOT _303_ (
    .A(etapa2_preData1[7]),
    .Y(_038_)
  );
  NAND _304_ (
    .A(_038_),
    .B(selectorL2),
    .Y(_039_)
  );
  NAND _305_ (
    .A(_039_),
    .B(reset),
    .Y(_040_)
  );
  NOR _306_ (
    .A(_040_),
    .B(_037_),
    .Y(_006_[7])
  );
  NOR _307_ (
    .A(etapa2_preData0[8]),
    .B(selectorL2),
    .Y(_041_)
  );
  NOT _308_ (
    .A(etapa2_preData1[8]),
    .Y(_042_)
  );
  NAND _309_ (
    .A(_042_),
    .B(selectorL2),
    .Y(_043_)
  );
  NAND _310_ (
    .A(_043_),
    .B(reset),
    .Y(_044_)
  );
  NOR _311_ (
    .A(_044_),
    .B(_041_),
    .Y(_006_[8])
  );
  NOT _312_ (
    .A(reset),
    .Y(_045_)
  );
  NOR _313_ (
    .A(_045_),
    .B(selectorL2),
    .Y(_008_)
  );
  NOT _314_ (
    .A(etapa1_preData3[0]),
    .Y(_046_)
  );
  NOT _315_ (
    .A(selectorL1),
    .Y(_047_)
  );
  NOR _316_ (
    .A(_047_),
    .B(_046_),
    .Y(_048_)
  );
  NOT _317_ (
    .A(etapa1_preData2[0]),
    .Y(_049_)
  );
  NOR _318_ (
    .A(selectorL1),
    .B(_049_),
    .Y(_050_)
  );
  NOR _319_ (
    .A(_050_),
    .B(_048_),
    .Y(_051_)
  );
  NOR _320_ (
    .A(_051_),
    .B(_045_),
    .Y(_005_[0])
  );
  NOT _321_ (
    .A(etapa1_preData3[1]),
    .Y(_052_)
  );
  NOR _322_ (
    .A(_047_),
    .B(_052_),
    .Y(_053_)
  );
  NOT _323_ (
    .A(etapa1_preData2[1]),
    .Y(_054_)
  );
  NOR _324_ (
    .A(selectorL1),
    .B(_054_),
    .Y(_055_)
  );
  NOR _325_ (
    .A(_055_),
    .B(_053_),
    .Y(_056_)
  );
  NOR _326_ (
    .A(_056_),
    .B(_045_),
    .Y(_005_[1])
  );
  NOT _327_ (
    .A(etapa1_preData3[2]),
    .Y(_057_)
  );
  NOR _328_ (
    .A(_047_),
    .B(_057_),
    .Y(_058_)
  );
  NOT _329_ (
    .A(etapa1_preData2[2]),
    .Y(_059_)
  );
  NOR _330_ (
    .A(selectorL1),
    .B(_059_),
    .Y(_060_)
  );
  NOR _331_ (
    .A(_060_),
    .B(_058_),
    .Y(_061_)
  );
  NOR _332_ (
    .A(_061_),
    .B(_045_),
    .Y(_005_[2])
  );
  NOT _333_ (
    .A(etapa1_preData3[3]),
    .Y(_062_)
  );
  NOR _334_ (
    .A(_047_),
    .B(_062_),
    .Y(_063_)
  );
  NOT _335_ (
    .A(etapa1_preData2[3]),
    .Y(_064_)
  );
  NOR _336_ (
    .A(selectorL1),
    .B(_064_),
    .Y(_065_)
  );
  NOR _337_ (
    .A(_065_),
    .B(_063_),
    .Y(_066_)
  );
  NOR _338_ (
    .A(_066_),
    .B(_045_),
    .Y(_005_[3])
  );
  NOT _339_ (
    .A(etapa1_preData3[4]),
    .Y(_067_)
  );
  NOR _340_ (
    .A(_047_),
    .B(_067_),
    .Y(_068_)
  );
  NOT _341_ (
    .A(etapa1_preData2[4]),
    .Y(_069_)
  );
  NOR _342_ (
    .A(selectorL1),
    .B(_069_),
    .Y(_070_)
  );
  NOR _343_ (
    .A(_070_),
    .B(_068_),
    .Y(_071_)
  );
  NOR _344_ (
    .A(_071_),
    .B(_045_),
    .Y(_005_[4])
  );
  NOT _345_ (
    .A(etapa1_preData3[5]),
    .Y(_072_)
  );
  NOR _346_ (
    .A(_047_),
    .B(_072_),
    .Y(_073_)
  );
  NOT _347_ (
    .A(etapa1_preData2[5]),
    .Y(_074_)
  );
  NOR _348_ (
    .A(selectorL1),
    .B(_074_),
    .Y(_075_)
  );
  NOR _349_ (
    .A(_075_),
    .B(_073_),
    .Y(_076_)
  );
  NOR _350_ (
    .A(_076_),
    .B(_045_),
    .Y(_005_[5])
  );
  NOT _351_ (
    .A(etapa1_preData3[6]),
    .Y(_077_)
  );
  NOR _352_ (
    .A(_047_),
    .B(_077_),
    .Y(_078_)
  );
  NOT _353_ (
    .A(etapa1_preData2[6]),
    .Y(_079_)
  );
  NOR _354_ (
    .A(selectorL1),
    .B(_079_),
    .Y(_080_)
  );
  NOR _355_ (
    .A(_080_),
    .B(_078_),
    .Y(_081_)
  );
  NOR _356_ (
    .A(_081_),
    .B(_045_),
    .Y(_005_[6])
  );
  NOT _357_ (
    .A(etapa1_preData3[7]),
    .Y(_082_)
  );
  NOR _358_ (
    .A(_047_),
    .B(_082_),
    .Y(_083_)
  );
  NOT _359_ (
    .A(etapa1_preData2[7]),
    .Y(_084_)
  );
  NOR _360_ (
    .A(selectorL1),
    .B(_084_),
    .Y(_085_)
  );
  NOR _361_ (
    .A(_085_),
    .B(_083_),
    .Y(_086_)
  );
  NOR _362_ (
    .A(_086_),
    .B(_045_),
    .Y(_005_[7])
  );
  NOR _363_ (
    .A(etapa1_preData2[8]),
    .B(selectorL1),
    .Y(_087_)
  );
  NOT _364_ (
    .A(etapa1_preData3[8]),
    .Y(_088_)
  );
  NAND _365_ (
    .A(_088_),
    .B(selectorL1),
    .Y(_089_)
  );
  NAND _366_ (
    .A(_089_),
    .B(reset),
    .Y(_090_)
  );
  NOR _367_ (
    .A(_090_),
    .B(_087_),
    .Y(_005_[8])
  );
  NOT _368_ (
    .A(etapa1_preData1[0]),
    .Y(_091_)
  );
  NOR _369_ (
    .A(_047_),
    .B(_091_),
    .Y(_092_)
  );
  NOT _370_ (
    .A(etapa1_preData0[0]),
    .Y(_093_)
  );
  NOR _371_ (
    .A(_093_),
    .B(selectorL1),
    .Y(_094_)
  );
  NOR _372_ (
    .A(_094_),
    .B(_092_),
    .Y(_095_)
  );
  NOR _373_ (
    .A(_095_),
    .B(_045_),
    .Y(_004_[0])
  );
  NOT _374_ (
    .A(etapa1_preData1[1]),
    .Y(_096_)
  );
  NOR _375_ (
    .A(_047_),
    .B(_096_),
    .Y(_097_)
  );
  NOT _376_ (
    .A(etapa1_preData0[1]),
    .Y(_098_)
  );
  NOR _377_ (
    .A(selectorL1),
    .B(_098_),
    .Y(_099_)
  );
  NOR _378_ (
    .A(_099_),
    .B(_097_),
    .Y(_100_)
  );
  NOR _379_ (
    .A(_100_),
    .B(_045_),
    .Y(_004_[1])
  );
  NOT _380_ (
    .A(etapa1_preData1[2]),
    .Y(_101_)
  );
  NOR _381_ (
    .A(_047_),
    .B(_101_),
    .Y(_102_)
  );
  NOT _382_ (
    .A(etapa1_preData0[2]),
    .Y(_103_)
  );
  NOR _383_ (
    .A(selectorL1),
    .B(_103_),
    .Y(_104_)
  );
  NOR _384_ (
    .A(_104_),
    .B(_102_),
    .Y(_105_)
  );
  NOR _385_ (
    .A(_105_),
    .B(_045_),
    .Y(_004_[2])
  );
  NOT _386_ (
    .A(etapa1_preData1[3]),
    .Y(_106_)
  );
  NOR _387_ (
    .A(_047_),
    .B(_106_),
    .Y(_107_)
  );
  NOT _388_ (
    .A(etapa1_preData0[3]),
    .Y(_108_)
  );
  NOR _389_ (
    .A(selectorL1),
    .B(_108_),
    .Y(_109_)
  );
  NOR _390_ (
    .A(_109_),
    .B(_107_),
    .Y(_110_)
  );
  NOR _391_ (
    .A(_110_),
    .B(_045_),
    .Y(_004_[3])
  );
  NOT _392_ (
    .A(etapa1_preData1[4]),
    .Y(_111_)
  );
  NOR _393_ (
    .A(_047_),
    .B(_111_),
    .Y(_112_)
  );
  NOT _394_ (
    .A(etapa1_preData0[4]),
    .Y(_113_)
  );
  NOR _395_ (
    .A(selectorL1),
    .B(_113_),
    .Y(_114_)
  );
  NOR _396_ (
    .A(_114_),
    .B(_112_),
    .Y(_115_)
  );
  NOR _397_ (
    .A(_115_),
    .B(_045_),
    .Y(_004_[4])
  );
  NOT _398_ (
    .A(etapa1_preData1[5]),
    .Y(_116_)
  );
  NOR _399_ (
    .A(_047_),
    .B(_116_),
    .Y(_117_)
  );
  NOT _400_ (
    .A(etapa1_preData0[5]),
    .Y(_118_)
  );
  NOR _401_ (
    .A(selectorL1),
    .B(_118_),
    .Y(_119_)
  );
  NOR _402_ (
    .A(_119_),
    .B(_117_),
    .Y(_120_)
  );
  NOR _403_ (
    .A(_120_),
    .B(_045_),
    .Y(_004_[5])
  );
  NOT _404_ (
    .A(etapa1_preData1[6]),
    .Y(_121_)
  );
  NOR _405_ (
    .A(_047_),
    .B(_121_),
    .Y(_122_)
  );
  NOT _406_ (
    .A(etapa1_preData0[6]),
    .Y(_123_)
  );
  NOR _407_ (
    .A(selectorL1),
    .B(_123_),
    .Y(_124_)
  );
  NOR _408_ (
    .A(_124_),
    .B(_122_),
    .Y(_125_)
  );
  NOR _409_ (
    .A(_125_),
    .B(_045_),
    .Y(_004_[6])
  );
  NOT _410_ (
    .A(etapa1_preData1[7]),
    .Y(_126_)
  );
  NOR _411_ (
    .A(_047_),
    .B(_126_),
    .Y(_127_)
  );
  NOT _412_ (
    .A(etapa1_preData0[7]),
    .Y(_128_)
  );
  NOR _413_ (
    .A(selectorL1),
    .B(_128_),
    .Y(_129_)
  );
  NOR _414_ (
    .A(_129_),
    .B(_127_),
    .Y(_130_)
  );
  NOR _415_ (
    .A(_130_),
    .B(_045_),
    .Y(_004_[7])
  );
  NOR _416_ (
    .A(etapa1_preData0[8]),
    .B(selectorL1),
    .Y(_131_)
  );
  NOT _417_ (
    .A(etapa1_preData1[8]),
    .Y(_132_)
  );
  NAND _418_ (
    .A(_132_),
    .B(selectorL1),
    .Y(_133_)
  );
  NAND _419_ (
    .A(_133_),
    .B(reset),
    .Y(_134_)
  );
  NOR _420_ (
    .A(_134_),
    .B(_131_),
    .Y(_004_[8])
  );
  NOR _421_ (
    .A(_045_),
    .B(selectorL1),
    .Y(_007_)
  );
  NOR _422_ (
    .A(data3[8]),
    .B(_046_),
    .Y(_135_)
  );
  NOT _423_ (
    .A(data3[0]),
    .Y(_136_)
  );
  NOT _424_ (
    .A(data3[8]),
    .Y(_137_)
  );
  NOR _425_ (
    .A(_137_),
    .B(_136_),
    .Y(_138_)
  );
  NOR _426_ (
    .A(_138_),
    .B(_135_),
    .Y(_139_)
  );
  NOR _427_ (
    .A(_139_),
    .B(_045_),
    .Y(_003_[0])
  );
  NOR _428_ (
    .A(_052_),
    .B(data3[8]),
    .Y(_140_)
  );
  NOT _429_ (
    .A(data3[1]),
    .Y(_141_)
  );
  NOR _430_ (
    .A(_141_),
    .B(_137_),
    .Y(_142_)
  );
  NOR _431_ (
    .A(_142_),
    .B(_140_),
    .Y(_143_)
  );
  NOR _432_ (
    .A(_143_),
    .B(_045_),
    .Y(_003_[1])
  );
  NOR _433_ (
    .A(_057_),
    .B(data3[8]),
    .Y(_144_)
  );
  NOT _434_ (
    .A(data3[2]),
    .Y(_145_)
  );
  NOR _435_ (
    .A(_145_),
    .B(_137_),
    .Y(_146_)
  );
  NOR _436_ (
    .A(_146_),
    .B(_144_),
    .Y(_147_)
  );
  NOR _437_ (
    .A(_147_),
    .B(_045_),
    .Y(_003_[2])
  );
  NOR _438_ (
    .A(_062_),
    .B(data3[8]),
    .Y(_148_)
  );
  NOT _439_ (
    .A(data3[3]),
    .Y(_149_)
  );
  NOR _440_ (
    .A(_149_),
    .B(_137_),
    .Y(_150_)
  );
  NOR _441_ (
    .A(_150_),
    .B(_148_),
    .Y(_151_)
  );
  NOR _442_ (
    .A(_151_),
    .B(_045_),
    .Y(_003_[3])
  );
  NOR _443_ (
    .A(_067_),
    .B(data3[8]),
    .Y(_152_)
  );
  NOT _444_ (
    .A(data3[4]),
    .Y(_153_)
  );
  NOR _445_ (
    .A(_153_),
    .B(_137_),
    .Y(_154_)
  );
  NOR _446_ (
    .A(_154_),
    .B(_152_),
    .Y(_155_)
  );
  NOR _447_ (
    .A(_155_),
    .B(_045_),
    .Y(_003_[4])
  );
  NOR _448_ (
    .A(_072_),
    .B(data3[8]),
    .Y(_156_)
  );
  NOT _449_ (
    .A(data3[5]),
    .Y(_157_)
  );
  NOR _450_ (
    .A(_157_),
    .B(_137_),
    .Y(_158_)
  );
  NOR _451_ (
    .A(_158_),
    .B(_156_),
    .Y(_159_)
  );
  NOR _452_ (
    .A(_159_),
    .B(_045_),
    .Y(_003_[5])
  );
  NOR _453_ (
    .A(_077_),
    .B(data3[8]),
    .Y(_160_)
  );
  NOT _454_ (
    .A(data3[6]),
    .Y(_161_)
  );
  NOR _455_ (
    .A(_161_),
    .B(_137_),
    .Y(_162_)
  );
  NOR _456_ (
    .A(_162_),
    .B(_160_),
    .Y(_163_)
  );
  NOR _457_ (
    .A(_163_),
    .B(_045_),
    .Y(_003_[6])
  );
  NOR _458_ (
    .A(_082_),
    .B(data3[8]),
    .Y(_164_)
  );
  NOT _459_ (
    .A(data3[7]),
    .Y(_165_)
  );
  NOR _460_ (
    .A(_165_),
    .B(_137_),
    .Y(_166_)
  );
  NOR _461_ (
    .A(_166_),
    .B(_164_),
    .Y(_167_)
  );
  NOR _462_ (
    .A(_167_),
    .B(_045_),
    .Y(_003_[7])
  );
  NOR _463_ (
    .A(_045_),
    .B(_137_),
    .Y(_003_[8])
  );
  NOR _464_ (
    .A(data2[8]),
    .B(_049_),
    .Y(_168_)
  );
  NOT _465_ (
    .A(data2[0]),
    .Y(_169_)
  );
  NOT _466_ (
    .A(data2[8]),
    .Y(_170_)
  );
  NOR _467_ (
    .A(_170_),
    .B(_169_),
    .Y(_171_)
  );
  NOR _468_ (
    .A(_171_),
    .B(_168_),
    .Y(_172_)
  );
  NOR _469_ (
    .A(_172_),
    .B(_045_),
    .Y(_002_[0])
  );
  NOR _470_ (
    .A(_054_),
    .B(data2[8]),
    .Y(_173_)
  );
  NOT _471_ (
    .A(data2[1]),
    .Y(_174_)
  );
  NOR _472_ (
    .A(_174_),
    .B(_170_),
    .Y(_175_)
  );
  NOR _473_ (
    .A(_175_),
    .B(_173_),
    .Y(_176_)
  );
  NOR _474_ (
    .A(_176_),
    .B(_045_),
    .Y(_002_[1])
  );
  NOR _475_ (
    .A(_059_),
    .B(data2[8]),
    .Y(_177_)
  );
  NOT _476_ (
    .A(data2[2]),
    .Y(_178_)
  );
  NOR _477_ (
    .A(_178_),
    .B(_170_),
    .Y(_179_)
  );
  NOR _478_ (
    .A(_179_),
    .B(_177_),
    .Y(_180_)
  );
  NOR _479_ (
    .A(_180_),
    .B(_045_),
    .Y(_002_[2])
  );
  NOR _480_ (
    .A(_064_),
    .B(data2[8]),
    .Y(_181_)
  );
  NOT _481_ (
    .A(data2[3]),
    .Y(_182_)
  );
  NOR _482_ (
    .A(_182_),
    .B(_170_),
    .Y(_183_)
  );
  NOR _483_ (
    .A(_183_),
    .B(_181_),
    .Y(_184_)
  );
  NOR _484_ (
    .A(_184_),
    .B(_045_),
    .Y(_002_[3])
  );
  NOR _485_ (
    .A(_069_),
    .B(data2[8]),
    .Y(_185_)
  );
  NOT _486_ (
    .A(data2[4]),
    .Y(_186_)
  );
  NOR _487_ (
    .A(_186_),
    .B(_170_),
    .Y(_187_)
  );
  NOR _488_ (
    .A(_187_),
    .B(_185_),
    .Y(_188_)
  );
  NOR _489_ (
    .A(_188_),
    .B(_045_),
    .Y(_002_[4])
  );
  NOR _490_ (
    .A(_074_),
    .B(data2[8]),
    .Y(_189_)
  );
  NOT _491_ (
    .A(data2[5]),
    .Y(_190_)
  );
  NOR _492_ (
    .A(_190_),
    .B(_170_),
    .Y(_191_)
  );
  NOR _493_ (
    .A(_191_),
    .B(_189_),
    .Y(_192_)
  );
  NOR _494_ (
    .A(_192_),
    .B(_045_),
    .Y(_002_[5])
  );
  NOR _495_ (
    .A(_079_),
    .B(data2[8]),
    .Y(_193_)
  );
  NOT _496_ (
    .A(data2[6]),
    .Y(_194_)
  );
  NOR _497_ (
    .A(_194_),
    .B(_170_),
    .Y(_195_)
  );
  NOR _498_ (
    .A(_195_),
    .B(_193_),
    .Y(_196_)
  );
  NOR _499_ (
    .A(_196_),
    .B(_045_),
    .Y(_002_[6])
  );
  NOR _500_ (
    .A(_084_),
    .B(data2[8]),
    .Y(_197_)
  );
  NOT _501_ (
    .A(data2[7]),
    .Y(_198_)
  );
  NOR _502_ (
    .A(_198_),
    .B(_170_),
    .Y(_199_)
  );
  NOR _503_ (
    .A(_199_),
    .B(_197_),
    .Y(_200_)
  );
  NOR _504_ (
    .A(_200_),
    .B(_045_),
    .Y(_002_[7])
  );
  NOR _505_ (
    .A(_045_),
    .B(_170_),
    .Y(_002_[8])
  );
  NOR _506_ (
    .A(data1[8]),
    .B(_091_),
    .Y(_201_)
  );
  NOT _507_ (
    .A(data1[0]),
    .Y(_202_)
  );
  NOT _508_ (
    .A(data1[8]),
    .Y(_203_)
  );
  NOR _509_ (
    .A(_203_),
    .B(_202_),
    .Y(_204_)
  );
  NOR _510_ (
    .A(_204_),
    .B(_201_),
    .Y(_205_)
  );
  NOR _511_ (
    .A(_205_),
    .B(_045_),
    .Y(_001_[0])
  );
  NOR _512_ (
    .A(_096_),
    .B(data1[8]),
    .Y(_206_)
  );
  NOT _513_ (
    .A(data1[1]),
    .Y(_207_)
  );
  NOR _514_ (
    .A(_207_),
    .B(_203_),
    .Y(_208_)
  );
  NOR _515_ (
    .A(_208_),
    .B(_206_),
    .Y(_209_)
  );
  NOR _516_ (
    .A(_209_),
    .B(_045_),
    .Y(_001_[1])
  );
  NOR _517_ (
    .A(_101_),
    .B(data1[8]),
    .Y(_210_)
  );
  NOT _518_ (
    .A(data1[2]),
    .Y(_211_)
  );
  NOR _519_ (
    .A(_211_),
    .B(_203_),
    .Y(_212_)
  );
  NOR _520_ (
    .A(_212_),
    .B(_210_),
    .Y(_213_)
  );
  NOR _521_ (
    .A(_213_),
    .B(_045_),
    .Y(_001_[2])
  );
  NOR _522_ (
    .A(_106_),
    .B(data1[8]),
    .Y(_214_)
  );
  NOT _523_ (
    .A(data1[3]),
    .Y(_215_)
  );
  NOR _524_ (
    .A(_215_),
    .B(_203_),
    .Y(_216_)
  );
  NOR _525_ (
    .A(_216_),
    .B(_214_),
    .Y(_217_)
  );
  NOR _526_ (
    .A(_217_),
    .B(_045_),
    .Y(_001_[3])
  );
  NOR _527_ (
    .A(_111_),
    .B(data1[8]),
    .Y(_218_)
  );
  NOT _528_ (
    .A(data1[4]),
    .Y(_219_)
  );
  NOR _529_ (
    .A(_219_),
    .B(_203_),
    .Y(_220_)
  );
  NOR _530_ (
    .A(_220_),
    .B(_218_),
    .Y(_221_)
  );
  NOR _531_ (
    .A(_221_),
    .B(_045_),
    .Y(_001_[4])
  );
  NOR _532_ (
    .A(_116_),
    .B(data1[8]),
    .Y(_222_)
  );
  NOT _533_ (
    .A(data1[5]),
    .Y(_223_)
  );
  NOR _534_ (
    .A(_223_),
    .B(_203_),
    .Y(_224_)
  );
  NOR _535_ (
    .A(_224_),
    .B(_222_),
    .Y(_225_)
  );
  NOR _536_ (
    .A(_225_),
    .B(_045_),
    .Y(_001_[5])
  );
  NOR _537_ (
    .A(_121_),
    .B(data1[8]),
    .Y(_226_)
  );
  NOT _538_ (
    .A(data1[6]),
    .Y(_227_)
  );
  NOR _539_ (
    .A(_227_),
    .B(_203_),
    .Y(_228_)
  );
  NOR _540_ (
    .A(_228_),
    .B(_226_),
    .Y(_229_)
  );
  NOR _541_ (
    .A(_229_),
    .B(_045_),
    .Y(_001_[6])
  );
  NOR _542_ (
    .A(_126_),
    .B(data1[8]),
    .Y(_230_)
  );
  NOT _543_ (
    .A(data1[7]),
    .Y(_231_)
  );
  NOR _544_ (
    .A(_231_),
    .B(_203_),
    .Y(_232_)
  );
  NOR _545_ (
    .A(_232_),
    .B(_230_),
    .Y(_233_)
  );
  NOR _546_ (
    .A(_233_),
    .B(_045_),
    .Y(_001_[7])
  );
  NOR _547_ (
    .A(_045_),
    .B(_203_),
    .Y(_001_[8])
  );
  NOR _548_ (
    .A(_093_),
    .B(data0[8]),
    .Y(_234_)
  );
  NOT _549_ (
    .A(data0[8]),
    .Y(_235_)
  );
  NOT _550_ (
    .A(data0[0]),
    .Y(_236_)
  );
  NOR _551_ (
    .A(_236_),
    .B(_235_),
    .Y(_237_)
  );
  NOR _552_ (
    .A(_237_),
    .B(_234_),
    .Y(_238_)
  );
  NOR _553_ (
    .A(_238_),
    .B(_045_),
    .Y(_000_[0])
  );
  NOR _554_ (
    .A(data0[8]),
    .B(_098_),
    .Y(_239_)
  );
  NOT _555_ (
    .A(data0[1]),
    .Y(_240_)
  );
  NOR _556_ (
    .A(_235_),
    .B(_240_),
    .Y(_241_)
  );
  NOR _557_ (
    .A(_241_),
    .B(_239_),
    .Y(_242_)
  );
  NOR _558_ (
    .A(_242_),
    .B(_045_),
    .Y(_000_[1])
  );
  NOR _559_ (
    .A(_103_),
    .B(data0[8]),
    .Y(_243_)
  );
  NOT _560_ (
    .A(data0[2]),
    .Y(_244_)
  );
  NOR _561_ (
    .A(_244_),
    .B(_235_),
    .Y(_245_)
  );
  NOR _562_ (
    .A(_245_),
    .B(_243_),
    .Y(_246_)
  );
  NOR _563_ (
    .A(_246_),
    .B(_045_),
    .Y(_000_[2])
  );
  NOR _564_ (
    .A(_108_),
    .B(data0[8]),
    .Y(_247_)
  );
  NOT _565_ (
    .A(data0[3]),
    .Y(_248_)
  );
  NOR _566_ (
    .A(_248_),
    .B(_235_),
    .Y(_249_)
  );
  NOR _567_ (
    .A(_249_),
    .B(_247_),
    .Y(_250_)
  );
  NOR _568_ (
    .A(_250_),
    .B(_045_),
    .Y(_000_[3])
  );
  NOR _569_ (
    .A(_113_),
    .B(data0[8]),
    .Y(_251_)
  );
  NOT _570_ (
    .A(data0[4]),
    .Y(_252_)
  );
  NOR _571_ (
    .A(_252_),
    .B(_235_),
    .Y(_253_)
  );
  NOR _572_ (
    .A(_253_),
    .B(_251_),
    .Y(_254_)
  );
  NOR _573_ (
    .A(_254_),
    .B(_045_),
    .Y(_000_[4])
  );
  NOR _574_ (
    .A(_118_),
    .B(data0[8]),
    .Y(_255_)
  );
  NOT _575_ (
    .A(data0[5]),
    .Y(_256_)
  );
  NOR _576_ (
    .A(_256_),
    .B(_235_),
    .Y(_257_)
  );
  NOR _577_ (
    .A(_257_),
    .B(_255_),
    .Y(_258_)
  );
  NOR _578_ (
    .A(_258_),
    .B(_045_),
    .Y(_000_[5])
  );
  NOR _579_ (
    .A(_123_),
    .B(data0[8]),
    .Y(_259_)
  );
  NOT _580_ (
    .A(data0[6]),
    .Y(_260_)
  );
  NOR _581_ (
    .A(_260_),
    .B(_235_),
    .Y(_261_)
  );
  NOR _582_ (
    .A(_261_),
    .B(_259_),
    .Y(_262_)
  );
  NOR _583_ (
    .A(_262_),
    .B(_045_),
    .Y(_000_[6])
  );
  NOR _584_ (
    .A(_128_),
    .B(data0[8]),
    .Y(_263_)
  );
  NOT _585_ (
    .A(data0[7]),
    .Y(_264_)
  );
  NOR _586_ (
    .A(_264_),
    .B(_235_),
    .Y(_265_)
  );
  NOR _587_ (
    .A(_265_),
    .B(_263_),
    .Y(_266_)
  );
  NOR _588_ (
    .A(_266_),
    .B(_045_),
    .Y(_000_[7])
  );
  NOR _589_ (
    .A(_045_),
    .B(_235_),
    .Y(_000_[8])
  );
  DFF _590_ (
    .C(clk_4f),
    .D(_008_),
    .Q(selectorL2)
  );
  DFF _591_ (
    .C(clk_4f),
    .D(_006_[0]),
    .Q(outEtapaL2[0])
  );
  DFF _592_ (
    .C(clk_4f),
    .D(_006_[1]),
    .Q(outEtapaL2[1])
  );
  DFF _593_ (
    .C(clk_4f),
    .D(_006_[2]),
    .Q(outEtapaL2[2])
  );
  DFF _594_ (
    .C(clk_4f),
    .D(_006_[3]),
    .Q(outEtapaL2[3])
  );
  DFF _595_ (
    .C(clk_4f),
    .D(_006_[4]),
    .Q(outEtapaL2[4])
  );
  DFF _596_ (
    .C(clk_4f),
    .D(_006_[5]),
    .Q(outEtapaL2[5])
  );
  DFF _597_ (
    .C(clk_4f),
    .D(_006_[6]),
    .Q(outEtapaL2[6])
  );
  DFF _598_ (
    .C(clk_4f),
    .D(_006_[7]),
    .Q(outEtapaL2[7])
  );
  DFF _599_ (
    .C(clk_4f),
    .D(_006_[8]),
    .Q(outEtapaL2[8])
  );
  DFF _600_ (
    .C(clk_2f),
    .D(_007_),
    .Q(selectorL1)
  );
  DFF _601_ (
    .C(clk_2f),
    .D(_004_[0]),
    .Q(etapa2_preData0[0])
  );
  DFF _602_ (
    .C(clk_2f),
    .D(_004_[1]),
    .Q(etapa2_preData0[1])
  );
  DFF _603_ (
    .C(clk_2f),
    .D(_004_[2]),
    .Q(etapa2_preData0[2])
  );
  DFF _604_ (
    .C(clk_2f),
    .D(_004_[3]),
    .Q(etapa2_preData0[3])
  );
  DFF _605_ (
    .C(clk_2f),
    .D(_004_[4]),
    .Q(etapa2_preData0[4])
  );
  DFF _606_ (
    .C(clk_2f),
    .D(_004_[5]),
    .Q(etapa2_preData0[5])
  );
  DFF _607_ (
    .C(clk_2f),
    .D(_004_[6]),
    .Q(etapa2_preData0[6])
  );
  DFF _608_ (
    .C(clk_2f),
    .D(_004_[7]),
    .Q(etapa2_preData0[7])
  );
  DFF _609_ (
    .C(clk_2f),
    .D(_004_[8]),
    .Q(etapa2_preData0[8])
  );
  DFF _610_ (
    .C(clk_2f),
    .D(_005_[0]),
    .Q(etapa2_preData1[0])
  );
  DFF _611_ (
    .C(clk_2f),
    .D(_005_[1]),
    .Q(etapa2_preData1[1])
  );
  DFF _612_ (
    .C(clk_2f),
    .D(_005_[2]),
    .Q(etapa2_preData1[2])
  );
  DFF _613_ (
    .C(clk_2f),
    .D(_005_[3]),
    .Q(etapa2_preData1[3])
  );
  DFF _614_ (
    .C(clk_2f),
    .D(_005_[4]),
    .Q(etapa2_preData1[4])
  );
  DFF _615_ (
    .C(clk_2f),
    .D(_005_[5]),
    .Q(etapa2_preData1[5])
  );
  DFF _616_ (
    .C(clk_2f),
    .D(_005_[6]),
    .Q(etapa2_preData1[6])
  );
  DFF _617_ (
    .C(clk_2f),
    .D(_005_[7]),
    .Q(etapa2_preData1[7])
  );
  DFF _618_ (
    .C(clk_2f),
    .D(_005_[8]),
    .Q(etapa2_preData1[8])
  );
  DFF _619_ (
    .C(clk_f),
    .D(_000_[0]),
    .Q(etapa1_preData0[0])
  );
  DFF _620_ (
    .C(clk_f),
    .D(_000_[1]),
    .Q(etapa1_preData0[1])
  );
  DFF _621_ (
    .C(clk_f),
    .D(_000_[2]),
    .Q(etapa1_preData0[2])
  );
  DFF _622_ (
    .C(clk_f),
    .D(_000_[3]),
    .Q(etapa1_preData0[3])
  );
  DFF _623_ (
    .C(clk_f),
    .D(_000_[4]),
    .Q(etapa1_preData0[4])
  );
  DFF _624_ (
    .C(clk_f),
    .D(_000_[5]),
    .Q(etapa1_preData0[5])
  );
  DFF _625_ (
    .C(clk_f),
    .D(_000_[6]),
    .Q(etapa1_preData0[6])
  );
  DFF _626_ (
    .C(clk_f),
    .D(_000_[7]),
    .Q(etapa1_preData0[7])
  );
  DFF _627_ (
    .C(clk_f),
    .D(_000_[8]),
    .Q(etapa1_preData0[8])
  );
  DFF _628_ (
    .C(clk_f),
    .D(_001_[0]),
    .Q(etapa1_preData1[0])
  );
  DFF _629_ (
    .C(clk_f),
    .D(_001_[1]),
    .Q(etapa1_preData1[1])
  );
  DFF _630_ (
    .C(clk_f),
    .D(_001_[2]),
    .Q(etapa1_preData1[2])
  );
  DFF _631_ (
    .C(clk_f),
    .D(_001_[3]),
    .Q(etapa1_preData1[3])
  );
  DFF _632_ (
    .C(clk_f),
    .D(_001_[4]),
    .Q(etapa1_preData1[4])
  );
  DFF _633_ (
    .C(clk_f),
    .D(_001_[5]),
    .Q(etapa1_preData1[5])
  );
  DFF _634_ (
    .C(clk_f),
    .D(_001_[6]),
    .Q(etapa1_preData1[6])
  );
  DFF _635_ (
    .C(clk_f),
    .D(_001_[7]),
    .Q(etapa1_preData1[7])
  );
  DFF _636_ (
    .C(clk_f),
    .D(_001_[8]),
    .Q(etapa1_preData1[8])
  );
  DFF _637_ (
    .C(clk_f),
    .D(_002_[0]),
    .Q(etapa1_preData2[0])
  );
  DFF _638_ (
    .C(clk_f),
    .D(_002_[1]),
    .Q(etapa1_preData2[1])
  );
  DFF _639_ (
    .C(clk_f),
    .D(_002_[2]),
    .Q(etapa1_preData2[2])
  );
  DFF _640_ (
    .C(clk_f),
    .D(_002_[3]),
    .Q(etapa1_preData2[3])
  );
  DFF _641_ (
    .C(clk_f),
    .D(_002_[4]),
    .Q(etapa1_preData2[4])
  );
  DFF _642_ (
    .C(clk_f),
    .D(_002_[5]),
    .Q(etapa1_preData2[5])
  );
  DFF _643_ (
    .C(clk_f),
    .D(_002_[6]),
    .Q(etapa1_preData2[6])
  );
  DFF _644_ (
    .C(clk_f),
    .D(_002_[7]),
    .Q(etapa1_preData2[7])
  );
  DFF _645_ (
    .C(clk_f),
    .D(_002_[8]),
    .Q(etapa1_preData2[8])
  );
  DFF _646_ (
    .C(clk_f),
    .D(_003_[0]),
    .Q(etapa1_preData3[0])
  );
  DFF _647_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(etapa1_preData3[1])
  );
  DFF _648_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(etapa1_preData3[2])
  );
  DFF _649_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(etapa1_preData3[3])
  );
  DFF _650_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(etapa1_preData3[4])
  );
  DFF _651_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(etapa1_preData3[5])
  );
  DFF _652_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(etapa1_preData3[6])
  );
  DFF _653_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(etapa1_preData3[7])
  );
  DFF _654_ (
    .C(clk_f),
    .D(_003_[8]),
    .Q(etapa1_preData3[8])
  );
endmodule

(* top =  1  *)
(* src = "phyEst.v:5" *)
module phyEst(clk16, clk4f, clk2f, clkf, reset, paralelo0, paralelo1, paralelo2, paralelo3, data_0, data_1, data_2, data_3);
  (* src = "phyEst.v:5" *)
  input clk16;
  (* src = "phyEst.v:5" *)
  input clk2f;
  (* src = "phyEst.v:5" *)
  input clk4f;
  (* src = "phyEst.v:5" *)
  input clkf;
  (* src = "phyEst.v:5" *)
  output [8:0] data_0;
  (* src = "phyEst.v:5" *)
  output [8:0] data_1;
  (* src = "phyEst.v:5" *)
  output [8:0] data_2;
  (* src = "phyEst.v:5" *)
  output [8:0] data_3;
  (* src = "phyEst.v:5" *)
  input [8:0] paralelo0;
  (* src = "phyEst.v:5" *)
  input [8:0] paralelo1;
  (* src = "phyEst.v:5" *)
  input [8:0] paralelo2;
  (* src = "phyEst.v:5" *)
  input [8:0] paralelo3;
  (* src = "phyEst.v:5" *)
  input reset;
  (* src = "phyEst.v:8" *)
  wire [1:0] serial;
  (* src = "phyEst.v:11" *)
  phyEst_rx phyEstRx (
    .clk_16(clk16),
    .clk_2f(clk2f),
    .clk_4f(clk4f),
    .clk_f(clkf),
    .data_0(data_0),
    .data_1(data_1),
    .data_2(data_2),
    .data_3(data_3),
    .reset(reset),
    .serial(serial)
  );
  (* src = "phyEst.v:25" *)
  phyEst_tx phyEstTx (
    .clk16f(clk16),
    .clk2f(clk2f),
    .clk4f(clk4f),
    .clkf(clkf),
    .paralelo0(paralelo0),
    .paralelo1(paralelo1),
    .paralelo2(paralelo2),
    .paralelo3(paralelo3),
    .reset(reset),
    .reset_L(reset),
    .serial(serial)
  );
endmodule

(* src = "phyEst_rx.v:4" *)
module phyEst_rx(clk_f, clk_2f, clk_4f, clk_16, reset, serial, data_0, data_1, data_2, data_3);
  (* src = "phyEst_rx.v:7" *)
  input clk_16;
  (* src = "phyEst_rx.v:5" *)
  input clk_2f;
  (* src = "phyEst_rx.v:6" *)
  input clk_4f;
  (* src = "phyEst_rx.v:4" *)
  input clk_f;
  (* src = "phyEst_rx.v:10" *)
  output [8:0] data_0;
  (* src = "phyEst_rx.v:11" *)
  output [8:0] data_1;
  (* src = "phyEst_rx.v:12" *)
  output [8:0] data_2;
  (* src = "phyEst_rx.v:13" *)
  output [8:0] data_3;
  (* src = "phyEst_rx.v:15" *)
  wire [8:0] inDemuxesEst;
  (* src = "phyEst_rx.v:8" *)
  input reset;
  (* src = "phyEst_rx.v:9" *)
  input [1:0] serial;
  (* src = "phyEst_rx.v:22" *)
  demuxEst demuxEstes (
    .clk_2f(clk_2f),
    .clk_4f(clk_4f),
    .clk_f(clk_f),
    .data0(data_0),
    .data1(data_1),
    .data2(data_2),
    .data3(data_3),
    .inEtapaL2(inDemuxesEst),
    .reset(reset)
  );
  (* src = "phyEst_rx.v:17" *)
  serialParaleloEst serial_paralelo (
    .clk16(clk_16),
    .outParalelo(inDemuxesEst),
    .reset16(reset),
    .serial(serial)
  );
endmodule

(* src = "phyEst_tx.v:4" *)
module phyEst_tx(clk16f, clk4f, clk2f, clkf, reset, reset_L, paralelo0, paralelo1, paralelo2, paralelo3, serial);
  (* src = "phyEst_tx.v:5" *)
  input clk16f;
  (* src = "phyEst_tx.v:7" *)
  input clk2f;
  (* src = "phyEst_tx.v:6" *)
  input clk4f;
  (* src = "phyEst_tx.v:8" *)
  input clkf;
  (* src = "phyEst_tx.v:18" *)
  wire [8:0] outEtapaL2;
  (* src = "phyEst_tx.v:11" *)
  input [8:0] paralelo0;
  (* src = "phyEst_tx.v:12" *)
  input [8:0] paralelo1;
  (* src = "phyEst_tx.v:13" *)
  input [8:0] paralelo2;
  (* src = "phyEst_tx.v:14" *)
  input [8:0] paralelo3;
  (* src = "phyEst_tx.v:9" *)
  input reset;
  (* src = "phyEst_tx.v:10" *)
  input reset_L;
  (* src = "phyEst_tx.v:15" *)
  output [1:0] serial;
  (* src = "phyEst_tx.v:23" *)
  muxesEst muxesEstMod (
    .clk_2f(clk2f),
    .clk_4f(clk4f),
    .clk_f(clkf),
    .data0(paralelo0),
    .data1(paralelo1),
    .data2(paralelo2),
    .data3(paralelo3),
    .outEtapaL2(outEtapaL2),
    .reset(reset_L)
  );
  (* src = "phyEst_tx.v:35" *)
  ParaleloSerialEst psMod (
    .clk16f(clk16f),
    .clk4f(clk4f),
    .paralelo(outEtapaL2),
    .reset(reset),
    .reset_L(reset_L),
    .serial(serial)
  );
endmodule

(* src = "serialParaleloEst.v:5" *)
module serialParaleloEst(clk16, reset16, serial, outParalelo);
  (* src = "serialParaleloEst.v:13" *)
  wire [2:0] _00_;
  (* src = "serialParaleloEst.v:13" *)
  wire [1:0] _01_;
  (* src = "serialParaleloEst.v:13" *)
  wire [8:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "serialParaleloEst.v:5" *)
  input clk16;
  (* src = "serialParaleloEst.v:7" *)
  wire [2:0] contador;
  (* src = "serialParaleloEst.v:8" *)
  wire [1:0] i;
  (* src = "serialParaleloEst.v:5" *)
  output [8:0] outParalelo;
  (* src = "serialParaleloEst.v:5" *)
  input reset16;
  (* src = "serialParaleloEst.v:5" *)
  input [1:0] serial;
  NOT _25_ (
    .A(i[1]),
    .Y(_03_)
  );
  NOT _26_ (
    .A(i[0]),
    .Y(_04_)
  );
  NOR _27_ (
    .A(_04_),
    .B(_03_),
    .Y(_05_)
  );
  NOR _28_ (
    .A(_05_),
    .B(outParalelo[8]),
    .Y(_06_)
  );
  NOT _29_ (
    .A(contador[2]),
    .Y(_07_)
  );
  NOT _30_ (
    .A(reset16),
    .Y(_08_)
  );
  NOR _31_ (
    .A(_08_),
    .B(_07_),
    .Y(_00_[2])
  );
  NOR _32_ (
    .A(_05_),
    .B(_08_),
    .Y(_09_)
  );
  NOR _33_ (
    .A(_09_),
    .B(_00_[2]),
    .Y(_10_)
  );
  NOR _34_ (
    .A(_10_),
    .B(_06_),
    .Y(_02_[8])
  );
  NOR _35_ (
    .A(_05_),
    .B(outParalelo[0]),
    .Y(_11_)
  );
  NOR _36_ (
    .A(_11_),
    .B(_08_),
    .Y(_02_[0])
  );
  NOR _37_ (
    .A(_05_),
    .B(outParalelo[1]),
    .Y(_12_)
  );
  NOR _38_ (
    .A(_12_),
    .B(_08_),
    .Y(_02_[1])
  );
  NOR _39_ (
    .A(_05_),
    .B(outParalelo[2]),
    .Y(_13_)
  );
  NOR _40_ (
    .A(_13_),
    .B(_08_),
    .Y(_02_[2])
  );
  NOR _41_ (
    .A(_05_),
    .B(outParalelo[3]),
    .Y(_14_)
  );
  NOR _42_ (
    .A(_14_),
    .B(_08_),
    .Y(_02_[3])
  );
  NOR _43_ (
    .A(_05_),
    .B(outParalelo[4]),
    .Y(_15_)
  );
  NOR _44_ (
    .A(_15_),
    .B(_08_),
    .Y(_02_[4])
  );
  NOR _45_ (
    .A(_05_),
    .B(outParalelo[5]),
    .Y(_16_)
  );
  NOR _46_ (
    .A(_16_),
    .B(_08_),
    .Y(_02_[5])
  );
  NOR _47_ (
    .A(_05_),
    .B(outParalelo[6]),
    .Y(_17_)
  );
  NOR _48_ (
    .A(_17_),
    .B(_08_),
    .Y(_02_[6])
  );
  NOR _49_ (
    .A(_05_),
    .B(outParalelo[7]),
    .Y(_18_)
  );
  NOR _50_ (
    .A(_18_),
    .B(_08_),
    .Y(_02_[7])
  );
  NAND _51_ (
    .A(reset16),
    .B(contador[0]),
    .Y(_19_)
  );
  NAND _52_ (
    .A(_00_[2]),
    .B(contador[1]),
    .Y(_20_)
  );
  NAND _53_ (
    .A(_20_),
    .B(_19_),
    .Y(_00_[0])
  );
  NAND _54_ (
    .A(reset16),
    .B(contador[1]),
    .Y(_21_)
  );
  NOR _55_ (
    .A(_21_),
    .B(contador[2]),
    .Y(_00_[1])
  );
  NOR _56_ (
    .A(i[0]),
    .B(_08_),
    .Y(_01_[0])
  );
  NAND _57_ (
    .A(i[0]),
    .B(i[1]),
    .Y(_22_)
  );
  NAND _58_ (
    .A(_22_),
    .B(reset16),
    .Y(_23_)
  );
  NOR _59_ (
    .A(i[0]),
    .B(i[1]),
    .Y(_24_)
  );
  NOR _60_ (
    .A(_24_),
    .B(_23_),
    .Y(_01_[1])
  );
  DFF _61_ (
    .C(clk16),
    .D(_02_[0]),
    .Q(outParalelo[0])
  );
  DFF _62_ (
    .C(clk16),
    .D(_02_[1]),
    .Q(outParalelo[1])
  );
  DFF _63_ (
    .C(clk16),
    .D(_02_[2]),
    .Q(outParalelo[2])
  );
  DFF _64_ (
    .C(clk16),
    .D(_02_[3]),
    .Q(outParalelo[3])
  );
  DFF _65_ (
    .C(clk16),
    .D(_02_[4]),
    .Q(outParalelo[4])
  );
  DFF _66_ (
    .C(clk16),
    .D(_02_[5]),
    .Q(outParalelo[5])
  );
  DFF _67_ (
    .C(clk16),
    .D(_02_[6]),
    .Q(outParalelo[6])
  );
  DFF _68_ (
    .C(clk16),
    .D(_02_[7]),
    .Q(outParalelo[7])
  );
  DFF _69_ (
    .C(clk16),
    .D(_02_[8]),
    .Q(outParalelo[8])
  );
  DFF _70_ (
    .C(clk16),
    .D(_00_[0]),
    .Q(contador[0])
  );
  DFF _71_ (
    .C(clk16),
    .D(_00_[1]),
    .Q(contador[1])
  );
  DFF _72_ (
    .C(clk16),
    .D(_00_[2]),
    .Q(contador[2])
  );
  DFF _73_ (
    .C(clk16),
    .D(_01_[0]),
    .Q(i[0])
  );
  DFF _74_ (
    .C(clk16),
    .D(_01_[1]),
    .Q(i[1])
  );
endmodule
