/* Generated by Yosys 0.7+574 (git sha1 0fad1570, gcc 6.3.0-18+deb9u1 -fPIC -Os) */

(* src = "ParaleloSerialEst.v:1" *)
module ParaleloSerialEst(clk16f, clk4f, reset, reset_L, paralelo, serial);
  (* src = "ParaleloSerialEst.v:12" *)
  wire [1:0] _000_;
  (* src = "ParaleloSerialEst.v:12" *)
  wire [1:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  (* src = "ParaleloSerialEst.v:2" *)
  input clk16f;
  (* src = "ParaleloSerialEst.v:3" *)
  input clk4f;
  (* src = "ParaleloSerialEst.v:9" *)
  wire [1:0] counterbc;
  (* src = "ParaleloSerialEst.v:10" *)
  wire [1:0] counterdata;
  (* src = "ParaleloSerialEst.v:6" *)
  input [8:0] paralelo;
  (* src = "ParaleloSerialEst.v:4" *)
  input reset;
  (* src = "ParaleloSerialEst.v:5" *)
  input reset_L;
  (* src = "ParaleloSerialEst.v:7" *)
  output [1:0] serial;
  NOT _047_ (
    .A(counterdata[0]),
    .Y(_002_)
  );
  NOT _048_ (
    .A(counterdata[1]),
    .Y(_003_)
  );
  NOT _049_ (
    .A(paralelo[8]),
    .Y(_004_)
  );
  NOT _050_ (
    .A(reset_L),
    .Y(_005_)
  );
  NOT _051_ (
    .A(paralelo[0]),
    .Y(_006_)
  );
  NOT _052_ (
    .A(paralelo[1]),
    .Y(_007_)
  );
  NOR _053_ (
    .A(counterbc[0]),
    .B(counterbc[1]),
    .Y(_008_)
  );
  NAND _054_ (
    .A(counterbc[0]),
    .B(counterbc[1]),
    .Y(_009_)
  );
  NAND _055_ (
    .A(_004_),
    .B(_009_),
    .Y(_010_)
  );
  NOR _056_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  NOT _057_ (
    .A(_011_),
    .Y(_012_)
  );
  NOR _058_ (
    .A(counterdata[0]),
    .B(_003_),
    .Y(_013_)
  );
  NOR _059_ (
    .A(counterdata[0]),
    .B(counterdata[1]),
    .Y(_014_)
  );
  NOR _060_ (
    .A(_002_),
    .B(counterdata[1]),
    .Y(_015_)
  );
  NAND _061_ (
    .A(counterdata[0]),
    .B(counterdata[1]),
    .Y(_016_)
  );
  NOR _062_ (
    .A(_006_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _063_ (
    .A(paralelo[6]),
    .B(_014_),
    .Y(_018_)
  );
  NAND _064_ (
    .A(paralelo[4]),
    .B(_015_),
    .Y(_019_)
  );
  NAND _065_ (
    .A(paralelo[2]),
    .B(_013_),
    .Y(_020_)
  );
  NAND _066_ (
    .A(_018_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _067_ (
    .A(_017_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _068_ (
    .A(_019_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _069_ (
    .A(paralelo[8]),
    .B(_023_),
    .Y(_024_)
  );
  NAND _070_ (
    .A(_012_),
    .B(_024_),
    .Y(serial[0])
  );
  NOR _071_ (
    .A(_007_),
    .B(_016_),
    .Y(_025_)
  );
  NAND _072_ (
    .A(paralelo[7]),
    .B(_014_),
    .Y(_026_)
  );
  NAND _073_ (
    .A(paralelo[5]),
    .B(_015_),
    .Y(_027_)
  );
  NAND _074_ (
    .A(paralelo[3]),
    .B(_013_),
    .Y(_028_)
  );
  NAND _075_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _076_ (
    .A(_025_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _077_ (
    .A(_027_),
    .B(_030_),
    .Y(_031_)
  );
  NAND _078_ (
    .A(paralelo[8]),
    .B(_031_),
    .Y(_032_)
  );
  NAND _079_ (
    .A(_010_),
    .B(_032_),
    .Y(serial[1])
  );
  NAND _080_ (
    .A(counterdata[0]),
    .B(paralelo[8]),
    .Y(_033_)
  );
  NOT _081_ (
    .A(_033_),
    .Y(_034_)
  );
  NOR _082_ (
    .A(counterdata[0]),
    .B(paralelo[8]),
    .Y(_035_)
  );
  NOT _083_ (
    .A(_035_),
    .Y(_036_)
  );
  NAND _084_ (
    .A(reset_L),
    .B(_036_),
    .Y(_037_)
  );
  NOR _085_ (
    .A(_034_),
    .B(_037_),
    .Y(_001_[0])
  );
  NOR _086_ (
    .A(_003_),
    .B(_034_),
    .Y(_038_)
  );
  NOR _087_ (
    .A(counterdata[1]),
    .B(_033_),
    .Y(_039_)
  );
  NOR _088_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _089_ (
    .A(_005_),
    .B(_040_),
    .Y(_001_[1])
  );
  NOR _090_ (
    .A(counterbc[0]),
    .B(_004_),
    .Y(_041_)
  );
  NAND _091_ (
    .A(counterbc[0]),
    .B(_004_),
    .Y(_042_)
  );
  NAND _092_ (
    .A(reset_L),
    .B(_042_),
    .Y(_043_)
  );
  NOR _093_ (
    .A(_041_),
    .B(_043_),
    .Y(_000_[0])
  );
  NAND _094_ (
    .A(counterbc[1]),
    .B(paralelo[8]),
    .Y(_044_)
  );
  NOT _095_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _096_ (
    .A(_011_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _097_ (
    .A(_005_),
    .B(_046_),
    .Y(_000_[1])
  );
  (* src = "ParaleloSerialEst.v:12" *)
  DFF _098_ (
    .C(clk16f),
    .D(_000_[0]),
    .Q(counterbc[0])
  );
  (* src = "ParaleloSerialEst.v:12" *)
  DFF _099_ (
    .C(clk16f),
    .D(_000_[1]),
    .Q(counterbc[1])
  );
  (* src = "ParaleloSerialEst.v:12" *)
  DFF _100_ (
    .C(clk16f),
    .D(_001_[0]),
    .Q(counterdata[0])
  );
  (* src = "ParaleloSerialEst.v:12" *)
  DFF _101_ (
    .C(clk16f),
    .D(_001_[1]),
    .Q(counterdata[1])
  );
endmodule

(* src = "demuxEst.v:3" *)
module demuxEst(clk_f, clk_2f, clk_4f, reset, inEtapaL2, data0, data1, data2, data3);
  (* src = "demuxEst.v:67" *)
  wire [8:0] _000_;
  (* src = "demuxEst.v:67" *)
  wire [8:0] _001_;
  (* src = "demuxEst.v:67" *)
  wire [8:0] _002_;
  (* src = "demuxEst.v:67" *)
  wire [8:0] _003_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _004_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _005_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _006_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _007_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _008_;
  (* src = "demuxEst.v:36" *)
  wire [8:0] _009_;
  (* src = "demuxEst.v:18" *)
  wire [8:0] _010_;
  (* src = "demuxEst.v:18" *)
  wire [8:0] _011_;
  (* src = "demuxEst.v:36" *)
  wire _012_;
  (* src = "demuxEst.v:18" *)
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  (* src = "demuxEst.v:4" *)
  input clk_2f;
  (* src = "demuxEst.v:5" *)
  input clk_4f;
  (* src = "demuxEst.v:3" *)
  input clk_f;
  (* src = "demuxEst.v:8" *)
  output [8:0] data0;
  (* src = "demuxEst.v:9" *)
  output [8:0] data1;
  (* src = "demuxEst.v:10" *)
  output [8:0] data2;
  (* src = "demuxEst.v:11" *)
  output [8:0] data3;
  (* src = "demuxEst.v:15" *)
  wire [8:0] etapa1_inData0;
  (* src = "demuxEst.v:15" *)
  wire [8:0] etapa1_inData1;
  (* src = "demuxEst.v:15" *)
  wire [8:0] etapa1_inData2;
  (* src = "demuxEst.v:15" *)
  wire [8:0] etapa1_inData3;
  (* src = "demuxEst.v:16" *)
  wire [8:0] etapa2_inData0;
  (* src = "demuxEst.v:16" *)
  wire [8:0] etapa2_inData1;
  (* src = "demuxEst.v:7" *)
  input [8:0] inEtapaL2;
  (* src = "demuxEst.v:13" *)
  wire [8:0] outEtapaL1L2_0;
  (* src = "demuxEst.v:13" *)
  wire [8:0] outEtapaL1L2_1;
  (* src = "demuxEst.v:6" *)
  input reset;
  (* src = "demuxEst.v:14" *)
  wire selectorL1;
  (* src = "demuxEst.v:14" *)
  wire selectorL2;
  NOT _231_ (
    .A(reset),
    .Y(_014_)
  );
  NOT _232_ (
    .A(etapa1_inData2[0]),
    .Y(_015_)
  );
  NOT _233_ (
    .A(etapa1_inData2[1]),
    .Y(_016_)
  );
  NOT _234_ (
    .A(etapa1_inData2[2]),
    .Y(_017_)
  );
  NOT _235_ (
    .A(etapa1_inData2[3]),
    .Y(_018_)
  );
  NOT _236_ (
    .A(etapa1_inData2[4]),
    .Y(_019_)
  );
  NOT _237_ (
    .A(etapa1_inData2[5]),
    .Y(_020_)
  );
  NOT _238_ (
    .A(etapa1_inData2[6]),
    .Y(_021_)
  );
  NOT _239_ (
    .A(etapa1_inData2[7]),
    .Y(_022_)
  );
  NOT _240_ (
    .A(etapa1_inData2[8]),
    .Y(_023_)
  );
  NOT _241_ (
    .A(etapa1_inData0[0]),
    .Y(_024_)
  );
  NOT _242_ (
    .A(etapa1_inData0[1]),
    .Y(_025_)
  );
  NOT _243_ (
    .A(etapa1_inData0[2]),
    .Y(_026_)
  );
  NOT _244_ (
    .A(etapa1_inData0[3]),
    .Y(_027_)
  );
  NOT _245_ (
    .A(etapa1_inData0[4]),
    .Y(_028_)
  );
  NOT _246_ (
    .A(etapa1_inData0[5]),
    .Y(_029_)
  );
  NOT _247_ (
    .A(etapa1_inData0[6]),
    .Y(_030_)
  );
  NOT _248_ (
    .A(etapa1_inData0[7]),
    .Y(_031_)
  );
  NOT _249_ (
    .A(etapa1_inData0[8]),
    .Y(_032_)
  );
  NOT _250_ (
    .A(outEtapaL1L2_0[0]),
    .Y(_033_)
  );
  NOT _251_ (
    .A(outEtapaL1L2_0[1]),
    .Y(_034_)
  );
  NOT _252_ (
    .A(outEtapaL1L2_0[2]),
    .Y(_035_)
  );
  NOT _253_ (
    .A(outEtapaL1L2_0[3]),
    .Y(_036_)
  );
  NOT _254_ (
    .A(outEtapaL1L2_0[4]),
    .Y(_037_)
  );
  NOT _255_ (
    .A(outEtapaL1L2_0[5]),
    .Y(_038_)
  );
  NOT _256_ (
    .A(outEtapaL1L2_0[6]),
    .Y(_039_)
  );
  NOT _257_ (
    .A(outEtapaL1L2_0[7]),
    .Y(_040_)
  );
  NOT _258_ (
    .A(outEtapaL1L2_0[8]),
    .Y(_041_)
  );
  NOT _259_ (
    .A(etapa2_inData1[0]),
    .Y(_042_)
  );
  NOT _260_ (
    .A(etapa2_inData1[1]),
    .Y(_043_)
  );
  NOT _261_ (
    .A(etapa2_inData1[2]),
    .Y(_044_)
  );
  NOT _262_ (
    .A(etapa2_inData1[3]),
    .Y(_045_)
  );
  NOT _263_ (
    .A(etapa2_inData1[4]),
    .Y(_046_)
  );
  NOT _264_ (
    .A(etapa2_inData1[5]),
    .Y(_047_)
  );
  NOT _265_ (
    .A(etapa2_inData1[6]),
    .Y(_048_)
  );
  NOT _266_ (
    .A(etapa2_inData1[7]),
    .Y(_049_)
  );
  NOT _267_ (
    .A(etapa2_inData1[8]),
    .Y(_050_)
  );
  NOT _268_ (
    .A(etapa2_inData0[0]),
    .Y(_051_)
  );
  NOT _269_ (
    .A(etapa2_inData0[1]),
    .Y(_052_)
  );
  NOT _270_ (
    .A(etapa2_inData0[2]),
    .Y(_053_)
  );
  NOT _271_ (
    .A(etapa2_inData0[3]),
    .Y(_054_)
  );
  NOT _272_ (
    .A(etapa2_inData0[4]),
    .Y(_055_)
  );
  NOT _273_ (
    .A(etapa2_inData0[5]),
    .Y(_056_)
  );
  NOT _274_ (
    .A(etapa2_inData0[6]),
    .Y(_057_)
  );
  NOT _275_ (
    .A(etapa2_inData0[7]),
    .Y(_058_)
  );
  NOT _276_ (
    .A(etapa2_inData0[8]),
    .Y(_059_)
  );
  NOT _277_ (
    .A(inEtapaL2[0]),
    .Y(_060_)
  );
  NOT _278_ (
    .A(inEtapaL2[1]),
    .Y(_061_)
  );
  NOT _279_ (
    .A(inEtapaL2[2]),
    .Y(_062_)
  );
  NOT _280_ (
    .A(inEtapaL2[3]),
    .Y(_063_)
  );
  NOT _281_ (
    .A(inEtapaL2[4]),
    .Y(_064_)
  );
  NOT _282_ (
    .A(inEtapaL2[5]),
    .Y(_065_)
  );
  NOT _283_ (
    .A(inEtapaL2[6]),
    .Y(_066_)
  );
  NOT _284_ (
    .A(inEtapaL2[7]),
    .Y(_067_)
  );
  NOT _285_ (
    .A(inEtapaL2[8]),
    .Y(_068_)
  );
  NAND _286_ (
    .A(etapa1_inData3[1]),
    .B(reset),
    .Y(_069_)
  );
  NOT _287_ (
    .A(_069_),
    .Y(_003_[1])
  );
  NAND _288_ (
    .A(reset),
    .B(etapa1_inData3[2]),
    .Y(_070_)
  );
  NOT _289_ (
    .A(_070_),
    .Y(_003_[2])
  );
  NAND _290_ (
    .A(reset),
    .B(etapa1_inData3[3]),
    .Y(_071_)
  );
  NOT _291_ (
    .A(_071_),
    .Y(_003_[3])
  );
  NAND _292_ (
    .A(reset),
    .B(etapa1_inData3[4]),
    .Y(_072_)
  );
  NOT _293_ (
    .A(_072_),
    .Y(_003_[4])
  );
  NAND _294_ (
    .A(reset),
    .B(etapa1_inData3[5]),
    .Y(_073_)
  );
  NOT _295_ (
    .A(_073_),
    .Y(_003_[5])
  );
  NAND _296_ (
    .A(reset),
    .B(etapa1_inData3[6]),
    .Y(_074_)
  );
  NOT _297_ (
    .A(_074_),
    .Y(_003_[6])
  );
  NAND _298_ (
    .A(reset),
    .B(etapa1_inData3[7]),
    .Y(_075_)
  );
  NOT _299_ (
    .A(_075_),
    .Y(_003_[7])
  );
  NAND _300_ (
    .A(reset),
    .B(etapa1_inData3[8]),
    .Y(_076_)
  );
  NOT _301_ (
    .A(_076_),
    .Y(_003_[8])
  );
  NOR _302_ (
    .A(_014_),
    .B(_015_),
    .Y(_002_[0])
  );
  NOR _303_ (
    .A(_014_),
    .B(_016_),
    .Y(_002_[1])
  );
  NOR _304_ (
    .A(_014_),
    .B(_017_),
    .Y(_002_[2])
  );
  NOR _305_ (
    .A(_014_),
    .B(_018_),
    .Y(_002_[3])
  );
  NOR _306_ (
    .A(_014_),
    .B(_019_),
    .Y(_002_[4])
  );
  NOR _307_ (
    .A(_014_),
    .B(_020_),
    .Y(_002_[5])
  );
  NOR _308_ (
    .A(_014_),
    .B(_021_),
    .Y(_002_[6])
  );
  NOR _309_ (
    .A(_014_),
    .B(_022_),
    .Y(_002_[7])
  );
  NOR _310_ (
    .A(_014_),
    .B(_023_),
    .Y(_002_[8])
  );
  NAND _311_ (
    .A(reset),
    .B(etapa1_inData1[0]),
    .Y(_077_)
  );
  NOT _312_ (
    .A(_077_),
    .Y(_001_[0])
  );
  NAND _313_ (
    .A(reset),
    .B(etapa1_inData1[1]),
    .Y(_078_)
  );
  NOT _314_ (
    .A(_078_),
    .Y(_001_[1])
  );
  NAND _315_ (
    .A(reset),
    .B(etapa1_inData1[2]),
    .Y(_079_)
  );
  NOT _316_ (
    .A(_079_),
    .Y(_001_[2])
  );
  NAND _317_ (
    .A(reset),
    .B(etapa1_inData1[3]),
    .Y(_080_)
  );
  NOT _318_ (
    .A(_080_),
    .Y(_001_[3])
  );
  NAND _319_ (
    .A(reset),
    .B(etapa1_inData1[4]),
    .Y(_081_)
  );
  NOT _320_ (
    .A(_081_),
    .Y(_001_[4])
  );
  NAND _321_ (
    .A(reset),
    .B(etapa1_inData1[5]),
    .Y(_082_)
  );
  NOT _322_ (
    .A(_082_),
    .Y(_001_[5])
  );
  NAND _323_ (
    .A(reset),
    .B(etapa1_inData1[6]),
    .Y(_083_)
  );
  NOT _324_ (
    .A(_083_),
    .Y(_001_[6])
  );
  NAND _325_ (
    .A(reset),
    .B(etapa1_inData1[7]),
    .Y(_084_)
  );
  NOT _326_ (
    .A(_084_),
    .Y(_001_[7])
  );
  NAND _327_ (
    .A(reset),
    .B(etapa1_inData1[8]),
    .Y(_085_)
  );
  NOT _328_ (
    .A(_085_),
    .Y(_001_[8])
  );
  NOR _329_ (
    .A(_014_),
    .B(_024_),
    .Y(_000_[0])
  );
  NOR _330_ (
    .A(_014_),
    .B(_025_),
    .Y(_000_[1])
  );
  NOR _331_ (
    .A(_014_),
    .B(_026_),
    .Y(_000_[2])
  );
  NOR _332_ (
    .A(_014_),
    .B(_027_),
    .Y(_000_[3])
  );
  NOR _333_ (
    .A(_014_),
    .B(_028_),
    .Y(_000_[4])
  );
  NOR _334_ (
    .A(_014_),
    .B(_029_),
    .Y(_000_[5])
  );
  NOR _335_ (
    .A(_014_),
    .B(_030_),
    .Y(_000_[6])
  );
  NOR _336_ (
    .A(_014_),
    .B(_031_),
    .Y(_000_[7])
  );
  NOR _337_ (
    .A(_014_),
    .B(_032_),
    .Y(_000_[8])
  );
  NAND _338_ (
    .A(reset),
    .B(outEtapaL1L2_1[0]),
    .Y(_086_)
  );
  NOT _339_ (
    .A(_086_),
    .Y(_009_[0])
  );
  NAND _340_ (
    .A(reset),
    .B(outEtapaL1L2_1[1]),
    .Y(_087_)
  );
  NOT _341_ (
    .A(_087_),
    .Y(_009_[1])
  );
  NAND _342_ (
    .A(reset),
    .B(outEtapaL1L2_1[2]),
    .Y(_088_)
  );
  NOT _343_ (
    .A(_088_),
    .Y(_009_[2])
  );
  NAND _344_ (
    .A(reset),
    .B(outEtapaL1L2_1[3]),
    .Y(_089_)
  );
  NOT _345_ (
    .A(_089_),
    .Y(_009_[3])
  );
  NAND _346_ (
    .A(reset),
    .B(outEtapaL1L2_1[4]),
    .Y(_090_)
  );
  NOT _347_ (
    .A(_090_),
    .Y(_009_[4])
  );
  NAND _348_ (
    .A(reset),
    .B(outEtapaL1L2_1[5]),
    .Y(_091_)
  );
  NOT _349_ (
    .A(_091_),
    .Y(_009_[5])
  );
  NAND _350_ (
    .A(reset),
    .B(outEtapaL1L2_1[6]),
    .Y(_092_)
  );
  NOT _351_ (
    .A(_092_),
    .Y(_009_[6])
  );
  NAND _352_ (
    .A(reset),
    .B(outEtapaL1L2_1[7]),
    .Y(_093_)
  );
  NOT _353_ (
    .A(_093_),
    .Y(_009_[7])
  );
  NAND _354_ (
    .A(reset),
    .B(outEtapaL1L2_1[8]),
    .Y(_094_)
  );
  NOT _355_ (
    .A(_094_),
    .Y(_009_[8])
  );
  NOR _356_ (
    .A(_014_),
    .B(_033_),
    .Y(_008_[0])
  );
  NOR _357_ (
    .A(_014_),
    .B(_034_),
    .Y(_008_[1])
  );
  NOR _358_ (
    .A(_014_),
    .B(_035_),
    .Y(_008_[2])
  );
  NOR _359_ (
    .A(_014_),
    .B(_036_),
    .Y(_008_[3])
  );
  NOR _360_ (
    .A(_014_),
    .B(_037_),
    .Y(_008_[4])
  );
  NOR _361_ (
    .A(_014_),
    .B(_038_),
    .Y(_008_[5])
  );
  NOR _362_ (
    .A(_014_),
    .B(_039_),
    .Y(_008_[6])
  );
  NOR _363_ (
    .A(_014_),
    .B(_040_),
    .Y(_008_[7])
  );
  NOR _364_ (
    .A(_014_),
    .B(_041_),
    .Y(_008_[8])
  );
  NAND _365_ (
    .A(_042_),
    .B(selectorL1),
    .Y(_095_)
  );
  NAND _366_ (
    .A(reset),
    .B(_095_),
    .Y(_096_)
  );
  NOR _367_ (
    .A(etapa1_inData3[0]),
    .B(selectorL1),
    .Y(_097_)
  );
  NOR _368_ (
    .A(_096_),
    .B(_097_),
    .Y(_007_[0])
  );
  NAND _369_ (
    .A(selectorL1),
    .B(_043_),
    .Y(_098_)
  );
  NAND _370_ (
    .A(reset),
    .B(_098_),
    .Y(_099_)
  );
  NOR _371_ (
    .A(etapa1_inData3[1]),
    .B(selectorL1),
    .Y(_100_)
  );
  NOR _372_ (
    .A(_099_),
    .B(_100_),
    .Y(_007_[1])
  );
  NAND _373_ (
    .A(selectorL1),
    .B(_044_),
    .Y(_101_)
  );
  NAND _374_ (
    .A(reset),
    .B(_101_),
    .Y(_102_)
  );
  NOR _375_ (
    .A(etapa1_inData3[2]),
    .B(selectorL1),
    .Y(_103_)
  );
  NOR _376_ (
    .A(_102_),
    .B(_103_),
    .Y(_007_[2])
  );
  NAND _377_ (
    .A(selectorL1),
    .B(_045_),
    .Y(_104_)
  );
  NAND _378_ (
    .A(reset),
    .B(_104_),
    .Y(_105_)
  );
  NOR _379_ (
    .A(etapa1_inData3[3]),
    .B(selectorL1),
    .Y(_106_)
  );
  NOR _380_ (
    .A(_105_),
    .B(_106_),
    .Y(_007_[3])
  );
  NAND _381_ (
    .A(selectorL1),
    .B(_046_),
    .Y(_107_)
  );
  NAND _382_ (
    .A(reset),
    .B(_107_),
    .Y(_108_)
  );
  NOR _383_ (
    .A(etapa1_inData3[4]),
    .B(selectorL1),
    .Y(_109_)
  );
  NOR _384_ (
    .A(_108_),
    .B(_109_),
    .Y(_007_[4])
  );
  NAND _385_ (
    .A(selectorL1),
    .B(_047_),
    .Y(_110_)
  );
  NAND _386_ (
    .A(reset),
    .B(_110_),
    .Y(_111_)
  );
  NOR _387_ (
    .A(etapa1_inData3[5]),
    .B(selectorL1),
    .Y(_112_)
  );
  NOR _388_ (
    .A(_111_),
    .B(_112_),
    .Y(_007_[5])
  );
  NAND _389_ (
    .A(selectorL1),
    .B(_048_),
    .Y(_113_)
  );
  NAND _390_ (
    .A(reset),
    .B(_113_),
    .Y(_114_)
  );
  NOR _391_ (
    .A(etapa1_inData3[6]),
    .B(selectorL1),
    .Y(_115_)
  );
  NOR _392_ (
    .A(_114_),
    .B(_115_),
    .Y(_007_[6])
  );
  NAND _393_ (
    .A(selectorL1),
    .B(_049_),
    .Y(_116_)
  );
  NAND _394_ (
    .A(reset),
    .B(_116_),
    .Y(_117_)
  );
  NOR _395_ (
    .A(etapa1_inData3[7]),
    .B(selectorL1),
    .Y(_118_)
  );
  NOR _396_ (
    .A(_117_),
    .B(_118_),
    .Y(_007_[7])
  );
  NAND _397_ (
    .A(selectorL1),
    .B(_050_),
    .Y(_119_)
  );
  NAND _398_ (
    .A(reset),
    .B(_119_),
    .Y(_120_)
  );
  NOR _399_ (
    .A(etapa1_inData3[8]),
    .B(selectorL1),
    .Y(_121_)
  );
  NOR _400_ (
    .A(_120_),
    .B(_121_),
    .Y(_007_[8])
  );
  NOR _401_ (
    .A(etapa2_inData1[0]),
    .B(selectorL1),
    .Y(_122_)
  );
  NOR _402_ (
    .A(_014_),
    .B(selectorL1),
    .Y(_012_)
  );
  NOR _403_ (
    .A(_002_[0]),
    .B(_012_),
    .Y(_123_)
  );
  NOR _404_ (
    .A(_122_),
    .B(_123_),
    .Y(_006_[0])
  );
  NOR _405_ (
    .A(selectorL1),
    .B(etapa2_inData1[1]),
    .Y(_124_)
  );
  NOR _406_ (
    .A(_002_[1]),
    .B(_012_),
    .Y(_125_)
  );
  NOR _407_ (
    .A(_124_),
    .B(_125_),
    .Y(_006_[1])
  );
  NOR _408_ (
    .A(selectorL1),
    .B(etapa2_inData1[2]),
    .Y(_126_)
  );
  NOR _409_ (
    .A(_002_[2]),
    .B(_012_),
    .Y(_127_)
  );
  NOR _410_ (
    .A(_126_),
    .B(_127_),
    .Y(_006_[2])
  );
  NOR _411_ (
    .A(selectorL1),
    .B(etapa2_inData1[3]),
    .Y(_128_)
  );
  NOR _412_ (
    .A(_002_[3]),
    .B(_012_),
    .Y(_129_)
  );
  NOR _413_ (
    .A(_128_),
    .B(_129_),
    .Y(_006_[3])
  );
  NOR _414_ (
    .A(selectorL1),
    .B(etapa2_inData1[4]),
    .Y(_130_)
  );
  NOR _415_ (
    .A(_002_[4]),
    .B(_012_),
    .Y(_131_)
  );
  NOR _416_ (
    .A(_130_),
    .B(_131_),
    .Y(_006_[4])
  );
  NOR _417_ (
    .A(selectorL1),
    .B(etapa2_inData1[5]),
    .Y(_132_)
  );
  NOR _418_ (
    .A(_002_[5]),
    .B(_012_),
    .Y(_133_)
  );
  NOR _419_ (
    .A(_132_),
    .B(_133_),
    .Y(_006_[5])
  );
  NOR _420_ (
    .A(selectorL1),
    .B(etapa2_inData1[6]),
    .Y(_134_)
  );
  NOR _421_ (
    .A(_002_[6]),
    .B(_012_),
    .Y(_135_)
  );
  NOR _422_ (
    .A(_134_),
    .B(_135_),
    .Y(_006_[6])
  );
  NOR _423_ (
    .A(selectorL1),
    .B(etapa2_inData1[7]),
    .Y(_136_)
  );
  NOR _424_ (
    .A(_002_[7]),
    .B(_012_),
    .Y(_137_)
  );
  NOR _425_ (
    .A(_136_),
    .B(_137_),
    .Y(_006_[7])
  );
  NOR _426_ (
    .A(selectorL1),
    .B(etapa2_inData1[8]),
    .Y(_138_)
  );
  NOR _427_ (
    .A(_002_[8]),
    .B(_012_),
    .Y(_139_)
  );
  NOR _428_ (
    .A(_138_),
    .B(_139_),
    .Y(_006_[8])
  );
  NAND _429_ (
    .A(selectorL1),
    .B(_051_),
    .Y(_140_)
  );
  NAND _430_ (
    .A(reset),
    .B(_140_),
    .Y(_141_)
  );
  NOR _431_ (
    .A(etapa1_inData1[0]),
    .B(selectorL1),
    .Y(_142_)
  );
  NOR _432_ (
    .A(_141_),
    .B(_142_),
    .Y(_005_[0])
  );
  NAND _433_ (
    .A(selectorL1),
    .B(_052_),
    .Y(_143_)
  );
  NAND _434_ (
    .A(reset),
    .B(_143_),
    .Y(_144_)
  );
  NOR _435_ (
    .A(etapa1_inData1[1]),
    .B(selectorL1),
    .Y(_145_)
  );
  NOR _436_ (
    .A(_144_),
    .B(_145_),
    .Y(_005_[1])
  );
  NAND _437_ (
    .A(selectorL1),
    .B(_053_),
    .Y(_146_)
  );
  NAND _438_ (
    .A(reset),
    .B(_146_),
    .Y(_147_)
  );
  NOR _439_ (
    .A(etapa1_inData1[2]),
    .B(selectorL1),
    .Y(_148_)
  );
  NOR _440_ (
    .A(_147_),
    .B(_148_),
    .Y(_005_[2])
  );
  NAND _441_ (
    .A(selectorL1),
    .B(_054_),
    .Y(_149_)
  );
  NAND _442_ (
    .A(reset),
    .B(_149_),
    .Y(_150_)
  );
  NOR _443_ (
    .A(etapa1_inData1[3]),
    .B(selectorL1),
    .Y(_151_)
  );
  NOR _444_ (
    .A(_150_),
    .B(_151_),
    .Y(_005_[3])
  );
  NAND _445_ (
    .A(selectorL1),
    .B(_055_),
    .Y(_152_)
  );
  NAND _446_ (
    .A(reset),
    .B(_152_),
    .Y(_153_)
  );
  NOR _447_ (
    .A(etapa1_inData1[4]),
    .B(selectorL1),
    .Y(_154_)
  );
  NOR _448_ (
    .A(_153_),
    .B(_154_),
    .Y(_005_[4])
  );
  NAND _449_ (
    .A(selectorL1),
    .B(_056_),
    .Y(_155_)
  );
  NAND _450_ (
    .A(reset),
    .B(_155_),
    .Y(_156_)
  );
  NOR _451_ (
    .A(etapa1_inData1[5]),
    .B(selectorL1),
    .Y(_157_)
  );
  NOR _452_ (
    .A(_156_),
    .B(_157_),
    .Y(_005_[5])
  );
  NAND _453_ (
    .A(selectorL1),
    .B(_057_),
    .Y(_158_)
  );
  NAND _454_ (
    .A(reset),
    .B(_158_),
    .Y(_159_)
  );
  NOR _455_ (
    .A(etapa1_inData1[6]),
    .B(selectorL1),
    .Y(_160_)
  );
  NOR _456_ (
    .A(_159_),
    .B(_160_),
    .Y(_005_[6])
  );
  NAND _457_ (
    .A(selectorL1),
    .B(_058_),
    .Y(_161_)
  );
  NAND _458_ (
    .A(reset),
    .B(_161_),
    .Y(_162_)
  );
  NOR _459_ (
    .A(etapa1_inData1[7]),
    .B(selectorL1),
    .Y(_163_)
  );
  NOR _460_ (
    .A(_162_),
    .B(_163_),
    .Y(_005_[7])
  );
  NAND _461_ (
    .A(selectorL1),
    .B(_059_),
    .Y(_164_)
  );
  NAND _462_ (
    .A(reset),
    .B(_164_),
    .Y(_165_)
  );
  NOR _463_ (
    .A(etapa1_inData1[8]),
    .B(selectorL1),
    .Y(_166_)
  );
  NOR _464_ (
    .A(_165_),
    .B(_166_),
    .Y(_005_[8])
  );
  NOR _465_ (
    .A(selectorL1),
    .B(etapa2_inData0[0]),
    .Y(_167_)
  );
  NOR _466_ (
    .A(_000_[0]),
    .B(_012_),
    .Y(_168_)
  );
  NOR _467_ (
    .A(_167_),
    .B(_168_),
    .Y(_004_[0])
  );
  NOR _468_ (
    .A(selectorL1),
    .B(etapa2_inData0[1]),
    .Y(_169_)
  );
  NOR _469_ (
    .A(_000_[1]),
    .B(_012_),
    .Y(_170_)
  );
  NOR _470_ (
    .A(_169_),
    .B(_170_),
    .Y(_004_[1])
  );
  NOR _471_ (
    .A(selectorL1),
    .B(etapa2_inData0[2]),
    .Y(_171_)
  );
  NOR _472_ (
    .A(_000_[2]),
    .B(_012_),
    .Y(_172_)
  );
  NOR _473_ (
    .A(_171_),
    .B(_172_),
    .Y(_004_[2])
  );
  NOR _474_ (
    .A(selectorL1),
    .B(etapa2_inData0[3]),
    .Y(_173_)
  );
  NOR _475_ (
    .A(_000_[3]),
    .B(_012_),
    .Y(_174_)
  );
  NOR _476_ (
    .A(_173_),
    .B(_174_),
    .Y(_004_[3])
  );
  NOR _477_ (
    .A(selectorL1),
    .B(etapa2_inData0[4]),
    .Y(_175_)
  );
  NOR _478_ (
    .A(_000_[4]),
    .B(_012_),
    .Y(_176_)
  );
  NOR _479_ (
    .A(_175_),
    .B(_176_),
    .Y(_004_[4])
  );
  NOR _480_ (
    .A(selectorL1),
    .B(etapa2_inData0[5]),
    .Y(_177_)
  );
  NOR _481_ (
    .A(_000_[5]),
    .B(_012_),
    .Y(_178_)
  );
  NOR _482_ (
    .A(_177_),
    .B(_178_),
    .Y(_004_[5])
  );
  NOR _483_ (
    .A(selectorL1),
    .B(etapa2_inData0[6]),
    .Y(_179_)
  );
  NOR _484_ (
    .A(_000_[6]),
    .B(_012_),
    .Y(_180_)
  );
  NOR _485_ (
    .A(_179_),
    .B(_180_),
    .Y(_004_[6])
  );
  NOR _486_ (
    .A(selectorL1),
    .B(etapa2_inData0[7]),
    .Y(_181_)
  );
  NOR _487_ (
    .A(_000_[7]),
    .B(_012_),
    .Y(_182_)
  );
  NOR _488_ (
    .A(_181_),
    .B(_182_),
    .Y(_004_[7])
  );
  NOR _489_ (
    .A(selectorL1),
    .B(etapa2_inData0[8]),
    .Y(_183_)
  );
  NOR _490_ (
    .A(_000_[8]),
    .B(_012_),
    .Y(_184_)
  );
  NOR _491_ (
    .A(_183_),
    .B(_184_),
    .Y(_004_[8])
  );
  NOR _492_ (
    .A(_014_),
    .B(selectorL2),
    .Y(_013_)
  );
  NAND _493_ (
    .A(_060_),
    .B(selectorL2),
    .Y(_185_)
  );
  NAND _494_ (
    .A(reset),
    .B(_185_),
    .Y(_186_)
  );
  NOR _495_ (
    .A(outEtapaL1L2_1[0]),
    .B(selectorL2),
    .Y(_187_)
  );
  NOR _496_ (
    .A(_186_),
    .B(_187_),
    .Y(_011_[0])
  );
  NAND _497_ (
    .A(selectorL2),
    .B(_061_),
    .Y(_188_)
  );
  NAND _498_ (
    .A(reset),
    .B(_188_),
    .Y(_189_)
  );
  NOR _499_ (
    .A(outEtapaL1L2_1[1]),
    .B(selectorL2),
    .Y(_190_)
  );
  NOR _500_ (
    .A(_189_),
    .B(_190_),
    .Y(_011_[1])
  );
  NAND _501_ (
    .A(selectorL2),
    .B(_062_),
    .Y(_191_)
  );
  NAND _502_ (
    .A(reset),
    .B(_191_),
    .Y(_192_)
  );
  NOR _503_ (
    .A(outEtapaL1L2_1[2]),
    .B(selectorL2),
    .Y(_193_)
  );
  NOR _504_ (
    .A(_192_),
    .B(_193_),
    .Y(_011_[2])
  );
  NAND _505_ (
    .A(selectorL2),
    .B(_063_),
    .Y(_194_)
  );
  NAND _506_ (
    .A(reset),
    .B(_194_),
    .Y(_195_)
  );
  NOR _507_ (
    .A(outEtapaL1L2_1[3]),
    .B(selectorL2),
    .Y(_196_)
  );
  NOR _508_ (
    .A(_195_),
    .B(_196_),
    .Y(_011_[3])
  );
  NAND _509_ (
    .A(selectorL2),
    .B(_064_),
    .Y(_197_)
  );
  NAND _510_ (
    .A(reset),
    .B(_197_),
    .Y(_198_)
  );
  NOR _511_ (
    .A(outEtapaL1L2_1[4]),
    .B(selectorL2),
    .Y(_199_)
  );
  NOR _512_ (
    .A(_198_),
    .B(_199_),
    .Y(_011_[4])
  );
  NAND _513_ (
    .A(selectorL2),
    .B(_065_),
    .Y(_200_)
  );
  NAND _514_ (
    .A(reset),
    .B(_200_),
    .Y(_201_)
  );
  NOR _515_ (
    .A(outEtapaL1L2_1[5]),
    .B(selectorL2),
    .Y(_202_)
  );
  NOR _516_ (
    .A(_201_),
    .B(_202_),
    .Y(_011_[5])
  );
  NAND _517_ (
    .A(selectorL2),
    .B(_066_),
    .Y(_203_)
  );
  NAND _518_ (
    .A(reset),
    .B(_203_),
    .Y(_204_)
  );
  NOR _519_ (
    .A(outEtapaL1L2_1[6]),
    .B(selectorL2),
    .Y(_205_)
  );
  NOR _520_ (
    .A(_204_),
    .B(_205_),
    .Y(_011_[6])
  );
  NAND _521_ (
    .A(selectorL2),
    .B(_067_),
    .Y(_206_)
  );
  NAND _522_ (
    .A(reset),
    .B(_206_),
    .Y(_207_)
  );
  NOR _523_ (
    .A(outEtapaL1L2_1[7]),
    .B(selectorL2),
    .Y(_208_)
  );
  NOR _524_ (
    .A(_207_),
    .B(_208_),
    .Y(_011_[7])
  );
  NAND _525_ (
    .A(selectorL2),
    .B(_068_),
    .Y(_209_)
  );
  NAND _526_ (
    .A(reset),
    .B(_209_),
    .Y(_210_)
  );
  NOR _527_ (
    .A(outEtapaL1L2_1[8]),
    .B(selectorL2),
    .Y(_211_)
  );
  NOR _528_ (
    .A(_210_),
    .B(_211_),
    .Y(_011_[8])
  );
  NOR _529_ (
    .A(inEtapaL2[0]),
    .B(selectorL2),
    .Y(_212_)
  );
  NOR _530_ (
    .A(_008_[0]),
    .B(_013_),
    .Y(_213_)
  );
  NOR _531_ (
    .A(_212_),
    .B(_213_),
    .Y(_010_[0])
  );
  NOR _532_ (
    .A(selectorL2),
    .B(inEtapaL2[1]),
    .Y(_214_)
  );
  NOR _533_ (
    .A(_008_[1]),
    .B(_013_),
    .Y(_215_)
  );
  NOR _534_ (
    .A(_214_),
    .B(_215_),
    .Y(_010_[1])
  );
  NOR _535_ (
    .A(selectorL2),
    .B(inEtapaL2[2]),
    .Y(_216_)
  );
  NOR _536_ (
    .A(_008_[2]),
    .B(_013_),
    .Y(_217_)
  );
  NOR _537_ (
    .A(_216_),
    .B(_217_),
    .Y(_010_[2])
  );
  NOR _538_ (
    .A(selectorL2),
    .B(inEtapaL2[3]),
    .Y(_218_)
  );
  NOR _539_ (
    .A(_008_[3]),
    .B(_013_),
    .Y(_219_)
  );
  NOR _540_ (
    .A(_218_),
    .B(_219_),
    .Y(_010_[3])
  );
  NOR _541_ (
    .A(selectorL2),
    .B(inEtapaL2[4]),
    .Y(_220_)
  );
  NOR _542_ (
    .A(_008_[4]),
    .B(_013_),
    .Y(_221_)
  );
  NOR _543_ (
    .A(_220_),
    .B(_221_),
    .Y(_010_[4])
  );
  NOR _544_ (
    .A(selectorL2),
    .B(inEtapaL2[5]),
    .Y(_222_)
  );
  NOR _545_ (
    .A(_008_[5]),
    .B(_013_),
    .Y(_223_)
  );
  NOR _546_ (
    .A(_222_),
    .B(_223_),
    .Y(_010_[5])
  );
  NOR _547_ (
    .A(selectorL2),
    .B(inEtapaL2[6]),
    .Y(_224_)
  );
  NOR _548_ (
    .A(_008_[6]),
    .B(_013_),
    .Y(_225_)
  );
  NOR _549_ (
    .A(_224_),
    .B(_225_),
    .Y(_010_[6])
  );
  NOR _550_ (
    .A(selectorL2),
    .B(inEtapaL2[7]),
    .Y(_226_)
  );
  NOR _551_ (
    .A(_008_[7]),
    .B(_013_),
    .Y(_227_)
  );
  NOR _552_ (
    .A(_226_),
    .B(_227_),
    .Y(_010_[7])
  );
  NOR _553_ (
    .A(selectorL2),
    .B(inEtapaL2[8]),
    .Y(_228_)
  );
  NOR _554_ (
    .A(_008_[8]),
    .B(_013_),
    .Y(_229_)
  );
  NOR _555_ (
    .A(_228_),
    .B(_229_),
    .Y(_010_[8])
  );
  NAND _556_ (
    .A(reset),
    .B(etapa1_inData3[0]),
    .Y(_230_)
  );
  NOT _557_ (
    .A(_230_),
    .Y(_003_[0])
  );
  (* src = "demuxEst.v:67" *)
  DFF _558_ (
    .C(clk_f),
    .D(_000_[0]),
    .Q(data0[0])
  );
  (* src = "demuxEst.v:67" *)
  DFF _559_ (
    .C(clk_f),
    .D(_000_[1]),
    .Q(data0[1])
  );
  (* src = "demuxEst.v:67" *)
  DFF _560_ (
    .C(clk_f),
    .D(_000_[2]),
    .Q(data0[2])
  );
  (* src = "demuxEst.v:67" *)
  DFF _561_ (
    .C(clk_f),
    .D(_000_[3]),
    .Q(data0[3])
  );
  (* src = "demuxEst.v:67" *)
  DFF _562_ (
    .C(clk_f),
    .D(_000_[4]),
    .Q(data0[4])
  );
  (* src = "demuxEst.v:67" *)
  DFF _563_ (
    .C(clk_f),
    .D(_000_[5]),
    .Q(data0[5])
  );
  (* src = "demuxEst.v:67" *)
  DFF _564_ (
    .C(clk_f),
    .D(_000_[6]),
    .Q(data0[6])
  );
  (* src = "demuxEst.v:67" *)
  DFF _565_ (
    .C(clk_f),
    .D(_000_[7]),
    .Q(data0[7])
  );
  (* src = "demuxEst.v:67" *)
  DFF _566_ (
    .C(clk_f),
    .D(_000_[8]),
    .Q(data0[8])
  );
  (* src = "demuxEst.v:67" *)
  DFF _567_ (
    .C(clk_f),
    .D(_001_[0]),
    .Q(data1[0])
  );
  (* src = "demuxEst.v:67" *)
  DFF _568_ (
    .C(clk_f),
    .D(_001_[1]),
    .Q(data1[1])
  );
  (* src = "demuxEst.v:67" *)
  DFF _569_ (
    .C(clk_f),
    .D(_001_[2]),
    .Q(data1[2])
  );
  (* src = "demuxEst.v:67" *)
  DFF _570_ (
    .C(clk_f),
    .D(_001_[3]),
    .Q(data1[3])
  );
  (* src = "demuxEst.v:67" *)
  DFF _571_ (
    .C(clk_f),
    .D(_001_[4]),
    .Q(data1[4])
  );
  (* src = "demuxEst.v:67" *)
  DFF _572_ (
    .C(clk_f),
    .D(_001_[5]),
    .Q(data1[5])
  );
  (* src = "demuxEst.v:67" *)
  DFF _573_ (
    .C(clk_f),
    .D(_001_[6]),
    .Q(data1[6])
  );
  (* src = "demuxEst.v:67" *)
  DFF _574_ (
    .C(clk_f),
    .D(_001_[7]),
    .Q(data1[7])
  );
  (* src = "demuxEst.v:67" *)
  DFF _575_ (
    .C(clk_f),
    .D(_001_[8]),
    .Q(data1[8])
  );
  (* src = "demuxEst.v:67" *)
  DFF _576_ (
    .C(clk_f),
    .D(_002_[0]),
    .Q(data2[0])
  );
  (* src = "demuxEst.v:67" *)
  DFF _577_ (
    .C(clk_f),
    .D(_002_[1]),
    .Q(data2[1])
  );
  (* src = "demuxEst.v:67" *)
  DFF _578_ (
    .C(clk_f),
    .D(_002_[2]),
    .Q(data2[2])
  );
  (* src = "demuxEst.v:67" *)
  DFF _579_ (
    .C(clk_f),
    .D(_002_[3]),
    .Q(data2[3])
  );
  (* src = "demuxEst.v:67" *)
  DFF _580_ (
    .C(clk_f),
    .D(_002_[4]),
    .Q(data2[4])
  );
  (* src = "demuxEst.v:67" *)
  DFF _581_ (
    .C(clk_f),
    .D(_002_[5]),
    .Q(data2[5])
  );
  (* src = "demuxEst.v:67" *)
  DFF _582_ (
    .C(clk_f),
    .D(_002_[6]),
    .Q(data2[6])
  );
  (* src = "demuxEst.v:67" *)
  DFF _583_ (
    .C(clk_f),
    .D(_002_[7]),
    .Q(data2[7])
  );
  (* src = "demuxEst.v:67" *)
  DFF _584_ (
    .C(clk_f),
    .D(_002_[8]),
    .Q(data2[8])
  );
  (* src = "demuxEst.v:67" *)
  DFF _585_ (
    .C(clk_f),
    .D(_003_[0]),
    .Q(data3[0])
  );
  (* src = "demuxEst.v:67" *)
  DFF _586_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(data3[1])
  );
  (* src = "demuxEst.v:67" *)
  DFF _587_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(data3[2])
  );
  (* src = "demuxEst.v:67" *)
  DFF _588_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(data3[3])
  );
  (* src = "demuxEst.v:67" *)
  DFF _589_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(data3[4])
  );
  (* src = "demuxEst.v:67" *)
  DFF _590_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(data3[5])
  );
  (* src = "demuxEst.v:67" *)
  DFF _591_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(data3[6])
  );
  (* src = "demuxEst.v:67" *)
  DFF _592_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(data3[7])
  );
  (* src = "demuxEst.v:67" *)
  DFF _593_ (
    .C(clk_f),
    .D(_003_[8]),
    .Q(data3[8])
  );
  (* src = "demuxEst.v:36" *)
  DFF _594_ (
    .C(clk_2f),
    .D(_012_),
    .Q(selectorL1)
  );
  (* src = "demuxEst.v:36" *)
  DFF _595_ (
    .C(clk_2f),
    .D(_004_[0]),
    .Q(etapa1_inData0[0])
  );
  (* src = "demuxEst.v:36" *)
  DFF _596_ (
    .C(clk_2f),
    .D(_004_[1]),
    .Q(etapa1_inData0[1])
  );
  (* src = "demuxEst.v:36" *)
  DFF _597_ (
    .C(clk_2f),
    .D(_004_[2]),
    .Q(etapa1_inData0[2])
  );
  (* src = "demuxEst.v:36" *)
  DFF _598_ (
    .C(clk_2f),
    .D(_004_[3]),
    .Q(etapa1_inData0[3])
  );
  (* src = "demuxEst.v:36" *)
  DFF _599_ (
    .C(clk_2f),
    .D(_004_[4]),
    .Q(etapa1_inData0[4])
  );
  (* src = "demuxEst.v:36" *)
  DFF _600_ (
    .C(clk_2f),
    .D(_004_[5]),
    .Q(etapa1_inData0[5])
  );
  (* src = "demuxEst.v:36" *)
  DFF _601_ (
    .C(clk_2f),
    .D(_004_[6]),
    .Q(etapa1_inData0[6])
  );
  (* src = "demuxEst.v:36" *)
  DFF _602_ (
    .C(clk_2f),
    .D(_004_[7]),
    .Q(etapa1_inData0[7])
  );
  (* src = "demuxEst.v:36" *)
  DFF _603_ (
    .C(clk_2f),
    .D(_004_[8]),
    .Q(etapa1_inData0[8])
  );
  (* src = "demuxEst.v:36" *)
  DFF _604_ (
    .C(clk_2f),
    .D(_005_[0]),
    .Q(etapa1_inData1[0])
  );
  (* src = "demuxEst.v:36" *)
  DFF _605_ (
    .C(clk_2f),
    .D(_005_[1]),
    .Q(etapa1_inData1[1])
  );
  (* src = "demuxEst.v:36" *)
  DFF _606_ (
    .C(clk_2f),
    .D(_005_[2]),
    .Q(etapa1_inData1[2])
  );
  (* src = "demuxEst.v:36" *)
  DFF _607_ (
    .C(clk_2f),
    .D(_005_[3]),
    .Q(etapa1_inData1[3])
  );
  (* src = "demuxEst.v:36" *)
  DFF _608_ (
    .C(clk_2f),
    .D(_005_[4]),
    .Q(etapa1_inData1[4])
  );
  (* src = "demuxEst.v:36" *)
  DFF _609_ (
    .C(clk_2f),
    .D(_005_[5]),
    .Q(etapa1_inData1[5])
  );
  (* src = "demuxEst.v:36" *)
  DFF _610_ (
    .C(clk_2f),
    .D(_005_[6]),
    .Q(etapa1_inData1[6])
  );
  (* src = "demuxEst.v:36" *)
  DFF _611_ (
    .C(clk_2f),
    .D(_005_[7]),
    .Q(etapa1_inData1[7])
  );
  (* src = "demuxEst.v:36" *)
  DFF _612_ (
    .C(clk_2f),
    .D(_005_[8]),
    .Q(etapa1_inData1[8])
  );
  (* src = "demuxEst.v:36" *)
  DFF _613_ (
    .C(clk_2f),
    .D(_006_[0]),
    .Q(etapa1_inData2[0])
  );
  (* src = "demuxEst.v:36" *)
  DFF _614_ (
    .C(clk_2f),
    .D(_006_[1]),
    .Q(etapa1_inData2[1])
  );
  (* src = "demuxEst.v:36" *)
  DFF _615_ (
    .C(clk_2f),
    .D(_006_[2]),
    .Q(etapa1_inData2[2])
  );
  (* src = "demuxEst.v:36" *)
  DFF _616_ (
    .C(clk_2f),
    .D(_006_[3]),
    .Q(etapa1_inData2[3])
  );
  (* src = "demuxEst.v:36" *)
  DFF _617_ (
    .C(clk_2f),
    .D(_006_[4]),
    .Q(etapa1_inData2[4])
  );
  (* src = "demuxEst.v:36" *)
  DFF _618_ (
    .C(clk_2f),
    .D(_006_[5]),
    .Q(etapa1_inData2[5])
  );
  (* src = "demuxEst.v:36" *)
  DFF _619_ (
    .C(clk_2f),
    .D(_006_[6]),
    .Q(etapa1_inData2[6])
  );
  (* src = "demuxEst.v:36" *)
  DFF _620_ (
    .C(clk_2f),
    .D(_006_[7]),
    .Q(etapa1_inData2[7])
  );
  (* src = "demuxEst.v:36" *)
  DFF _621_ (
    .C(clk_2f),
    .D(_006_[8]),
    .Q(etapa1_inData2[8])
  );
  (* src = "demuxEst.v:36" *)
  DFF _622_ (
    .C(clk_2f),
    .D(_007_[0]),
    .Q(etapa1_inData3[0])
  );
  (* src = "demuxEst.v:36" *)
  DFF _623_ (
    .C(clk_2f),
    .D(_007_[1]),
    .Q(etapa1_inData3[1])
  );
  (* src = "demuxEst.v:36" *)
  DFF _624_ (
    .C(clk_2f),
    .D(_007_[2]),
    .Q(etapa1_inData3[2])
  );
  (* src = "demuxEst.v:36" *)
  DFF _625_ (
    .C(clk_2f),
    .D(_007_[3]),
    .Q(etapa1_inData3[3])
  );
  (* src = "demuxEst.v:36" *)
  DFF _626_ (
    .C(clk_2f),
    .D(_007_[4]),
    .Q(etapa1_inData3[4])
  );
  (* src = "demuxEst.v:36" *)
  DFF _627_ (
    .C(clk_2f),
    .D(_007_[5]),
    .Q(etapa1_inData3[5])
  );
  (* src = "demuxEst.v:36" *)
  DFF _628_ (
    .C(clk_2f),
    .D(_007_[6]),
    .Q(etapa1_inData3[6])
  );
  (* src = "demuxEst.v:36" *)
  DFF _629_ (
    .C(clk_2f),
    .D(_007_[7]),
    .Q(etapa1_inData3[7])
  );
  (* src = "demuxEst.v:36" *)
  DFF _630_ (
    .C(clk_2f),
    .D(_007_[8]),
    .Q(etapa1_inData3[8])
  );
  (* src = "demuxEst.v:36" *)
  DFF _631_ (
    .C(clk_2f),
    .D(_008_[0]),
    .Q(etapa2_inData0[0])
  );
  (* src = "demuxEst.v:36" *)
  DFF _632_ (
    .C(clk_2f),
    .D(_008_[1]),
    .Q(etapa2_inData0[1])
  );
  (* src = "demuxEst.v:36" *)
  DFF _633_ (
    .C(clk_2f),
    .D(_008_[2]),
    .Q(etapa2_inData0[2])
  );
  (* src = "demuxEst.v:36" *)
  DFF _634_ (
    .C(clk_2f),
    .D(_008_[3]),
    .Q(etapa2_inData0[3])
  );
  (* src = "demuxEst.v:36" *)
  DFF _635_ (
    .C(clk_2f),
    .D(_008_[4]),
    .Q(etapa2_inData0[4])
  );
  (* src = "demuxEst.v:36" *)
  DFF _636_ (
    .C(clk_2f),
    .D(_008_[5]),
    .Q(etapa2_inData0[5])
  );
  (* src = "demuxEst.v:36" *)
  DFF _637_ (
    .C(clk_2f),
    .D(_008_[6]),
    .Q(etapa2_inData0[6])
  );
  (* src = "demuxEst.v:36" *)
  DFF _638_ (
    .C(clk_2f),
    .D(_008_[7]),
    .Q(etapa2_inData0[7])
  );
  (* src = "demuxEst.v:36" *)
  DFF _639_ (
    .C(clk_2f),
    .D(_008_[8]),
    .Q(etapa2_inData0[8])
  );
  (* src = "demuxEst.v:36" *)
  DFF _640_ (
    .C(clk_2f),
    .D(_009_[0]),
    .Q(etapa2_inData1[0])
  );
  (* src = "demuxEst.v:36" *)
  DFF _641_ (
    .C(clk_2f),
    .D(_009_[1]),
    .Q(etapa2_inData1[1])
  );
  (* src = "demuxEst.v:36" *)
  DFF _642_ (
    .C(clk_2f),
    .D(_009_[2]),
    .Q(etapa2_inData1[2])
  );
  (* src = "demuxEst.v:36" *)
  DFF _643_ (
    .C(clk_2f),
    .D(_009_[3]),
    .Q(etapa2_inData1[3])
  );
  (* src = "demuxEst.v:36" *)
  DFF _644_ (
    .C(clk_2f),
    .D(_009_[4]),
    .Q(etapa2_inData1[4])
  );
  (* src = "demuxEst.v:36" *)
  DFF _645_ (
    .C(clk_2f),
    .D(_009_[5]),
    .Q(etapa2_inData1[5])
  );
  (* src = "demuxEst.v:36" *)
  DFF _646_ (
    .C(clk_2f),
    .D(_009_[6]),
    .Q(etapa2_inData1[6])
  );
  (* src = "demuxEst.v:36" *)
  DFF _647_ (
    .C(clk_2f),
    .D(_009_[7]),
    .Q(etapa2_inData1[7])
  );
  (* src = "demuxEst.v:36" *)
  DFF _648_ (
    .C(clk_2f),
    .D(_009_[8]),
    .Q(etapa2_inData1[8])
  );
  (* src = "demuxEst.v:18" *)
  DFF _649_ (
    .C(clk_4f),
    .D(_010_[0]),
    .Q(outEtapaL1L2_0[0])
  );
  (* src = "demuxEst.v:18" *)
  DFF _650_ (
    .C(clk_4f),
    .D(_010_[1]),
    .Q(outEtapaL1L2_0[1])
  );
  (* src = "demuxEst.v:18" *)
  DFF _651_ (
    .C(clk_4f),
    .D(_010_[2]),
    .Q(outEtapaL1L2_0[2])
  );
  (* src = "demuxEst.v:18" *)
  DFF _652_ (
    .C(clk_4f),
    .D(_010_[3]),
    .Q(outEtapaL1L2_0[3])
  );
  (* src = "demuxEst.v:18" *)
  DFF _653_ (
    .C(clk_4f),
    .D(_010_[4]),
    .Q(outEtapaL1L2_0[4])
  );
  (* src = "demuxEst.v:18" *)
  DFF _654_ (
    .C(clk_4f),
    .D(_010_[5]),
    .Q(outEtapaL1L2_0[5])
  );
  (* src = "demuxEst.v:18" *)
  DFF _655_ (
    .C(clk_4f),
    .D(_010_[6]),
    .Q(outEtapaL1L2_0[6])
  );
  (* src = "demuxEst.v:18" *)
  DFF _656_ (
    .C(clk_4f),
    .D(_010_[7]),
    .Q(outEtapaL1L2_0[7])
  );
  (* src = "demuxEst.v:18" *)
  DFF _657_ (
    .C(clk_4f),
    .D(_010_[8]),
    .Q(outEtapaL1L2_0[8])
  );
  (* src = "demuxEst.v:18" *)
  DFF _658_ (
    .C(clk_4f),
    .D(_011_[0]),
    .Q(outEtapaL1L2_1[0])
  );
  (* src = "demuxEst.v:18" *)
  DFF _659_ (
    .C(clk_4f),
    .D(_011_[1]),
    .Q(outEtapaL1L2_1[1])
  );
  (* src = "demuxEst.v:18" *)
  DFF _660_ (
    .C(clk_4f),
    .D(_011_[2]),
    .Q(outEtapaL1L2_1[2])
  );
  (* src = "demuxEst.v:18" *)
  DFF _661_ (
    .C(clk_4f),
    .D(_011_[3]),
    .Q(outEtapaL1L2_1[3])
  );
  (* src = "demuxEst.v:18" *)
  DFF _662_ (
    .C(clk_4f),
    .D(_011_[4]),
    .Q(outEtapaL1L2_1[4])
  );
  (* src = "demuxEst.v:18" *)
  DFF _663_ (
    .C(clk_4f),
    .D(_011_[5]),
    .Q(outEtapaL1L2_1[5])
  );
  (* src = "demuxEst.v:18" *)
  DFF _664_ (
    .C(clk_4f),
    .D(_011_[6]),
    .Q(outEtapaL1L2_1[6])
  );
  (* src = "demuxEst.v:18" *)
  DFF _665_ (
    .C(clk_4f),
    .D(_011_[7]),
    .Q(outEtapaL1L2_1[7])
  );
  (* src = "demuxEst.v:18" *)
  DFF _666_ (
    .C(clk_4f),
    .D(_011_[8]),
    .Q(outEtapaL1L2_1[8])
  );
  (* src = "demuxEst.v:18" *)
  DFF _667_ (
    .C(clk_4f),
    .D(_013_),
    .Q(selectorL2)
  );
endmodule

(* src = "muxesEst.v:1" *)
module muxesEst(clk_f, clk_2f, clk_4f, reset, data0, data1, data2, data3, outEtapaL2);
  (* src = "muxesEst.v:18" *)
  wire [8:0] _000_;
  (* src = "muxesEst.v:18" *)
  wire [8:0] _001_;
  (* src = "muxesEst.v:18" *)
  wire [8:0] _002_;
  (* src = "muxesEst.v:18" *)
  wire [8:0] _003_;
  (* src = "muxesEst.v:35" *)
  wire [8:0] _004_;
  (* src = "muxesEst.v:35" *)
  wire [8:0] _005_;
  (* src = "muxesEst.v:49" *)
  wire [8:0] _006_;
  (* src = "muxesEst.v:35" *)
  wire _007_;
  (* src = "muxesEst.v:49" *)
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  (* src = "muxesEst.v:3" *)
  input clk_2f;
  (* src = "muxesEst.v:4" *)
  input clk_4f;
  (* src = "muxesEst.v:2" *)
  input clk_f;
  (* src = "muxesEst.v:6" *)
  input [8:0] data0;
  (* src = "muxesEst.v:7" *)
  input [8:0] data1;
  (* src = "muxesEst.v:8" *)
  input [8:0] data2;
  (* src = "muxesEst.v:9" *)
  input [8:0] data3;
  (* src = "muxesEst.v:15" *)
  wire [8:0] etapa1_preData0;
  (* src = "muxesEst.v:15" *)
  wire [8:0] etapa1_preData1;
  (* src = "muxesEst.v:15" *)
  wire [8:0] etapa1_preData2;
  (* src = "muxesEst.v:15" *)
  wire [8:0] etapa1_preData3;
  (* src = "muxesEst.v:16" *)
  wire [8:0] etapa2_preData0;
  (* src = "muxesEst.v:16" *)
  wire [8:0] etapa2_preData1;
  (* src = "muxesEst.v:10" *)
  output [8:0] outEtapaL2;
  (* src = "muxesEst.v:5" *)
  input reset;
  (* src = "muxesEst.v:14" *)
  wire selectorL1;
  (* src = "muxesEst.v:14" *)
  wire selectorL2;
  NOT _250_ (
    .A(data0[1]),
    .Y(_009_)
  );
  NOT _251_ (
    .A(data0[2]),
    .Y(_010_)
  );
  NOT _252_ (
    .A(data0[3]),
    .Y(_011_)
  );
  NOT _253_ (
    .A(data0[4]),
    .Y(_012_)
  );
  NOT _254_ (
    .A(data0[5]),
    .Y(_013_)
  );
  NOT _255_ (
    .A(data0[6]),
    .Y(_014_)
  );
  NOT _256_ (
    .A(data0[7]),
    .Y(_015_)
  );
  NOT _257_ (
    .A(etapa1_preData1[0]),
    .Y(_016_)
  );
  NOT _258_ (
    .A(data1[0]),
    .Y(_017_)
  );
  NOT _259_ (
    .A(etapa1_preData1[1]),
    .Y(_018_)
  );
  NOT _260_ (
    .A(data1[1]),
    .Y(_019_)
  );
  NOT _261_ (
    .A(etapa1_preData1[2]),
    .Y(_020_)
  );
  NOT _262_ (
    .A(data1[2]),
    .Y(_021_)
  );
  NOT _263_ (
    .A(etapa1_preData1[3]),
    .Y(_022_)
  );
  NOT _264_ (
    .A(data1[3]),
    .Y(_023_)
  );
  NOT _265_ (
    .A(etapa1_preData1[4]),
    .Y(_024_)
  );
  NOT _266_ (
    .A(data1[4]),
    .Y(_025_)
  );
  NOT _267_ (
    .A(etapa1_preData1[5]),
    .Y(_026_)
  );
  NOT _268_ (
    .A(data1[5]),
    .Y(_027_)
  );
  NOT _269_ (
    .A(etapa1_preData1[6]),
    .Y(_028_)
  );
  NOT _270_ (
    .A(data1[6]),
    .Y(_029_)
  );
  NOT _271_ (
    .A(etapa1_preData1[7]),
    .Y(_030_)
  );
  NOT _272_ (
    .A(data1[7]),
    .Y(_031_)
  );
  NOT _273_ (
    .A(data2[0]),
    .Y(_032_)
  );
  NOT _274_ (
    .A(data2[1]),
    .Y(_033_)
  );
  NOT _275_ (
    .A(data2[2]),
    .Y(_034_)
  );
  NOT _276_ (
    .A(data2[3]),
    .Y(_035_)
  );
  NOT _277_ (
    .A(data2[4]),
    .Y(_036_)
  );
  NOT _278_ (
    .A(data2[5]),
    .Y(_037_)
  );
  NOT _279_ (
    .A(data2[6]),
    .Y(_038_)
  );
  NOT _280_ (
    .A(data2[7]),
    .Y(_039_)
  );
  NOT _281_ (
    .A(etapa1_preData3[0]),
    .Y(_040_)
  );
  NOT _282_ (
    .A(data3[0]),
    .Y(_041_)
  );
  NOT _283_ (
    .A(etapa1_preData3[1]),
    .Y(_042_)
  );
  NOT _284_ (
    .A(data3[1]),
    .Y(_043_)
  );
  NOT _285_ (
    .A(etapa1_preData3[2]),
    .Y(_044_)
  );
  NOT _286_ (
    .A(data3[2]),
    .Y(_045_)
  );
  NOT _287_ (
    .A(etapa1_preData3[3]),
    .Y(_046_)
  );
  NOT _288_ (
    .A(data3[3]),
    .Y(_047_)
  );
  NOT _289_ (
    .A(etapa1_preData3[4]),
    .Y(_048_)
  );
  NOT _290_ (
    .A(data3[4]),
    .Y(_049_)
  );
  NOT _291_ (
    .A(etapa1_preData3[5]),
    .Y(_050_)
  );
  NOT _292_ (
    .A(data3[5]),
    .Y(_051_)
  );
  NOT _293_ (
    .A(etapa1_preData3[6]),
    .Y(_052_)
  );
  NOT _294_ (
    .A(data3[6]),
    .Y(_053_)
  );
  NOT _295_ (
    .A(etapa1_preData3[7]),
    .Y(_054_)
  );
  NOT _296_ (
    .A(data3[7]),
    .Y(_055_)
  );
  NOT _297_ (
    .A(etapa1_preData3[8]),
    .Y(_056_)
  );
  NOT _298_ (
    .A(etapa1_preData1[8]),
    .Y(_057_)
  );
  NOT _299_ (
    .A(etapa2_preData1[0]),
    .Y(_058_)
  );
  NOT _300_ (
    .A(etapa2_preData1[1]),
    .Y(_059_)
  );
  NOT _301_ (
    .A(etapa2_preData1[2]),
    .Y(_060_)
  );
  NOT _302_ (
    .A(etapa2_preData1[3]),
    .Y(_061_)
  );
  NOT _303_ (
    .A(etapa2_preData1[4]),
    .Y(_062_)
  );
  NOT _304_ (
    .A(etapa2_preData1[5]),
    .Y(_063_)
  );
  NOT _305_ (
    .A(etapa2_preData1[6]),
    .Y(_064_)
  );
  NOT _306_ (
    .A(etapa2_preData1[7]),
    .Y(_065_)
  );
  NOT _307_ (
    .A(etapa2_preData1[8]),
    .Y(_066_)
  );
  NOT _308_ (
    .A(reset),
    .Y(_067_)
  );
  NOT _309_ (
    .A(data0[0]),
    .Y(_068_)
  );
  NOR _310_ (
    .A(etapa2_preData0[0]),
    .B(selectorL2),
    .Y(_069_)
  );
  NOR _311_ (
    .A(selectorL2),
    .B(_067_),
    .Y(_008_)
  );
  NAND _312_ (
    .A(_058_),
    .B(selectorL2),
    .Y(_070_)
  );
  NAND _313_ (
    .A(reset),
    .B(_070_),
    .Y(_071_)
  );
  NOR _314_ (
    .A(_069_),
    .B(_071_),
    .Y(_006_[0])
  );
  NOR _315_ (
    .A(selectorL2),
    .B(etapa2_preData0[1]),
    .Y(_072_)
  );
  NAND _316_ (
    .A(selectorL2),
    .B(_059_),
    .Y(_073_)
  );
  NAND _317_ (
    .A(reset),
    .B(_073_),
    .Y(_074_)
  );
  NOR _318_ (
    .A(_072_),
    .B(_074_),
    .Y(_006_[1])
  );
  NOR _319_ (
    .A(selectorL2),
    .B(etapa2_preData0[2]),
    .Y(_075_)
  );
  NAND _320_ (
    .A(selectorL2),
    .B(_060_),
    .Y(_076_)
  );
  NAND _321_ (
    .A(reset),
    .B(_076_),
    .Y(_077_)
  );
  NOR _322_ (
    .A(_075_),
    .B(_077_),
    .Y(_006_[2])
  );
  NOR _323_ (
    .A(selectorL2),
    .B(etapa2_preData0[3]),
    .Y(_078_)
  );
  NAND _324_ (
    .A(selectorL2),
    .B(_061_),
    .Y(_079_)
  );
  NAND _325_ (
    .A(reset),
    .B(_079_),
    .Y(_080_)
  );
  NOR _326_ (
    .A(_078_),
    .B(_080_),
    .Y(_006_[3])
  );
  NOR _327_ (
    .A(selectorL2),
    .B(etapa2_preData0[4]),
    .Y(_081_)
  );
  NAND _328_ (
    .A(selectorL2),
    .B(_062_),
    .Y(_082_)
  );
  NAND _329_ (
    .A(reset),
    .B(_082_),
    .Y(_083_)
  );
  NOR _330_ (
    .A(_081_),
    .B(_083_),
    .Y(_006_[4])
  );
  NOR _331_ (
    .A(selectorL2),
    .B(etapa2_preData0[5]),
    .Y(_084_)
  );
  NAND _332_ (
    .A(selectorL2),
    .B(_063_),
    .Y(_085_)
  );
  NAND _333_ (
    .A(reset),
    .B(_085_),
    .Y(_086_)
  );
  NOR _334_ (
    .A(_084_),
    .B(_086_),
    .Y(_006_[5])
  );
  NOR _335_ (
    .A(selectorL2),
    .B(etapa2_preData0[6]),
    .Y(_087_)
  );
  NAND _336_ (
    .A(selectorL2),
    .B(_064_),
    .Y(_088_)
  );
  NAND _337_ (
    .A(reset),
    .B(_088_),
    .Y(_089_)
  );
  NOR _338_ (
    .A(_087_),
    .B(_089_),
    .Y(_006_[6])
  );
  NOR _339_ (
    .A(selectorL2),
    .B(etapa2_preData0[7]),
    .Y(_090_)
  );
  NAND _340_ (
    .A(selectorL2),
    .B(_065_),
    .Y(_091_)
  );
  NAND _341_ (
    .A(reset),
    .B(_091_),
    .Y(_092_)
  );
  NOR _342_ (
    .A(_090_),
    .B(_092_),
    .Y(_006_[7])
  );
  NOR _343_ (
    .A(selectorL2),
    .B(etapa2_preData0[8]),
    .Y(_093_)
  );
  NAND _344_ (
    .A(selectorL2),
    .B(_066_),
    .Y(_094_)
  );
  NAND _345_ (
    .A(reset),
    .B(_094_),
    .Y(_095_)
  );
  NOR _346_ (
    .A(_093_),
    .B(_095_),
    .Y(_006_[8])
  );
  NOR _347_ (
    .A(etapa1_preData2[0]),
    .B(selectorL1),
    .Y(_096_)
  );
  NAND _348_ (
    .A(_040_),
    .B(selectorL1),
    .Y(_097_)
  );
  NAND _349_ (
    .A(reset),
    .B(_097_),
    .Y(_098_)
  );
  NOR _350_ (
    .A(_096_),
    .B(_098_),
    .Y(_005_[0])
  );
  NOR _351_ (
    .A(etapa1_preData2[1]),
    .B(selectorL1),
    .Y(_099_)
  );
  NAND _352_ (
    .A(_042_),
    .B(selectorL1),
    .Y(_100_)
  );
  NAND _353_ (
    .A(reset),
    .B(_100_),
    .Y(_101_)
  );
  NOR _354_ (
    .A(_099_),
    .B(_101_),
    .Y(_005_[1])
  );
  NOR _355_ (
    .A(etapa1_preData2[2]),
    .B(selectorL1),
    .Y(_102_)
  );
  NAND _356_ (
    .A(_044_),
    .B(selectorL1),
    .Y(_103_)
  );
  NAND _357_ (
    .A(reset),
    .B(_103_),
    .Y(_104_)
  );
  NOR _358_ (
    .A(_102_),
    .B(_104_),
    .Y(_005_[2])
  );
  NOR _359_ (
    .A(etapa1_preData2[3]),
    .B(selectorL1),
    .Y(_105_)
  );
  NAND _360_ (
    .A(_046_),
    .B(selectorL1),
    .Y(_106_)
  );
  NAND _361_ (
    .A(reset),
    .B(_106_),
    .Y(_107_)
  );
  NOR _362_ (
    .A(_105_),
    .B(_107_),
    .Y(_005_[3])
  );
  NOR _363_ (
    .A(etapa1_preData2[4]),
    .B(selectorL1),
    .Y(_108_)
  );
  NAND _364_ (
    .A(_048_),
    .B(selectorL1),
    .Y(_109_)
  );
  NAND _365_ (
    .A(reset),
    .B(_109_),
    .Y(_110_)
  );
  NOR _366_ (
    .A(_108_),
    .B(_110_),
    .Y(_005_[4])
  );
  NOR _367_ (
    .A(etapa1_preData2[5]),
    .B(selectorL1),
    .Y(_111_)
  );
  NAND _368_ (
    .A(_050_),
    .B(selectorL1),
    .Y(_112_)
  );
  NAND _369_ (
    .A(reset),
    .B(_112_),
    .Y(_113_)
  );
  NOR _370_ (
    .A(_111_),
    .B(_113_),
    .Y(_005_[5])
  );
  NOR _371_ (
    .A(etapa1_preData2[6]),
    .B(selectorL1),
    .Y(_114_)
  );
  NAND _372_ (
    .A(_052_),
    .B(selectorL1),
    .Y(_115_)
  );
  NAND _373_ (
    .A(reset),
    .B(_115_),
    .Y(_116_)
  );
  NOR _374_ (
    .A(_114_),
    .B(_116_),
    .Y(_005_[6])
  );
  NOR _375_ (
    .A(etapa1_preData2[7]),
    .B(selectorL1),
    .Y(_117_)
  );
  NAND _376_ (
    .A(_054_),
    .B(selectorL1),
    .Y(_118_)
  );
  NAND _377_ (
    .A(reset),
    .B(_118_),
    .Y(_119_)
  );
  NOR _378_ (
    .A(_117_),
    .B(_119_),
    .Y(_005_[7])
  );
  NOR _379_ (
    .A(selectorL1),
    .B(etapa1_preData2[8]),
    .Y(_120_)
  );
  NAND _380_ (
    .A(selectorL1),
    .B(_056_),
    .Y(_121_)
  );
  NAND _381_ (
    .A(reset),
    .B(_121_),
    .Y(_122_)
  );
  NOR _382_ (
    .A(_120_),
    .B(_122_),
    .Y(_005_[8])
  );
  NOR _383_ (
    .A(selectorL1),
    .B(etapa1_preData0[0]),
    .Y(_123_)
  );
  NAND _384_ (
    .A(_016_),
    .B(selectorL1),
    .Y(_124_)
  );
  NAND _385_ (
    .A(reset),
    .B(_124_),
    .Y(_125_)
  );
  NOR _386_ (
    .A(_123_),
    .B(_125_),
    .Y(_004_[0])
  );
  NOR _387_ (
    .A(etapa1_preData0[1]),
    .B(selectorL1),
    .Y(_126_)
  );
  NAND _388_ (
    .A(_018_),
    .B(selectorL1),
    .Y(_127_)
  );
  NAND _389_ (
    .A(reset),
    .B(_127_),
    .Y(_128_)
  );
  NOR _390_ (
    .A(_126_),
    .B(_128_),
    .Y(_004_[1])
  );
  NOR _391_ (
    .A(etapa1_preData0[2]),
    .B(selectorL1),
    .Y(_129_)
  );
  NAND _392_ (
    .A(_020_),
    .B(selectorL1),
    .Y(_130_)
  );
  NAND _393_ (
    .A(reset),
    .B(_130_),
    .Y(_131_)
  );
  NOR _394_ (
    .A(_129_),
    .B(_131_),
    .Y(_004_[2])
  );
  NOR _395_ (
    .A(etapa1_preData0[3]),
    .B(selectorL1),
    .Y(_132_)
  );
  NAND _396_ (
    .A(_022_),
    .B(selectorL1),
    .Y(_133_)
  );
  NAND _397_ (
    .A(reset),
    .B(_133_),
    .Y(_134_)
  );
  NOR _398_ (
    .A(_132_),
    .B(_134_),
    .Y(_004_[3])
  );
  NOR _399_ (
    .A(etapa1_preData0[4]),
    .B(selectorL1),
    .Y(_135_)
  );
  NAND _400_ (
    .A(_024_),
    .B(selectorL1),
    .Y(_136_)
  );
  NAND _401_ (
    .A(reset),
    .B(_136_),
    .Y(_137_)
  );
  NOR _402_ (
    .A(_135_),
    .B(_137_),
    .Y(_004_[4])
  );
  NOR _403_ (
    .A(etapa1_preData0[5]),
    .B(selectorL1),
    .Y(_138_)
  );
  NAND _404_ (
    .A(_026_),
    .B(selectorL1),
    .Y(_139_)
  );
  NAND _405_ (
    .A(reset),
    .B(_139_),
    .Y(_140_)
  );
  NOR _406_ (
    .A(_138_),
    .B(_140_),
    .Y(_004_[5])
  );
  NOR _407_ (
    .A(etapa1_preData0[6]),
    .B(selectorL1),
    .Y(_141_)
  );
  NAND _408_ (
    .A(_028_),
    .B(selectorL1),
    .Y(_142_)
  );
  NAND _409_ (
    .A(reset),
    .B(_142_),
    .Y(_143_)
  );
  NOR _410_ (
    .A(_141_),
    .B(_143_),
    .Y(_004_[6])
  );
  NOR _411_ (
    .A(etapa1_preData0[7]),
    .B(selectorL1),
    .Y(_144_)
  );
  NAND _412_ (
    .A(_030_),
    .B(selectorL1),
    .Y(_145_)
  );
  NAND _413_ (
    .A(reset),
    .B(_145_),
    .Y(_146_)
  );
  NOR _414_ (
    .A(_144_),
    .B(_146_),
    .Y(_004_[7])
  );
  NOR _415_ (
    .A(selectorL1),
    .B(etapa1_preData0[8]),
    .Y(_147_)
  );
  NAND _416_ (
    .A(selectorL1),
    .B(_057_),
    .Y(_148_)
  );
  NAND _417_ (
    .A(reset),
    .B(_148_),
    .Y(_149_)
  );
  NOR _418_ (
    .A(_147_),
    .B(_149_),
    .Y(_004_[8])
  );
  NOR _419_ (
    .A(selectorL1),
    .B(_067_),
    .Y(_007_)
  );
  NAND _420_ (
    .A(_041_),
    .B(data3[8]),
    .Y(_150_)
  );
  NAND _421_ (
    .A(reset),
    .B(_150_),
    .Y(_151_)
  );
  NOR _422_ (
    .A(etapa1_preData3[0]),
    .B(data3[8]),
    .Y(_152_)
  );
  NOR _423_ (
    .A(_151_),
    .B(_152_),
    .Y(_003_[0])
  );
  NAND _424_ (
    .A(data3[8]),
    .B(_043_),
    .Y(_153_)
  );
  NAND _425_ (
    .A(reset),
    .B(_153_),
    .Y(_154_)
  );
  NOR _426_ (
    .A(data3[8]),
    .B(etapa1_preData3[1]),
    .Y(_155_)
  );
  NOR _427_ (
    .A(_154_),
    .B(_155_),
    .Y(_003_[1])
  );
  NAND _428_ (
    .A(data3[8]),
    .B(_045_),
    .Y(_156_)
  );
  NAND _429_ (
    .A(reset),
    .B(_156_),
    .Y(_157_)
  );
  NOR _430_ (
    .A(data3[8]),
    .B(etapa1_preData3[2]),
    .Y(_158_)
  );
  NOR _431_ (
    .A(_157_),
    .B(_158_),
    .Y(_003_[2])
  );
  NAND _432_ (
    .A(data3[8]),
    .B(_047_),
    .Y(_159_)
  );
  NAND _433_ (
    .A(reset),
    .B(_159_),
    .Y(_160_)
  );
  NOR _434_ (
    .A(data3[8]),
    .B(etapa1_preData3[3]),
    .Y(_161_)
  );
  NOR _435_ (
    .A(_160_),
    .B(_161_),
    .Y(_003_[3])
  );
  NAND _436_ (
    .A(data3[8]),
    .B(_049_),
    .Y(_162_)
  );
  NAND _437_ (
    .A(reset),
    .B(_162_),
    .Y(_163_)
  );
  NOR _438_ (
    .A(data3[8]),
    .B(etapa1_preData3[4]),
    .Y(_164_)
  );
  NOR _439_ (
    .A(_163_),
    .B(_164_),
    .Y(_003_[4])
  );
  NAND _440_ (
    .A(data3[8]),
    .B(_051_),
    .Y(_165_)
  );
  NAND _441_ (
    .A(reset),
    .B(_165_),
    .Y(_166_)
  );
  NOR _442_ (
    .A(data3[8]),
    .B(etapa1_preData3[5]),
    .Y(_167_)
  );
  NOR _443_ (
    .A(_166_),
    .B(_167_),
    .Y(_003_[5])
  );
  NAND _444_ (
    .A(data3[8]),
    .B(_053_),
    .Y(_168_)
  );
  NAND _445_ (
    .A(reset),
    .B(_168_),
    .Y(_169_)
  );
  NOR _446_ (
    .A(data3[8]),
    .B(etapa1_preData3[6]),
    .Y(_170_)
  );
  NOR _447_ (
    .A(_169_),
    .B(_170_),
    .Y(_003_[6])
  );
  NAND _448_ (
    .A(data3[8]),
    .B(_055_),
    .Y(_171_)
  );
  NAND _449_ (
    .A(reset),
    .B(_171_),
    .Y(_172_)
  );
  NOR _450_ (
    .A(data3[8]),
    .B(etapa1_preData3[7]),
    .Y(_173_)
  );
  NOR _451_ (
    .A(_172_),
    .B(_173_),
    .Y(_003_[7])
  );
  NAND _452_ (
    .A(data3[8]),
    .B(reset),
    .Y(_174_)
  );
  NOT _453_ (
    .A(_174_),
    .Y(_003_[8])
  );
  NAND _454_ (
    .A(_032_),
    .B(data2[8]),
    .Y(_175_)
  );
  NAND _455_ (
    .A(reset),
    .B(_175_),
    .Y(_176_)
  );
  NOR _456_ (
    .A(etapa1_preData2[0]),
    .B(data2[8]),
    .Y(_177_)
  );
  NOR _457_ (
    .A(_176_),
    .B(_177_),
    .Y(_002_[0])
  );
  NAND _458_ (
    .A(data2[8]),
    .B(_033_),
    .Y(_178_)
  );
  NAND _459_ (
    .A(reset),
    .B(_178_),
    .Y(_179_)
  );
  NOR _460_ (
    .A(data2[8]),
    .B(etapa1_preData2[1]),
    .Y(_180_)
  );
  NOR _461_ (
    .A(_179_),
    .B(_180_),
    .Y(_002_[1])
  );
  NAND _462_ (
    .A(data2[8]),
    .B(_034_),
    .Y(_181_)
  );
  NAND _463_ (
    .A(reset),
    .B(_181_),
    .Y(_182_)
  );
  NOR _464_ (
    .A(data2[8]),
    .B(etapa1_preData2[2]),
    .Y(_183_)
  );
  NOR _465_ (
    .A(_182_),
    .B(_183_),
    .Y(_002_[2])
  );
  NAND _466_ (
    .A(data2[8]),
    .B(_035_),
    .Y(_184_)
  );
  NAND _467_ (
    .A(reset),
    .B(_184_),
    .Y(_185_)
  );
  NOR _468_ (
    .A(data2[8]),
    .B(etapa1_preData2[3]),
    .Y(_186_)
  );
  NOR _469_ (
    .A(_185_),
    .B(_186_),
    .Y(_002_[3])
  );
  NAND _470_ (
    .A(data2[8]),
    .B(_036_),
    .Y(_187_)
  );
  NAND _471_ (
    .A(reset),
    .B(_187_),
    .Y(_188_)
  );
  NOR _472_ (
    .A(data2[8]),
    .B(etapa1_preData2[4]),
    .Y(_189_)
  );
  NOR _473_ (
    .A(_188_),
    .B(_189_),
    .Y(_002_[4])
  );
  NAND _474_ (
    .A(data2[8]),
    .B(_037_),
    .Y(_190_)
  );
  NAND _475_ (
    .A(reset),
    .B(_190_),
    .Y(_191_)
  );
  NOR _476_ (
    .A(data2[8]),
    .B(etapa1_preData2[5]),
    .Y(_192_)
  );
  NOR _477_ (
    .A(_191_),
    .B(_192_),
    .Y(_002_[5])
  );
  NAND _478_ (
    .A(data2[8]),
    .B(_038_),
    .Y(_193_)
  );
  NAND _479_ (
    .A(reset),
    .B(_193_),
    .Y(_194_)
  );
  NOR _480_ (
    .A(data2[8]),
    .B(etapa1_preData2[6]),
    .Y(_195_)
  );
  NOR _481_ (
    .A(_194_),
    .B(_195_),
    .Y(_002_[6])
  );
  NAND _482_ (
    .A(data2[8]),
    .B(_039_),
    .Y(_196_)
  );
  NAND _483_ (
    .A(reset),
    .B(_196_),
    .Y(_197_)
  );
  NOR _484_ (
    .A(data2[8]),
    .B(etapa1_preData2[7]),
    .Y(_198_)
  );
  NOR _485_ (
    .A(_197_),
    .B(_198_),
    .Y(_002_[7])
  );
  NAND _486_ (
    .A(data2[8]),
    .B(reset),
    .Y(_199_)
  );
  NOT _487_ (
    .A(_199_),
    .Y(_002_[8])
  );
  NAND _488_ (
    .A(_017_),
    .B(data1[8]),
    .Y(_200_)
  );
  NAND _489_ (
    .A(reset),
    .B(_200_),
    .Y(_201_)
  );
  NOR _490_ (
    .A(etapa1_preData1[0]),
    .B(data1[8]),
    .Y(_202_)
  );
  NOR _491_ (
    .A(_201_),
    .B(_202_),
    .Y(_001_[0])
  );
  NAND _492_ (
    .A(data1[8]),
    .B(_019_),
    .Y(_203_)
  );
  NAND _493_ (
    .A(reset),
    .B(_203_),
    .Y(_204_)
  );
  NOR _494_ (
    .A(data1[8]),
    .B(etapa1_preData1[1]),
    .Y(_205_)
  );
  NOR _495_ (
    .A(_204_),
    .B(_205_),
    .Y(_001_[1])
  );
  NAND _496_ (
    .A(data1[8]),
    .B(_021_),
    .Y(_206_)
  );
  NAND _497_ (
    .A(reset),
    .B(_206_),
    .Y(_207_)
  );
  NOR _498_ (
    .A(data1[8]),
    .B(etapa1_preData1[2]),
    .Y(_208_)
  );
  NOR _499_ (
    .A(_207_),
    .B(_208_),
    .Y(_001_[2])
  );
  NAND _500_ (
    .A(data1[8]),
    .B(_023_),
    .Y(_209_)
  );
  NAND _501_ (
    .A(reset),
    .B(_209_),
    .Y(_210_)
  );
  NOR _502_ (
    .A(data1[8]),
    .B(etapa1_preData1[3]),
    .Y(_211_)
  );
  NOR _503_ (
    .A(_210_),
    .B(_211_),
    .Y(_001_[3])
  );
  NAND _504_ (
    .A(data1[8]),
    .B(_025_),
    .Y(_212_)
  );
  NAND _505_ (
    .A(reset),
    .B(_212_),
    .Y(_213_)
  );
  NOR _506_ (
    .A(data1[8]),
    .B(etapa1_preData1[4]),
    .Y(_214_)
  );
  NOR _507_ (
    .A(_213_),
    .B(_214_),
    .Y(_001_[4])
  );
  NAND _508_ (
    .A(data1[8]),
    .B(_027_),
    .Y(_215_)
  );
  NAND _509_ (
    .A(reset),
    .B(_215_),
    .Y(_216_)
  );
  NOR _510_ (
    .A(data1[8]),
    .B(etapa1_preData1[5]),
    .Y(_217_)
  );
  NOR _511_ (
    .A(_216_),
    .B(_217_),
    .Y(_001_[5])
  );
  NAND _512_ (
    .A(data1[8]),
    .B(_029_),
    .Y(_218_)
  );
  NAND _513_ (
    .A(reset),
    .B(_218_),
    .Y(_219_)
  );
  NOR _514_ (
    .A(data1[8]),
    .B(etapa1_preData1[6]),
    .Y(_220_)
  );
  NOR _515_ (
    .A(_219_),
    .B(_220_),
    .Y(_001_[6])
  );
  NAND _516_ (
    .A(data1[8]),
    .B(_031_),
    .Y(_221_)
  );
  NAND _517_ (
    .A(reset),
    .B(_221_),
    .Y(_222_)
  );
  NOR _518_ (
    .A(data1[8]),
    .B(etapa1_preData1[7]),
    .Y(_223_)
  );
  NOR _519_ (
    .A(_222_),
    .B(_223_),
    .Y(_001_[7])
  );
  NAND _520_ (
    .A(data1[8]),
    .B(reset),
    .Y(_224_)
  );
  NOT _521_ (
    .A(_224_),
    .Y(_001_[8])
  );
  NAND _522_ (
    .A(data0[8]),
    .B(_068_),
    .Y(_225_)
  );
  NAND _523_ (
    .A(reset),
    .B(_225_),
    .Y(_226_)
  );
  NOR _524_ (
    .A(data0[8]),
    .B(etapa1_preData0[0]),
    .Y(_227_)
  );
  NOR _525_ (
    .A(_226_),
    .B(_227_),
    .Y(_000_[0])
  );
  NAND _526_ (
    .A(_009_),
    .B(data0[8]),
    .Y(_228_)
  );
  NAND _527_ (
    .A(reset),
    .B(_228_),
    .Y(_229_)
  );
  NOR _528_ (
    .A(etapa1_preData0[1]),
    .B(data0[8]),
    .Y(_230_)
  );
  NOR _529_ (
    .A(_229_),
    .B(_230_),
    .Y(_000_[1])
  );
  NAND _530_ (
    .A(data0[8]),
    .B(_010_),
    .Y(_231_)
  );
  NAND _531_ (
    .A(reset),
    .B(_231_),
    .Y(_232_)
  );
  NOR _532_ (
    .A(data0[8]),
    .B(etapa1_preData0[2]),
    .Y(_233_)
  );
  NOR _533_ (
    .A(_232_),
    .B(_233_),
    .Y(_000_[2])
  );
  NAND _534_ (
    .A(data0[8]),
    .B(_011_),
    .Y(_234_)
  );
  NAND _535_ (
    .A(reset),
    .B(_234_),
    .Y(_235_)
  );
  NOR _536_ (
    .A(data0[8]),
    .B(etapa1_preData0[3]),
    .Y(_236_)
  );
  NOR _537_ (
    .A(_235_),
    .B(_236_),
    .Y(_000_[3])
  );
  NAND _538_ (
    .A(data0[8]),
    .B(_012_),
    .Y(_237_)
  );
  NAND _539_ (
    .A(reset),
    .B(_237_),
    .Y(_238_)
  );
  NOR _540_ (
    .A(data0[8]),
    .B(etapa1_preData0[4]),
    .Y(_239_)
  );
  NOR _541_ (
    .A(_238_),
    .B(_239_),
    .Y(_000_[4])
  );
  NAND _542_ (
    .A(data0[8]),
    .B(_013_),
    .Y(_240_)
  );
  NAND _543_ (
    .A(reset),
    .B(_240_),
    .Y(_241_)
  );
  NOR _544_ (
    .A(data0[8]),
    .B(etapa1_preData0[5]),
    .Y(_242_)
  );
  NOR _545_ (
    .A(_241_),
    .B(_242_),
    .Y(_000_[5])
  );
  NAND _546_ (
    .A(data0[8]),
    .B(_014_),
    .Y(_243_)
  );
  NAND _547_ (
    .A(reset),
    .B(_243_),
    .Y(_244_)
  );
  NOR _548_ (
    .A(data0[8]),
    .B(etapa1_preData0[6]),
    .Y(_245_)
  );
  NOR _549_ (
    .A(_244_),
    .B(_245_),
    .Y(_000_[6])
  );
  NAND _550_ (
    .A(data0[8]),
    .B(_015_),
    .Y(_246_)
  );
  NAND _551_ (
    .A(reset),
    .B(_246_),
    .Y(_247_)
  );
  NOR _552_ (
    .A(data0[8]),
    .B(etapa1_preData0[7]),
    .Y(_248_)
  );
  NOR _553_ (
    .A(_247_),
    .B(_248_),
    .Y(_000_[7])
  );
  NAND _554_ (
    .A(data0[8]),
    .B(reset),
    .Y(_249_)
  );
  NOT _555_ (
    .A(_249_),
    .Y(_000_[8])
  );
  (* src = "muxesEst.v:49" *)
  DFF _556_ (
    .C(clk_4f),
    .D(_008_),
    .Q(selectorL2)
  );
  (* src = "muxesEst.v:49" *)
  DFF _557_ (
    .C(clk_4f),
    .D(_006_[0]),
    .Q(outEtapaL2[0])
  );
  (* src = "muxesEst.v:49" *)
  DFF _558_ (
    .C(clk_4f),
    .D(_006_[1]),
    .Q(outEtapaL2[1])
  );
  (* src = "muxesEst.v:49" *)
  DFF _559_ (
    .C(clk_4f),
    .D(_006_[2]),
    .Q(outEtapaL2[2])
  );
  (* src = "muxesEst.v:49" *)
  DFF _560_ (
    .C(clk_4f),
    .D(_006_[3]),
    .Q(outEtapaL2[3])
  );
  (* src = "muxesEst.v:49" *)
  DFF _561_ (
    .C(clk_4f),
    .D(_006_[4]),
    .Q(outEtapaL2[4])
  );
  (* src = "muxesEst.v:49" *)
  DFF _562_ (
    .C(clk_4f),
    .D(_006_[5]),
    .Q(outEtapaL2[5])
  );
  (* src = "muxesEst.v:49" *)
  DFF _563_ (
    .C(clk_4f),
    .D(_006_[6]),
    .Q(outEtapaL2[6])
  );
  (* src = "muxesEst.v:49" *)
  DFF _564_ (
    .C(clk_4f),
    .D(_006_[7]),
    .Q(outEtapaL2[7])
  );
  (* src = "muxesEst.v:49" *)
  DFF _565_ (
    .C(clk_4f),
    .D(_006_[8]),
    .Q(outEtapaL2[8])
  );
  (* src = "muxesEst.v:35" *)
  DFF _566_ (
    .C(clk_2f),
    .D(_007_),
    .Q(selectorL1)
  );
  (* src = "muxesEst.v:35" *)
  DFF _567_ (
    .C(clk_2f),
    .D(_004_[0]),
    .Q(etapa2_preData0[0])
  );
  (* src = "muxesEst.v:35" *)
  DFF _568_ (
    .C(clk_2f),
    .D(_004_[1]),
    .Q(etapa2_preData0[1])
  );
  (* src = "muxesEst.v:35" *)
  DFF _569_ (
    .C(clk_2f),
    .D(_004_[2]),
    .Q(etapa2_preData0[2])
  );
  (* src = "muxesEst.v:35" *)
  DFF _570_ (
    .C(clk_2f),
    .D(_004_[3]),
    .Q(etapa2_preData0[3])
  );
  (* src = "muxesEst.v:35" *)
  DFF _571_ (
    .C(clk_2f),
    .D(_004_[4]),
    .Q(etapa2_preData0[4])
  );
  (* src = "muxesEst.v:35" *)
  DFF _572_ (
    .C(clk_2f),
    .D(_004_[5]),
    .Q(etapa2_preData0[5])
  );
  (* src = "muxesEst.v:35" *)
  DFF _573_ (
    .C(clk_2f),
    .D(_004_[6]),
    .Q(etapa2_preData0[6])
  );
  (* src = "muxesEst.v:35" *)
  DFF _574_ (
    .C(clk_2f),
    .D(_004_[7]),
    .Q(etapa2_preData0[7])
  );
  (* src = "muxesEst.v:35" *)
  DFF _575_ (
    .C(clk_2f),
    .D(_004_[8]),
    .Q(etapa2_preData0[8])
  );
  (* src = "muxesEst.v:35" *)
  DFF _576_ (
    .C(clk_2f),
    .D(_005_[0]),
    .Q(etapa2_preData1[0])
  );
  (* src = "muxesEst.v:35" *)
  DFF _577_ (
    .C(clk_2f),
    .D(_005_[1]),
    .Q(etapa2_preData1[1])
  );
  (* src = "muxesEst.v:35" *)
  DFF _578_ (
    .C(clk_2f),
    .D(_005_[2]),
    .Q(etapa2_preData1[2])
  );
  (* src = "muxesEst.v:35" *)
  DFF _579_ (
    .C(clk_2f),
    .D(_005_[3]),
    .Q(etapa2_preData1[3])
  );
  (* src = "muxesEst.v:35" *)
  DFF _580_ (
    .C(clk_2f),
    .D(_005_[4]),
    .Q(etapa2_preData1[4])
  );
  (* src = "muxesEst.v:35" *)
  DFF _581_ (
    .C(clk_2f),
    .D(_005_[5]),
    .Q(etapa2_preData1[5])
  );
  (* src = "muxesEst.v:35" *)
  DFF _582_ (
    .C(clk_2f),
    .D(_005_[6]),
    .Q(etapa2_preData1[6])
  );
  (* src = "muxesEst.v:35" *)
  DFF _583_ (
    .C(clk_2f),
    .D(_005_[7]),
    .Q(etapa2_preData1[7])
  );
  (* src = "muxesEst.v:35" *)
  DFF _584_ (
    .C(clk_2f),
    .D(_005_[8]),
    .Q(etapa2_preData1[8])
  );
  (* src = "muxesEst.v:18" *)
  DFF _585_ (
    .C(clk_f),
    .D(_000_[0]),
    .Q(etapa1_preData0[0])
  );
  (* src = "muxesEst.v:18" *)
  DFF _586_ (
    .C(clk_f),
    .D(_000_[1]),
    .Q(etapa1_preData0[1])
  );
  (* src = "muxesEst.v:18" *)
  DFF _587_ (
    .C(clk_f),
    .D(_000_[2]),
    .Q(etapa1_preData0[2])
  );
  (* src = "muxesEst.v:18" *)
  DFF _588_ (
    .C(clk_f),
    .D(_000_[3]),
    .Q(etapa1_preData0[3])
  );
  (* src = "muxesEst.v:18" *)
  DFF _589_ (
    .C(clk_f),
    .D(_000_[4]),
    .Q(etapa1_preData0[4])
  );
  (* src = "muxesEst.v:18" *)
  DFF _590_ (
    .C(clk_f),
    .D(_000_[5]),
    .Q(etapa1_preData0[5])
  );
  (* src = "muxesEst.v:18" *)
  DFF _591_ (
    .C(clk_f),
    .D(_000_[6]),
    .Q(etapa1_preData0[6])
  );
  (* src = "muxesEst.v:18" *)
  DFF _592_ (
    .C(clk_f),
    .D(_000_[7]),
    .Q(etapa1_preData0[7])
  );
  (* src = "muxesEst.v:18" *)
  DFF _593_ (
    .C(clk_f),
    .D(_000_[8]),
    .Q(etapa1_preData0[8])
  );
  (* src = "muxesEst.v:18" *)
  DFF _594_ (
    .C(clk_f),
    .D(_001_[0]),
    .Q(etapa1_preData1[0])
  );
  (* src = "muxesEst.v:18" *)
  DFF _595_ (
    .C(clk_f),
    .D(_001_[1]),
    .Q(etapa1_preData1[1])
  );
  (* src = "muxesEst.v:18" *)
  DFF _596_ (
    .C(clk_f),
    .D(_001_[2]),
    .Q(etapa1_preData1[2])
  );
  (* src = "muxesEst.v:18" *)
  DFF _597_ (
    .C(clk_f),
    .D(_001_[3]),
    .Q(etapa1_preData1[3])
  );
  (* src = "muxesEst.v:18" *)
  DFF _598_ (
    .C(clk_f),
    .D(_001_[4]),
    .Q(etapa1_preData1[4])
  );
  (* src = "muxesEst.v:18" *)
  DFF _599_ (
    .C(clk_f),
    .D(_001_[5]),
    .Q(etapa1_preData1[5])
  );
  (* src = "muxesEst.v:18" *)
  DFF _600_ (
    .C(clk_f),
    .D(_001_[6]),
    .Q(etapa1_preData1[6])
  );
  (* src = "muxesEst.v:18" *)
  DFF _601_ (
    .C(clk_f),
    .D(_001_[7]),
    .Q(etapa1_preData1[7])
  );
  (* src = "muxesEst.v:18" *)
  DFF _602_ (
    .C(clk_f),
    .D(_001_[8]),
    .Q(etapa1_preData1[8])
  );
  (* src = "muxesEst.v:18" *)
  DFF _603_ (
    .C(clk_f),
    .D(_002_[0]),
    .Q(etapa1_preData2[0])
  );
  (* src = "muxesEst.v:18" *)
  DFF _604_ (
    .C(clk_f),
    .D(_002_[1]),
    .Q(etapa1_preData2[1])
  );
  (* src = "muxesEst.v:18" *)
  DFF _605_ (
    .C(clk_f),
    .D(_002_[2]),
    .Q(etapa1_preData2[2])
  );
  (* src = "muxesEst.v:18" *)
  DFF _606_ (
    .C(clk_f),
    .D(_002_[3]),
    .Q(etapa1_preData2[3])
  );
  (* src = "muxesEst.v:18" *)
  DFF _607_ (
    .C(clk_f),
    .D(_002_[4]),
    .Q(etapa1_preData2[4])
  );
  (* src = "muxesEst.v:18" *)
  DFF _608_ (
    .C(clk_f),
    .D(_002_[5]),
    .Q(etapa1_preData2[5])
  );
  (* src = "muxesEst.v:18" *)
  DFF _609_ (
    .C(clk_f),
    .D(_002_[6]),
    .Q(etapa1_preData2[6])
  );
  (* src = "muxesEst.v:18" *)
  DFF _610_ (
    .C(clk_f),
    .D(_002_[7]),
    .Q(etapa1_preData2[7])
  );
  (* src = "muxesEst.v:18" *)
  DFF _611_ (
    .C(clk_f),
    .D(_002_[8]),
    .Q(etapa1_preData2[8])
  );
  (* src = "muxesEst.v:18" *)
  DFF _612_ (
    .C(clk_f),
    .D(_003_[0]),
    .Q(etapa1_preData3[0])
  );
  (* src = "muxesEst.v:18" *)
  DFF _613_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(etapa1_preData3[1])
  );
  (* src = "muxesEst.v:18" *)
  DFF _614_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(etapa1_preData3[2])
  );
  (* src = "muxesEst.v:18" *)
  DFF _615_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(etapa1_preData3[3])
  );
  (* src = "muxesEst.v:18" *)
  DFF _616_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(etapa1_preData3[4])
  );
  (* src = "muxesEst.v:18" *)
  DFF _617_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(etapa1_preData3[5])
  );
  (* src = "muxesEst.v:18" *)
  DFF _618_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(etapa1_preData3[6])
  );
  (* src = "muxesEst.v:18" *)
  DFF _619_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(etapa1_preData3[7])
  );
  (* src = "muxesEst.v:18" *)
  DFF _620_ (
    .C(clk_f),
    .D(_003_[8]),
    .Q(etapa1_preData3[8])
  );
endmodule

(* top =  1  *)
(* src = "phyEst.v:5" *)
module phyEst(clk16, clk4f, clk2f, clkf, reset, paralelo0, paralelo1, paralelo2, paralelo3, data_0, data_1, data_2, data_3);
  (* src = "phyEst.v:5" *)
  input clk16;
  (* src = "phyEst.v:5" *)
  input clk2f;
  (* src = "phyEst.v:5" *)
  input clk4f;
  (* src = "phyEst.v:5" *)
  input clkf;
  (* src = "phyEst.v:5" *)
  output [8:0] data_0;
  (* src = "phyEst.v:5" *)
  output [8:0] data_1;
  (* src = "phyEst.v:5" *)
  output [8:0] data_2;
  (* src = "phyEst.v:5" *)
  output [8:0] data_3;
  (* src = "phyEst.v:5" *)
  input [8:0] paralelo0;
  (* src = "phyEst.v:5" *)
  input [8:0] paralelo1;
  (* src = "phyEst.v:5" *)
  input [8:0] paralelo2;
  (* src = "phyEst.v:5" *)
  input [8:0] paralelo3;
  (* src = "phyEst.v:5" *)
  input reset;
  (* src = "phyEst.v:8" *)
  wire [1:0] serial;
  (* src = "phyEst.v:11" *)
  phyEst_rx phyEstRx (
    .clk_16(clk16),
    .clk_2f(clk2f),
    .clk_4f(clk4f),
    .clk_f(clkf),
    .data_0(data_0),
    .data_1(data_1),
    .data_2(data_2),
    .data_3(data_3),
    .reset(reset),
    .serial(serial)
  );
  (* src = "phyEst.v:25" *)
  phyEst_tx phyEstTx (
    .clk16f(clk16),
    .clk2f(clk2f),
    .clk4f(clk4f),
    .clkf(clkf),
    .paralelo0(paralelo0),
    .paralelo1(paralelo1),
    .paralelo2(paralelo2),
    .paralelo3(paralelo3),
    .reset(reset),
    .reset_L(reset),
    .serial(serial)
  );
endmodule

(* src = "phyEst_rx.v:4" *)
module phyEst_rx(clk_f, clk_2f, clk_4f, clk_16, reset, serial, data_0, data_1, data_2, data_3);
  (* src = "phyEst_rx.v:7" *)
  input clk_16;
  (* src = "phyEst_rx.v:5" *)
  input clk_2f;
  (* src = "phyEst_rx.v:6" *)
  input clk_4f;
  (* src = "phyEst_rx.v:4" *)
  input clk_f;
  (* src = "phyEst_rx.v:10" *)
  output [8:0] data_0;
  (* src = "phyEst_rx.v:11" *)
  output [8:0] data_1;
  (* src = "phyEst_rx.v:12" *)
  output [8:0] data_2;
  (* src = "phyEst_rx.v:13" *)
  output [8:0] data_3;
  (* src = "phyEst_rx.v:15" *)
  wire [8:0] inDemuxesEst;
  (* src = "phyEst_rx.v:8" *)
  input reset;
  (* src = "phyEst_rx.v:9" *)
  input [1:0] serial;
  (* src = "phyEst_rx.v:22" *)
  demuxEst demuxEstes (
    .clk_2f(clk_2f),
    .clk_4f(clk_4f),
    .clk_f(clk_f),
    .data0(data_0),
    .data1(data_1),
    .data2(data_2),
    .data3(data_3),
    .inEtapaL2(inDemuxesEst),
    .reset(reset)
  );
  (* src = "phyEst_rx.v:17" *)
  serialParaleloEst serial_paralelo (
    .clk16(clk_16),
    .outParalelo(inDemuxesEst),
    .reset16(reset),
    .serial(serial)
  );
endmodule

(* src = "phyEst_tx.v:4" *)
module phyEst_tx(clk16f, clk4f, clk2f, clkf, reset, reset_L, paralelo0, paralelo1, paralelo2, paralelo3, serial);
  (* src = "phyEst_tx.v:5" *)
  input clk16f;
  (* src = "phyEst_tx.v:7" *)
  input clk2f;
  (* src = "phyEst_tx.v:6" *)
  input clk4f;
  (* src = "phyEst_tx.v:8" *)
  input clkf;
  (* src = "phyEst_tx.v:18" *)
  wire [8:0] outEtapaL2;
  (* src = "phyEst_tx.v:11" *)
  input [8:0] paralelo0;
  (* src = "phyEst_tx.v:12" *)
  input [8:0] paralelo1;
  (* src = "phyEst_tx.v:13" *)
  input [8:0] paralelo2;
  (* src = "phyEst_tx.v:14" *)
  input [8:0] paralelo3;
  (* src = "phyEst_tx.v:9" *)
  input reset;
  (* src = "phyEst_tx.v:10" *)
  input reset_L;
  (* src = "phyEst_tx.v:15" *)
  output [1:0] serial;
  (* src = "phyEst_tx.v:23" *)
  muxesEst muxesEstMod (
    .clk_2f(clk2f),
    .clk_4f(clk4f),
    .clk_f(clkf),
    .data0(paralelo0),
    .data1(paralelo1),
    .data2(paralelo2),
    .data3(paralelo3),
    .outEtapaL2(outEtapaL2),
    .reset(reset_L)
  );
  (* src = "phyEst_tx.v:35" *)
  ParaleloSerialEst psMod (
    .clk16f(clk16f),
    .clk4f(clk4f),
    .paralelo(outEtapaL2),
    .reset(reset),
    .reset_L(reset_L),
    .serial(serial)
  );
endmodule

(* src = "serialParaleloEst.v:5" *)
module serialParaleloEst(clk16, reset16, serial, outParalelo);
  (* src = "serialParaleloEst.v:13" *)
  wire [2:0] _00_;
  (* src = "serialParaleloEst.v:13" *)
  wire [1:0] _01_;
  (* src = "serialParaleloEst.v:13" *)
  wire [8:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "serialParaleloEst.v:5" *)
  input clk16;
  (* src = "serialParaleloEst.v:7" *)
  wire [2:0] contador;
  (* src = "serialParaleloEst.v:8" *)
  wire [1:0] i;
  (* src = "serialParaleloEst.v:5" *)
  output [8:0] outParalelo;
  (* src = "serialParaleloEst.v:5" *)
  input reset16;
  (* src = "serialParaleloEst.v:5" *)
  input [1:0] serial;
  NOT _25_ (
    .A(reset16),
    .Y(_03_)
  );
  NOT _26_ (
    .A(i[1]),
    .Y(_04_)
  );
  NOT _27_ (
    .A(i[0]),
    .Y(_05_)
  );
  NOR _28_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  NAND _29_ (
    .A(i[1]),
    .B(i[0]),
    .Y(_07_)
  );
  NOR _30_ (
    .A(outParalelo[8]),
    .B(_06_),
    .Y(_08_)
  );
  NAND _31_ (
    .A(contador[2]),
    .B(reset16),
    .Y(_09_)
  );
  NOT _32_ (
    .A(_09_),
    .Y(_00_[2])
  );
  NAND _33_ (
    .A(reset16),
    .B(_07_),
    .Y(_10_)
  );
  NAND _34_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  NOT _35_ (
    .A(_11_),
    .Y(_12_)
  );
  NOR _36_ (
    .A(_08_),
    .B(_12_),
    .Y(_02_[8])
  );
  NOR _37_ (
    .A(outParalelo[0]),
    .B(_06_),
    .Y(_13_)
  );
  NOR _38_ (
    .A(_03_),
    .B(_13_),
    .Y(_02_[0])
  );
  NOR _39_ (
    .A(outParalelo[1]),
    .B(_06_),
    .Y(_14_)
  );
  NOR _40_ (
    .A(_03_),
    .B(_14_),
    .Y(_02_[1])
  );
  NOR _41_ (
    .A(outParalelo[2]),
    .B(_06_),
    .Y(_15_)
  );
  NOR _42_ (
    .A(_03_),
    .B(_15_),
    .Y(_02_[2])
  );
  NOR _43_ (
    .A(outParalelo[3]),
    .B(_06_),
    .Y(_16_)
  );
  NOR _44_ (
    .A(_03_),
    .B(_16_),
    .Y(_02_[3])
  );
  NOR _45_ (
    .A(outParalelo[4]),
    .B(_06_),
    .Y(_17_)
  );
  NOR _46_ (
    .A(_03_),
    .B(_17_),
    .Y(_02_[4])
  );
  NOR _47_ (
    .A(outParalelo[5]),
    .B(_06_),
    .Y(_18_)
  );
  NOR _48_ (
    .A(_03_),
    .B(_18_),
    .Y(_02_[5])
  );
  NOR _49_ (
    .A(outParalelo[6]),
    .B(_06_),
    .Y(_19_)
  );
  NOR _50_ (
    .A(_03_),
    .B(_19_),
    .Y(_02_[6])
  );
  NOR _51_ (
    .A(outParalelo[7]),
    .B(_06_),
    .Y(_20_)
  );
  NOR _52_ (
    .A(_03_),
    .B(_20_),
    .Y(_02_[7])
  );
  NAND _53_ (
    .A(contador[0]),
    .B(reset16),
    .Y(_21_)
  );
  NAND _54_ (
    .A(contador[1]),
    .B(_00_[2]),
    .Y(_22_)
  );
  NAND _55_ (
    .A(_21_),
    .B(_22_),
    .Y(_00_[0])
  );
  NAND _56_ (
    .A(contador[1]),
    .B(reset16),
    .Y(_23_)
  );
  NOR _57_ (
    .A(contador[2]),
    .B(_23_),
    .Y(_00_[1])
  );
  NOR _58_ (
    .A(_03_),
    .B(i[0]),
    .Y(_01_[0])
  );
  NOR _59_ (
    .A(i[1]),
    .B(i[0]),
    .Y(_24_)
  );
  NOR _60_ (
    .A(_10_),
    .B(_24_),
    .Y(_01_[1])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _61_ (
    .C(clk16),
    .D(_02_[0]),
    .Q(outParalelo[0])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _62_ (
    .C(clk16),
    .D(_02_[1]),
    .Q(outParalelo[1])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _63_ (
    .C(clk16),
    .D(_02_[2]),
    .Q(outParalelo[2])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _64_ (
    .C(clk16),
    .D(_02_[3]),
    .Q(outParalelo[3])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _65_ (
    .C(clk16),
    .D(_02_[4]),
    .Q(outParalelo[4])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _66_ (
    .C(clk16),
    .D(_02_[5]),
    .Q(outParalelo[5])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _67_ (
    .C(clk16),
    .D(_02_[6]),
    .Q(outParalelo[6])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _68_ (
    .C(clk16),
    .D(_02_[7]),
    .Q(outParalelo[7])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _69_ (
    .C(clk16),
    .D(_02_[8]),
    .Q(outParalelo[8])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _70_ (
    .C(clk16),
    .D(_00_[0]),
    .Q(contador[0])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _71_ (
    .C(clk16),
    .D(_00_[1]),
    .Q(contador[1])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _72_ (
    .C(clk16),
    .D(_00_[2]),
    .Q(contador[2])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _73_ (
    .C(clk16),
    .D(_01_[0]),
    .Q(i[0])
  );
  (* src = "serialParaleloEst.v:13" *)
  DFF _74_ (
    .C(clk16),
    .D(_01_[1]),
    .Q(i[1])
  );
endmodule
