/* Generated by Yosys 0.7+659 (git sha1 51f1bbe, clang 3.5.0-10 -fPIC -Os) */

module ParaleloSerialEstructural(clk16f, clk4f, reset, reset_L, paralelo, serial);
  wire [1:0] _000_;
  wire [1:0] _001_;
  wire [1:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  input clk16f;
  input clk4f;
  wire [1:0] counterbc;
  wire [1:0] counterdata;
  input [8:0] paralelo;
  input reset;
  input reset_L;
  output [1:0] serial;
  NOT _049_ (
    .A(counterbc[1]),
    .Y(_003_)
  );
  NOT _050_ (
    .A(counterdata[1]),
    .Y(_004_)
  );
  NOT _051_ (
    .A(counterdata[0]),
    .Y(_005_)
  );
  NOT _052_ (
    .A(reset),
    .Y(_006_)
  );
  NOT _053_ (
    .A(reset_L),
    .Y(_007_)
  );
  NAND _054_ (
    .A(_006_),
    .B(paralelo[8]),
    .Y(_008_)
  );
  NOT _055_ (
    .A(_008_),
    .Y(_009_)
  );
  NOR _056_ (
    .A(counterdata[1]),
    .B(counterdata[0]),
    .Y(_010_)
  );
  NAND _057_ (
    .A(paralelo[7]),
    .B(_010_),
    .Y(_011_)
  );
  NOR _058_ (
    .A(_004_),
    .B(_005_),
    .Y(_012_)
  );
  NAND _059_ (
    .A(paralelo[1]),
    .B(_012_),
    .Y(_013_)
  );
  NAND _060_ (
    .A(_011_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _061_ (
    .A(counterdata[1]),
    .B(_005_),
    .Y(_015_)
  );
  NAND _062_ (
    .A(paralelo[5]),
    .B(_015_),
    .Y(_016_)
  );
  NOR _063_ (
    .A(_004_),
    .B(counterdata[0]),
    .Y(_017_)
  );
  NAND _064_ (
    .A(paralelo[3]),
    .B(_017_),
    .Y(_018_)
  );
  NAND _065_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _066_ (
    .A(_014_),
    .B(_019_),
    .Y(_020_)
  );
  NOR _067_ (
    .A(_008_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _068_ (
    .A(counterbc[1]),
    .B(counterbc[0]),
    .Y(_022_)
  );
  NAND _069_ (
    .A(_008_),
    .B(_022_),
    .Y(_023_)
  );
  NOT _070_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _071_ (
    .A(_021_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _072_ (
    .A(_007_),
    .B(_025_),
    .Y(_002_[1])
  );
  NOR _073_ (
    .A(counterbc[1]),
    .B(counterbc[0]),
    .Y(_026_)
  );
  NOR _074_ (
    .A(_023_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _075_ (
    .A(paralelo[6]),
    .B(_010_),
    .Y(_028_)
  );
  NAND _076_ (
    .A(paralelo[0]),
    .B(_012_),
    .Y(_029_)
  );
  NAND _077_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _078_ (
    .A(paralelo[4]),
    .B(_015_),
    .Y(_031_)
  );
  NAND _079_ (
    .A(paralelo[2]),
    .B(_017_),
    .Y(_032_)
  );
  NAND _080_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _081_ (
    .A(_030_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _082_ (
    .A(_008_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _083_ (
    .A(_027_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _084_ (
    .A(_007_),
    .B(_036_),
    .Y(_002_[0])
  );
  NOR _085_ (
    .A(counterbc[0]),
    .B(_008_),
    .Y(_037_)
  );
  NAND _086_ (
    .A(counterbc[0]),
    .B(_008_),
    .Y(_038_)
  );
  NAND _087_ (
    .A(reset_L),
    .B(_038_),
    .Y(_039_)
  );
  NOR _088_ (
    .A(_037_),
    .B(_039_),
    .Y(_000_[0])
  );
  NOR _089_ (
    .A(_003_),
    .B(_008_),
    .Y(_040_)
  );
  NOR _090_ (
    .A(_027_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _091_ (
    .A(_007_),
    .B(_041_),
    .Y(_000_[1])
  );
  NAND _092_ (
    .A(counterdata[0]),
    .B(_009_),
    .Y(_042_)
  );
  NOT _093_ (
    .A(_042_),
    .Y(_043_)
  );
  NAND _094_ (
    .A(_005_),
    .B(_008_),
    .Y(_044_)
  );
  NAND _095_ (
    .A(reset_L),
    .B(_044_),
    .Y(_045_)
  );
  NOR _096_ (
    .A(_043_),
    .B(_045_),
    .Y(_001_[0])
  );
  NOR _097_ (
    .A(_004_),
    .B(_042_),
    .Y(_046_)
  );
  NAND _098_ (
    .A(_004_),
    .B(_042_),
    .Y(_047_)
  );
  NAND _099_ (
    .A(reset_L),
    .B(_047_),
    .Y(_048_)
  );
  NOR _100_ (
    .A(_046_),
    .B(_048_),
    .Y(_001_[1])
  );
  DFF _101_ (
    .C(clk16f),
    .D(_002_[0]),
    .Q(serial[0])
  );
  DFF _102_ (
    .C(clk16f),
    .D(_002_[1]),
    .Q(serial[1])
  );
  DFF _103_ (
    .C(clk16f),
    .D(_000_[0]),
    .Q(counterbc[0])
  );
  DFF _104_ (
    .C(clk16f),
    .D(_000_[1]),
    .Q(counterbc[1])
  );
  DFF _105_ (
    .C(clk16f),
    .D(_001_[0]),
    .Q(counterdata[0])
  );
  DFF _106_ (
    .C(clk16f),
    .D(_001_[1]),
    .Q(counterdata[1])
  );
endmodule
