/* Generated by Yosys 0.7+574 (git sha1 0fad1570, gcc 6.3.0-18+deb9u1 -fPIC -Os) */

(* top =  1  *)
(* src = "demuxEstructural.v:3" *)
module demuxEstructural(clk_f, clk_2f, clk_4f, reset, inEtapaL2, data0, data1, data2, data3);
  (* src = "demuxEstructural.v:67" *)
  wire [8:0] _000_;
  (* src = "demuxEstructural.v:67" *)
  wire [8:0] _001_;
  (* src = "demuxEstructural.v:67" *)
  wire [8:0] _002_;
  (* src = "demuxEstructural.v:67" *)
  wire [8:0] _003_;
  (* src = "demuxEstructural.v:36" *)
  wire [8:0] _004_;
  (* src = "demuxEstructural.v:36" *)
  wire [8:0] _005_;
  (* src = "demuxEstructural.v:36" *)
  wire [8:0] _006_;
  (* src = "demuxEstructural.v:36" *)
  wire [8:0] _007_;
  (* src = "demuxEstructural.v:36" *)
  wire [8:0] _008_;
  (* src = "demuxEstructural.v:36" *)
  wire [8:0] _009_;
  (* src = "demuxEstructural.v:18" *)
  wire [8:0] _010_;
  (* src = "demuxEstructural.v:18" *)
  wire [8:0] _011_;
  (* src = "demuxEstructural.v:36" *)
  wire _012_;
  (* src = "demuxEstructural.v:18" *)
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  (* src = "demuxEstructural.v:4" *)
  input clk_2f;
  (* src = "demuxEstructural.v:5" *)
  input clk_4f;
  (* src = "demuxEstructural.v:3" *)
  input clk_f;
  (* src = "demuxEstructural.v:8" *)
  output [8:0] data0;
  (* src = "demuxEstructural.v:9" *)
  output [8:0] data1;
  (* src = "demuxEstructural.v:10" *)
  output [8:0] data2;
  (* src = "demuxEstructural.v:11" *)
  output [8:0] data3;
  (* src = "demuxEstructural.v:15" *)
  wire [8:0] etapa1_inData0;
  (* src = "demuxEstructural.v:15" *)
  wire [8:0] etapa1_inData1;
  (* src = "demuxEstructural.v:15" *)
  wire [8:0] etapa1_inData2;
  (* src = "demuxEstructural.v:15" *)
  wire [8:0] etapa1_inData3;
  (* src = "demuxEstructural.v:16" *)
  wire [8:0] etapa2_inData0;
  (* src = "demuxEstructural.v:16" *)
  wire [8:0] etapa2_inData1;
  (* src = "demuxEstructural.v:7" *)
  input [8:0] inEtapaL2;
  (* src = "demuxEstructural.v:13" *)
  wire [8:0] outEtapaL1L2_0;
  (* src = "demuxEstructural.v:13" *)
  wire [8:0] outEtapaL1L2_1;
  (* src = "demuxEstructural.v:6" *)
  input reset;
  (* src = "demuxEstructural.v:14" *)
  wire selectorL1;
  (* src = "demuxEstructural.v:14" *)
  wire selectorL2;
  NOT _316_ (
    .A(etapa2_inData1[1]),
    .Y(_014_)
  );
  NOT _317_ (
    .A(etapa2_inData1[2]),
    .Y(_015_)
  );
  NOT _318_ (
    .A(etapa2_inData1[3]),
    .Y(_016_)
  );
  NOT _319_ (
    .A(etapa2_inData1[4]),
    .Y(_017_)
  );
  NOT _320_ (
    .A(etapa2_inData1[5]),
    .Y(_018_)
  );
  NOT _321_ (
    .A(etapa2_inData1[6]),
    .Y(_019_)
  );
  NOT _322_ (
    .A(etapa2_inData1[7]),
    .Y(_020_)
  );
  NOT _323_ (
    .A(etapa2_inData0[0]),
    .Y(_021_)
  );
  NOT _324_ (
    .A(etapa2_inData0[1]),
    .Y(_022_)
  );
  NOT _325_ (
    .A(etapa2_inData0[2]),
    .Y(_023_)
  );
  NOT _326_ (
    .A(etapa2_inData0[3]),
    .Y(_024_)
  );
  NOT _327_ (
    .A(etapa2_inData0[4]),
    .Y(_025_)
  );
  NOT _328_ (
    .A(etapa2_inData0[5]),
    .Y(_026_)
  );
  NOT _329_ (
    .A(etapa2_inData0[6]),
    .Y(_027_)
  );
  NOT _330_ (
    .A(etapa2_inData0[7]),
    .Y(_028_)
  );
  NOT _331_ (
    .A(outEtapaL1L2_0[0]),
    .Y(_029_)
  );
  NOT _332_ (
    .A(outEtapaL1L2_0[8]),
    .Y(_030_)
  );
  NOT _333_ (
    .A(outEtapaL1L2_0[1]),
    .Y(_031_)
  );
  NOT _334_ (
    .A(outEtapaL1L2_0[2]),
    .Y(_032_)
  );
  NOT _335_ (
    .A(outEtapaL1L2_0[3]),
    .Y(_033_)
  );
  NOT _336_ (
    .A(outEtapaL1L2_0[4]),
    .Y(_034_)
  );
  NOT _337_ (
    .A(outEtapaL1L2_0[5]),
    .Y(_035_)
  );
  NOT _338_ (
    .A(outEtapaL1L2_0[6]),
    .Y(_036_)
  );
  NOT _339_ (
    .A(outEtapaL1L2_0[7]),
    .Y(_037_)
  );
  NOT _340_ (
    .A(etapa2_inData1[0]),
    .Y(_038_)
  );
  NOT _341_ (
    .A(outEtapaL1L2_1[8]),
    .Y(_039_)
  );
  NOT _342_ (
    .A(outEtapaL1L2_1[1]),
    .Y(_040_)
  );
  NOT _343_ (
    .A(outEtapaL1L2_1[2]),
    .Y(_041_)
  );
  NOT _344_ (
    .A(outEtapaL1L2_1[3]),
    .Y(_042_)
  );
  NOT _345_ (
    .A(outEtapaL1L2_1[4]),
    .Y(_043_)
  );
  NOT _346_ (
    .A(outEtapaL1L2_1[5]),
    .Y(_044_)
  );
  NOT _347_ (
    .A(outEtapaL1L2_1[6]),
    .Y(_045_)
  );
  NOT _348_ (
    .A(outEtapaL1L2_1[7]),
    .Y(_046_)
  );
  NOT _349_ (
    .A(etapa1_inData1[0]),
    .Y(_047_)
  );
  NOT _350_ (
    .A(etapa1_inData1[1]),
    .Y(_048_)
  );
  NOT _351_ (
    .A(etapa1_inData1[2]),
    .Y(_049_)
  );
  NOT _352_ (
    .A(etapa1_inData1[3]),
    .Y(_050_)
  );
  NOT _353_ (
    .A(etapa1_inData1[4]),
    .Y(_051_)
  );
  NOT _354_ (
    .A(etapa1_inData1[5]),
    .Y(_052_)
  );
  NOT _355_ (
    .A(etapa1_inData1[6]),
    .Y(_053_)
  );
  NOT _356_ (
    .A(etapa1_inData1[7]),
    .Y(_054_)
  );
  NOT _357_ (
    .A(etapa1_inData3[0]),
    .Y(_055_)
  );
  NOT _358_ (
    .A(etapa1_inData3[1]),
    .Y(_056_)
  );
  NOT _359_ (
    .A(etapa1_inData3[2]),
    .Y(_057_)
  );
  NOT _360_ (
    .A(etapa1_inData3[3]),
    .Y(_058_)
  );
  NOT _361_ (
    .A(etapa1_inData3[4]),
    .Y(_059_)
  );
  NOT _362_ (
    .A(etapa1_inData3[5]),
    .Y(_060_)
  );
  NOT _363_ (
    .A(etapa1_inData3[6]),
    .Y(_061_)
  );
  NOT _364_ (
    .A(etapa1_inData3[7]),
    .Y(_062_)
  );
  NOT _365_ (
    .A(etapa1_inData0[0]),
    .Y(_063_)
  );
  NOT _366_ (
    .A(etapa1_inData0[1]),
    .Y(_064_)
  );
  NOT _367_ (
    .A(etapa1_inData0[2]),
    .Y(_065_)
  );
  NOT _368_ (
    .A(etapa1_inData0[3]),
    .Y(_066_)
  );
  NOT _369_ (
    .A(etapa1_inData0[4]),
    .Y(_067_)
  );
  NOT _370_ (
    .A(etapa1_inData0[5]),
    .Y(_068_)
  );
  NOT _371_ (
    .A(etapa1_inData0[6]),
    .Y(_069_)
  );
  NOT _372_ (
    .A(etapa1_inData0[7]),
    .Y(_070_)
  );
  NOT _373_ (
    .A(etapa1_inData2[0]),
    .Y(_071_)
  );
  NOT _374_ (
    .A(etapa1_inData2[1]),
    .Y(_072_)
  );
  NOT _375_ (
    .A(etapa1_inData2[2]),
    .Y(_073_)
  );
  NOT _376_ (
    .A(etapa1_inData2[3]),
    .Y(_074_)
  );
  NOT _377_ (
    .A(etapa1_inData2[4]),
    .Y(_075_)
  );
  NOT _378_ (
    .A(etapa1_inData2[5]),
    .Y(_076_)
  );
  NOT _379_ (
    .A(etapa1_inData2[6]),
    .Y(_077_)
  );
  NOT _380_ (
    .A(etapa1_inData2[7]),
    .Y(_078_)
  );
  NOT _381_ (
    .A(reset),
    .Y(_079_)
  );
  NOT _382_ (
    .A(selectorL1),
    .Y(_080_)
  );
  NOT _383_ (
    .A(selectorL2),
    .Y(_081_)
  );
  NOR _384_ (
    .A(_055_),
    .B(_079_),
    .Y(_003_[0])
  );
  NOR _385_ (
    .A(_056_),
    .B(_079_),
    .Y(_003_[1])
  );
  NOR _386_ (
    .A(_057_),
    .B(_079_),
    .Y(_003_[2])
  );
  NOR _387_ (
    .A(_058_),
    .B(_079_),
    .Y(_003_[3])
  );
  NOR _388_ (
    .A(_059_),
    .B(_079_),
    .Y(_003_[4])
  );
  NOR _389_ (
    .A(_060_),
    .B(_079_),
    .Y(_003_[5])
  );
  NOR _390_ (
    .A(_061_),
    .B(_079_),
    .Y(_003_[6])
  );
  NOR _391_ (
    .A(_062_),
    .B(_079_),
    .Y(_003_[7])
  );
  NAND _392_ (
    .A(etapa1_inData3[8]),
    .B(reset),
    .Y(_082_)
  );
  NOT _393_ (
    .A(_082_),
    .Y(_003_[8])
  );
  NOR _394_ (
    .A(_071_),
    .B(_079_),
    .Y(_002_[0])
  );
  NOR _395_ (
    .A(_072_),
    .B(_079_),
    .Y(_002_[1])
  );
  NOR _396_ (
    .A(_073_),
    .B(_079_),
    .Y(_002_[2])
  );
  NOR _397_ (
    .A(_074_),
    .B(_079_),
    .Y(_002_[3])
  );
  NOR _398_ (
    .A(_075_),
    .B(_079_),
    .Y(_002_[4])
  );
  NOR _399_ (
    .A(_076_),
    .B(_079_),
    .Y(_002_[5])
  );
  NOR _400_ (
    .A(_077_),
    .B(_079_),
    .Y(_002_[6])
  );
  NOR _401_ (
    .A(_078_),
    .B(_079_),
    .Y(_002_[7])
  );
  NAND _402_ (
    .A(etapa1_inData2[8]),
    .B(reset),
    .Y(_083_)
  );
  NOT _403_ (
    .A(_083_),
    .Y(_002_[8])
  );
  NOR _404_ (
    .A(_047_),
    .B(_079_),
    .Y(_001_[0])
  );
  NOR _405_ (
    .A(_048_),
    .B(_079_),
    .Y(_001_[1])
  );
  NOR _406_ (
    .A(_049_),
    .B(_079_),
    .Y(_001_[2])
  );
  NOR _407_ (
    .A(_050_),
    .B(_079_),
    .Y(_001_[3])
  );
  NOR _408_ (
    .A(_051_),
    .B(_079_),
    .Y(_001_[4])
  );
  NOR _409_ (
    .A(_052_),
    .B(_079_),
    .Y(_001_[5])
  );
  NOR _410_ (
    .A(_053_),
    .B(_079_),
    .Y(_001_[6])
  );
  NOR _411_ (
    .A(_054_),
    .B(_079_),
    .Y(_001_[7])
  );
  NAND _412_ (
    .A(etapa1_inData1[8]),
    .B(reset),
    .Y(_084_)
  );
  NOT _413_ (
    .A(_084_),
    .Y(_001_[8])
  );
  NOR _414_ (
    .A(_063_),
    .B(_079_),
    .Y(_000_[0])
  );
  NOR _415_ (
    .A(_064_),
    .B(_079_),
    .Y(_000_[1])
  );
  NOR _416_ (
    .A(_065_),
    .B(_079_),
    .Y(_000_[2])
  );
  NOR _417_ (
    .A(_066_),
    .B(_079_),
    .Y(_000_[3])
  );
  NOR _418_ (
    .A(_067_),
    .B(_079_),
    .Y(_000_[4])
  );
  NOR _419_ (
    .A(_068_),
    .B(_079_),
    .Y(_000_[5])
  );
  NOR _420_ (
    .A(_069_),
    .B(_079_),
    .Y(_000_[6])
  );
  NOR _421_ (
    .A(_070_),
    .B(_079_),
    .Y(_000_[7])
  );
  NAND _422_ (
    .A(etapa1_inData0[8]),
    .B(reset),
    .Y(_085_)
  );
  NOT _423_ (
    .A(_085_),
    .Y(_000_[8])
  );
  NOR _424_ (
    .A(outEtapaL1L2_1[0]),
    .B(_039_),
    .Y(_086_)
  );
  NAND _425_ (
    .A(outEtapaL1L2_1[8]),
    .B(reset),
    .Y(_087_)
  );
  NOT _426_ (
    .A(_087_),
    .Y(_009_[8])
  );
  NOR _427_ (
    .A(_038_),
    .B(_079_),
    .Y(_088_)
  );
  NOR _428_ (
    .A(_009_[8]),
    .B(_088_),
    .Y(_089_)
  );
  NOR _429_ (
    .A(_086_),
    .B(_089_),
    .Y(_009_[0])
  );
  NOR _430_ (
    .A(_014_),
    .B(outEtapaL1L2_1[8]),
    .Y(_090_)
  );
  NOR _431_ (
    .A(_039_),
    .B(_040_),
    .Y(_091_)
  );
  NOR _432_ (
    .A(_090_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _433_ (
    .A(_079_),
    .B(_092_),
    .Y(_009_[1])
  );
  NOR _434_ (
    .A(_015_),
    .B(outEtapaL1L2_1[8]),
    .Y(_093_)
  );
  NOR _435_ (
    .A(_039_),
    .B(_041_),
    .Y(_094_)
  );
  NOR _436_ (
    .A(_093_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _437_ (
    .A(_079_),
    .B(_095_),
    .Y(_009_[2])
  );
  NOR _438_ (
    .A(_016_),
    .B(outEtapaL1L2_1[8]),
    .Y(_096_)
  );
  NOR _439_ (
    .A(_039_),
    .B(_042_),
    .Y(_097_)
  );
  NOR _440_ (
    .A(_096_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _441_ (
    .A(_079_),
    .B(_098_),
    .Y(_009_[3])
  );
  NOR _442_ (
    .A(_017_),
    .B(outEtapaL1L2_1[8]),
    .Y(_099_)
  );
  NOR _443_ (
    .A(_039_),
    .B(_043_),
    .Y(_100_)
  );
  NOR _444_ (
    .A(_099_),
    .B(_100_),
    .Y(_101_)
  );
  NOR _445_ (
    .A(_079_),
    .B(_101_),
    .Y(_009_[4])
  );
  NOR _446_ (
    .A(_018_),
    .B(outEtapaL1L2_1[8]),
    .Y(_102_)
  );
  NOR _447_ (
    .A(_039_),
    .B(_044_),
    .Y(_103_)
  );
  NOR _448_ (
    .A(_102_),
    .B(_103_),
    .Y(_104_)
  );
  NOR _449_ (
    .A(_079_),
    .B(_104_),
    .Y(_009_[5])
  );
  NOR _450_ (
    .A(_019_),
    .B(outEtapaL1L2_1[8]),
    .Y(_105_)
  );
  NOR _451_ (
    .A(_039_),
    .B(_045_),
    .Y(_106_)
  );
  NOR _452_ (
    .A(_105_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _453_ (
    .A(_079_),
    .B(_107_),
    .Y(_009_[6])
  );
  NOR _454_ (
    .A(_020_),
    .B(outEtapaL1L2_1[8]),
    .Y(_108_)
  );
  NOR _455_ (
    .A(_039_),
    .B(_046_),
    .Y(_109_)
  );
  NOR _456_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  NOR _457_ (
    .A(_079_),
    .B(_110_),
    .Y(_009_[7])
  );
  NOR _458_ (
    .A(_021_),
    .B(outEtapaL1L2_0[8]),
    .Y(_111_)
  );
  NOR _459_ (
    .A(_029_),
    .B(_030_),
    .Y(_112_)
  );
  NOR _460_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _461_ (
    .A(_079_),
    .B(_113_),
    .Y(_008_[0])
  );
  NOR _462_ (
    .A(_022_),
    .B(outEtapaL1L2_0[8]),
    .Y(_114_)
  );
  NOR _463_ (
    .A(_030_),
    .B(_031_),
    .Y(_115_)
  );
  NOR _464_ (
    .A(_114_),
    .B(_115_),
    .Y(_116_)
  );
  NOR _465_ (
    .A(_079_),
    .B(_116_),
    .Y(_008_[1])
  );
  NOR _466_ (
    .A(_023_),
    .B(outEtapaL1L2_0[8]),
    .Y(_117_)
  );
  NOR _467_ (
    .A(_030_),
    .B(_032_),
    .Y(_118_)
  );
  NOR _468_ (
    .A(_117_),
    .B(_118_),
    .Y(_119_)
  );
  NOR _469_ (
    .A(_079_),
    .B(_119_),
    .Y(_008_[2])
  );
  NOR _470_ (
    .A(_024_),
    .B(outEtapaL1L2_0[8]),
    .Y(_120_)
  );
  NOR _471_ (
    .A(_030_),
    .B(_033_),
    .Y(_121_)
  );
  NOR _472_ (
    .A(_120_),
    .B(_121_),
    .Y(_122_)
  );
  NOR _473_ (
    .A(_079_),
    .B(_122_),
    .Y(_008_[3])
  );
  NOR _474_ (
    .A(_025_),
    .B(outEtapaL1L2_0[8]),
    .Y(_123_)
  );
  NOR _475_ (
    .A(_030_),
    .B(_034_),
    .Y(_124_)
  );
  NOR _476_ (
    .A(_123_),
    .B(_124_),
    .Y(_125_)
  );
  NOR _477_ (
    .A(_079_),
    .B(_125_),
    .Y(_008_[4])
  );
  NOR _478_ (
    .A(_026_),
    .B(outEtapaL1L2_0[8]),
    .Y(_126_)
  );
  NOR _479_ (
    .A(_030_),
    .B(_035_),
    .Y(_127_)
  );
  NOR _480_ (
    .A(_126_),
    .B(_127_),
    .Y(_128_)
  );
  NOR _481_ (
    .A(_079_),
    .B(_128_),
    .Y(_008_[5])
  );
  NOR _482_ (
    .A(_027_),
    .B(outEtapaL1L2_0[8]),
    .Y(_129_)
  );
  NOR _483_ (
    .A(_030_),
    .B(_036_),
    .Y(_130_)
  );
  NOR _484_ (
    .A(_129_),
    .B(_130_),
    .Y(_131_)
  );
  NOR _485_ (
    .A(_079_),
    .B(_131_),
    .Y(_008_[6])
  );
  NOR _486_ (
    .A(_028_),
    .B(outEtapaL1L2_0[8]),
    .Y(_132_)
  );
  NOR _487_ (
    .A(_030_),
    .B(_037_),
    .Y(_133_)
  );
  NOR _488_ (
    .A(_132_),
    .B(_133_),
    .Y(_134_)
  );
  NOR _489_ (
    .A(_079_),
    .B(_134_),
    .Y(_008_[7])
  );
  NOR _490_ (
    .A(_030_),
    .B(_079_),
    .Y(_008_[8])
  );
  NAND _491_ (
    .A(etapa2_inData1[8]),
    .B(selectorL1),
    .Y(_135_)
  );
  NOR _492_ (
    .A(etapa2_inData1[0]),
    .B(_135_),
    .Y(_136_)
  );
  NOR _493_ (
    .A(_079_),
    .B(_135_),
    .Y(_137_)
  );
  NOT _494_ (
    .A(_137_),
    .Y(_138_)
  );
  NOR _495_ (
    .A(_003_[0]),
    .B(_137_),
    .Y(_139_)
  );
  NOR _496_ (
    .A(_136_),
    .B(_139_),
    .Y(_007_[0])
  );
  NOR _497_ (
    .A(etapa2_inData1[1]),
    .B(_135_),
    .Y(_140_)
  );
  NOR _498_ (
    .A(_003_[1]),
    .B(_137_),
    .Y(_141_)
  );
  NOR _499_ (
    .A(_140_),
    .B(_141_),
    .Y(_007_[1])
  );
  NOR _500_ (
    .A(etapa2_inData1[2]),
    .B(_135_),
    .Y(_142_)
  );
  NOR _501_ (
    .A(_003_[2]),
    .B(_137_),
    .Y(_143_)
  );
  NOR _502_ (
    .A(_142_),
    .B(_143_),
    .Y(_007_[2])
  );
  NOR _503_ (
    .A(etapa2_inData1[3]),
    .B(_135_),
    .Y(_144_)
  );
  NOR _504_ (
    .A(_003_[3]),
    .B(_137_),
    .Y(_145_)
  );
  NOR _505_ (
    .A(_144_),
    .B(_145_),
    .Y(_007_[3])
  );
  NOR _506_ (
    .A(etapa2_inData1[4]),
    .B(_135_),
    .Y(_146_)
  );
  NOR _507_ (
    .A(_003_[4]),
    .B(_137_),
    .Y(_147_)
  );
  NOR _508_ (
    .A(_146_),
    .B(_147_),
    .Y(_007_[4])
  );
  NOR _509_ (
    .A(etapa2_inData1[5]),
    .B(_135_),
    .Y(_148_)
  );
  NOR _510_ (
    .A(_003_[5]),
    .B(_137_),
    .Y(_149_)
  );
  NOR _511_ (
    .A(_148_),
    .B(_149_),
    .Y(_007_[5])
  );
  NOR _512_ (
    .A(etapa2_inData1[6]),
    .B(_135_),
    .Y(_150_)
  );
  NOR _513_ (
    .A(_003_[6]),
    .B(_137_),
    .Y(_151_)
  );
  NOR _514_ (
    .A(_150_),
    .B(_151_),
    .Y(_007_[6])
  );
  NOR _515_ (
    .A(etapa2_inData1[7]),
    .B(_135_),
    .Y(_152_)
  );
  NOR _516_ (
    .A(_003_[7]),
    .B(_137_),
    .Y(_153_)
  );
  NOR _517_ (
    .A(_152_),
    .B(_153_),
    .Y(_007_[7])
  );
  NAND _518_ (
    .A(_082_),
    .B(_138_),
    .Y(_007_[8])
  );
  NAND _519_ (
    .A(etapa2_inData1[8]),
    .B(_080_),
    .Y(_154_)
  );
  NOR _520_ (
    .A(etapa2_inData1[0]),
    .B(_154_),
    .Y(_155_)
  );
  NOR _521_ (
    .A(_079_),
    .B(selectorL1),
    .Y(_012_)
  );
  NOR _522_ (
    .A(_079_),
    .B(_154_),
    .Y(_156_)
  );
  NOT _523_ (
    .A(_156_),
    .Y(_157_)
  );
  NOR _524_ (
    .A(_002_[0]),
    .B(_156_),
    .Y(_158_)
  );
  NOR _525_ (
    .A(_155_),
    .B(_158_),
    .Y(_006_[0])
  );
  NOR _526_ (
    .A(etapa2_inData1[1]),
    .B(_154_),
    .Y(_159_)
  );
  NOR _527_ (
    .A(_002_[1]),
    .B(_156_),
    .Y(_160_)
  );
  NOR _528_ (
    .A(_159_),
    .B(_160_),
    .Y(_006_[1])
  );
  NOR _529_ (
    .A(etapa2_inData1[2]),
    .B(_154_),
    .Y(_161_)
  );
  NOR _530_ (
    .A(_002_[2]),
    .B(_156_),
    .Y(_162_)
  );
  NOR _531_ (
    .A(_161_),
    .B(_162_),
    .Y(_006_[2])
  );
  NOR _532_ (
    .A(etapa2_inData1[3]),
    .B(_154_),
    .Y(_163_)
  );
  NOR _533_ (
    .A(_002_[3]),
    .B(_156_),
    .Y(_164_)
  );
  NOR _534_ (
    .A(_163_),
    .B(_164_),
    .Y(_006_[3])
  );
  NOR _535_ (
    .A(etapa2_inData1[4]),
    .B(_154_),
    .Y(_165_)
  );
  NOR _536_ (
    .A(_002_[4]),
    .B(_156_),
    .Y(_166_)
  );
  NOR _537_ (
    .A(_165_),
    .B(_166_),
    .Y(_006_[4])
  );
  NOR _538_ (
    .A(etapa2_inData1[5]),
    .B(_154_),
    .Y(_167_)
  );
  NOR _539_ (
    .A(_002_[5]),
    .B(_156_),
    .Y(_168_)
  );
  NOR _540_ (
    .A(_167_),
    .B(_168_),
    .Y(_006_[5])
  );
  NOR _541_ (
    .A(etapa2_inData1[6]),
    .B(_154_),
    .Y(_169_)
  );
  NOR _542_ (
    .A(_002_[6]),
    .B(_156_),
    .Y(_170_)
  );
  NOR _543_ (
    .A(_169_),
    .B(_170_),
    .Y(_006_[6])
  );
  NOR _544_ (
    .A(etapa2_inData1[7]),
    .B(_154_),
    .Y(_171_)
  );
  NOR _545_ (
    .A(_002_[7]),
    .B(_156_),
    .Y(_172_)
  );
  NOR _546_ (
    .A(_171_),
    .B(_172_),
    .Y(_006_[7])
  );
  NAND _547_ (
    .A(_083_),
    .B(_157_),
    .Y(_006_[8])
  );
  NAND _548_ (
    .A(etapa2_inData0[8]),
    .B(selectorL1),
    .Y(_173_)
  );
  NOR _549_ (
    .A(etapa2_inData0[0]),
    .B(_173_),
    .Y(_174_)
  );
  NOR _550_ (
    .A(_079_),
    .B(_173_),
    .Y(_175_)
  );
  NOT _551_ (
    .A(_175_),
    .Y(_176_)
  );
  NOR _552_ (
    .A(_001_[0]),
    .B(_175_),
    .Y(_177_)
  );
  NOR _553_ (
    .A(_174_),
    .B(_177_),
    .Y(_005_[0])
  );
  NOR _554_ (
    .A(etapa2_inData0[1]),
    .B(_173_),
    .Y(_178_)
  );
  NOR _555_ (
    .A(_001_[1]),
    .B(_175_),
    .Y(_179_)
  );
  NOR _556_ (
    .A(_178_),
    .B(_179_),
    .Y(_005_[1])
  );
  NOR _557_ (
    .A(etapa2_inData0[2]),
    .B(_173_),
    .Y(_180_)
  );
  NOR _558_ (
    .A(_001_[2]),
    .B(_175_),
    .Y(_181_)
  );
  NOR _559_ (
    .A(_180_),
    .B(_181_),
    .Y(_005_[2])
  );
  NOR _560_ (
    .A(etapa2_inData0[3]),
    .B(_173_),
    .Y(_182_)
  );
  NOR _561_ (
    .A(_001_[3]),
    .B(_175_),
    .Y(_183_)
  );
  NOR _562_ (
    .A(_182_),
    .B(_183_),
    .Y(_005_[3])
  );
  NOR _563_ (
    .A(etapa2_inData0[4]),
    .B(_173_),
    .Y(_184_)
  );
  NOR _564_ (
    .A(_001_[4]),
    .B(_175_),
    .Y(_185_)
  );
  NOR _565_ (
    .A(_184_),
    .B(_185_),
    .Y(_005_[4])
  );
  NOR _566_ (
    .A(etapa2_inData0[5]),
    .B(_173_),
    .Y(_186_)
  );
  NOR _567_ (
    .A(_001_[5]),
    .B(_175_),
    .Y(_187_)
  );
  NOR _568_ (
    .A(_186_),
    .B(_187_),
    .Y(_005_[5])
  );
  NOR _569_ (
    .A(etapa2_inData0[6]),
    .B(_173_),
    .Y(_188_)
  );
  NOR _570_ (
    .A(_001_[6]),
    .B(_175_),
    .Y(_189_)
  );
  NOR _571_ (
    .A(_188_),
    .B(_189_),
    .Y(_005_[6])
  );
  NOR _572_ (
    .A(etapa2_inData0[7]),
    .B(_173_),
    .Y(_190_)
  );
  NOR _573_ (
    .A(_001_[7]),
    .B(_175_),
    .Y(_191_)
  );
  NOR _574_ (
    .A(_190_),
    .B(_191_),
    .Y(_005_[7])
  );
  NAND _575_ (
    .A(_084_),
    .B(_176_),
    .Y(_005_[8])
  );
  NAND _576_ (
    .A(etapa2_inData0[8]),
    .B(_080_),
    .Y(_192_)
  );
  NOR _577_ (
    .A(etapa2_inData0[0]),
    .B(_192_),
    .Y(_193_)
  );
  NOR _578_ (
    .A(_079_),
    .B(_192_),
    .Y(_194_)
  );
  NOT _579_ (
    .A(_194_),
    .Y(_195_)
  );
  NOR _580_ (
    .A(_000_[0]),
    .B(_194_),
    .Y(_196_)
  );
  NOR _581_ (
    .A(_193_),
    .B(_196_),
    .Y(_004_[0])
  );
  NOR _582_ (
    .A(etapa2_inData0[1]),
    .B(_192_),
    .Y(_197_)
  );
  NOR _583_ (
    .A(_000_[1]),
    .B(_194_),
    .Y(_198_)
  );
  NOR _584_ (
    .A(_197_),
    .B(_198_),
    .Y(_004_[1])
  );
  NOR _585_ (
    .A(etapa2_inData0[2]),
    .B(_192_),
    .Y(_199_)
  );
  NOR _586_ (
    .A(_000_[2]),
    .B(_194_),
    .Y(_200_)
  );
  NOR _587_ (
    .A(_199_),
    .B(_200_),
    .Y(_004_[2])
  );
  NOR _588_ (
    .A(etapa2_inData0[3]),
    .B(_192_),
    .Y(_201_)
  );
  NOR _589_ (
    .A(_000_[3]),
    .B(_194_),
    .Y(_202_)
  );
  NOR _590_ (
    .A(_201_),
    .B(_202_),
    .Y(_004_[3])
  );
  NOR _591_ (
    .A(etapa2_inData0[4]),
    .B(_192_),
    .Y(_203_)
  );
  NOR _592_ (
    .A(_000_[4]),
    .B(_194_),
    .Y(_204_)
  );
  NOR _593_ (
    .A(_203_),
    .B(_204_),
    .Y(_004_[4])
  );
  NOR _594_ (
    .A(etapa2_inData0[5]),
    .B(_192_),
    .Y(_205_)
  );
  NOR _595_ (
    .A(_000_[5]),
    .B(_194_),
    .Y(_206_)
  );
  NOR _596_ (
    .A(_205_),
    .B(_206_),
    .Y(_004_[5])
  );
  NOR _597_ (
    .A(etapa2_inData0[6]),
    .B(_192_),
    .Y(_207_)
  );
  NOR _598_ (
    .A(_000_[6]),
    .B(_194_),
    .Y(_208_)
  );
  NOR _599_ (
    .A(_207_),
    .B(_208_),
    .Y(_004_[6])
  );
  NOR _600_ (
    .A(etapa2_inData0[7]),
    .B(_192_),
    .Y(_209_)
  );
  NOR _601_ (
    .A(_000_[7]),
    .B(_194_),
    .Y(_210_)
  );
  NOR _602_ (
    .A(_209_),
    .B(_210_),
    .Y(_004_[7])
  );
  NAND _603_ (
    .A(_085_),
    .B(_195_),
    .Y(_004_[8])
  );
  NOR _604_ (
    .A(_079_),
    .B(selectorL2),
    .Y(_013_)
  );
  NAND _605_ (
    .A(reset),
    .B(selectorL2),
    .Y(_211_)
  );
  NOR _606_ (
    .A(outEtapaL1L2_1[0]),
    .B(selectorL2),
    .Y(_212_)
  );
  NOT _607_ (
    .A(_212_),
    .Y(_213_)
  );
  NAND _608_ (
    .A(reset),
    .B(_213_),
    .Y(_214_)
  );
  NOR _609_ (
    .A(inEtapaL2[8]),
    .B(_038_),
    .Y(_215_)
  );
  NAND _610_ (
    .A(inEtapaL2[8]),
    .B(inEtapaL2[0]),
    .Y(_216_)
  );
  NAND _611_ (
    .A(selectorL2),
    .B(_216_),
    .Y(_217_)
  );
  NOR _612_ (
    .A(_215_),
    .B(_217_),
    .Y(_218_)
  );
  NOR _613_ (
    .A(_214_),
    .B(_218_),
    .Y(_011_[0])
  );
  NOR _614_ (
    .A(_014_),
    .B(inEtapaL2[8]),
    .Y(_219_)
  );
  NAND _615_ (
    .A(inEtapaL2[1]),
    .B(inEtapaL2[8]),
    .Y(_220_)
  );
  NAND _616_ (
    .A(selectorL2),
    .B(_220_),
    .Y(_221_)
  );
  NOR _617_ (
    .A(_219_),
    .B(_221_),
    .Y(_222_)
  );
  NOR _618_ (
    .A(outEtapaL1L2_1[1]),
    .B(selectorL2),
    .Y(_223_)
  );
  NOT _619_ (
    .A(_223_),
    .Y(_224_)
  );
  NAND _620_ (
    .A(reset),
    .B(_224_),
    .Y(_225_)
  );
  NOR _621_ (
    .A(_222_),
    .B(_225_),
    .Y(_011_[1])
  );
  NOR _622_ (
    .A(inEtapaL2[8]),
    .B(_015_),
    .Y(_226_)
  );
  NAND _623_ (
    .A(inEtapaL2[8]),
    .B(inEtapaL2[2]),
    .Y(_227_)
  );
  NAND _624_ (
    .A(selectorL2),
    .B(_227_),
    .Y(_228_)
  );
  NOR _625_ (
    .A(_226_),
    .B(_228_),
    .Y(_229_)
  );
  NOR _626_ (
    .A(outEtapaL1L2_1[2]),
    .B(selectorL2),
    .Y(_230_)
  );
  NOT _627_ (
    .A(_230_),
    .Y(_231_)
  );
  NAND _628_ (
    .A(reset),
    .B(_231_),
    .Y(_232_)
  );
  NOR _629_ (
    .A(_229_),
    .B(_232_),
    .Y(_011_[2])
  );
  NOR _630_ (
    .A(inEtapaL2[8]),
    .B(_016_),
    .Y(_233_)
  );
  NAND _631_ (
    .A(inEtapaL2[8]),
    .B(inEtapaL2[3]),
    .Y(_234_)
  );
  NAND _632_ (
    .A(selectorL2),
    .B(_234_),
    .Y(_235_)
  );
  NOR _633_ (
    .A(_233_),
    .B(_235_),
    .Y(_236_)
  );
  NOR _634_ (
    .A(outEtapaL1L2_1[3]),
    .B(selectorL2),
    .Y(_237_)
  );
  NOT _635_ (
    .A(_237_),
    .Y(_238_)
  );
  NAND _636_ (
    .A(reset),
    .B(_238_),
    .Y(_239_)
  );
  NOR _637_ (
    .A(_236_),
    .B(_239_),
    .Y(_011_[3])
  );
  NOR _638_ (
    .A(inEtapaL2[8]),
    .B(_017_),
    .Y(_240_)
  );
  NAND _639_ (
    .A(inEtapaL2[8]),
    .B(inEtapaL2[4]),
    .Y(_241_)
  );
  NAND _640_ (
    .A(selectorL2),
    .B(_241_),
    .Y(_242_)
  );
  NOR _641_ (
    .A(_240_),
    .B(_242_),
    .Y(_243_)
  );
  NOR _642_ (
    .A(outEtapaL1L2_1[4]),
    .B(selectorL2),
    .Y(_244_)
  );
  NOT _643_ (
    .A(_244_),
    .Y(_245_)
  );
  NAND _644_ (
    .A(reset),
    .B(_245_),
    .Y(_246_)
  );
  NOR _645_ (
    .A(_243_),
    .B(_246_),
    .Y(_011_[4])
  );
  NOR _646_ (
    .A(inEtapaL2[8]),
    .B(_018_),
    .Y(_247_)
  );
  NAND _647_ (
    .A(inEtapaL2[8]),
    .B(inEtapaL2[5]),
    .Y(_248_)
  );
  NAND _648_ (
    .A(selectorL2),
    .B(_248_),
    .Y(_249_)
  );
  NOR _649_ (
    .A(_247_),
    .B(_249_),
    .Y(_250_)
  );
  NOR _650_ (
    .A(outEtapaL1L2_1[5]),
    .B(selectorL2),
    .Y(_251_)
  );
  NOT _651_ (
    .A(_251_),
    .Y(_252_)
  );
  NAND _652_ (
    .A(reset),
    .B(_252_),
    .Y(_253_)
  );
  NOR _653_ (
    .A(_250_),
    .B(_253_),
    .Y(_011_[5])
  );
  NOR _654_ (
    .A(inEtapaL2[8]),
    .B(_019_),
    .Y(_254_)
  );
  NAND _655_ (
    .A(inEtapaL2[8]),
    .B(inEtapaL2[6]),
    .Y(_255_)
  );
  NAND _656_ (
    .A(selectorL2),
    .B(_255_),
    .Y(_256_)
  );
  NOR _657_ (
    .A(_254_),
    .B(_256_),
    .Y(_257_)
  );
  NOR _658_ (
    .A(outEtapaL1L2_1[6]),
    .B(selectorL2),
    .Y(_258_)
  );
  NOT _659_ (
    .A(_258_),
    .Y(_259_)
  );
  NAND _660_ (
    .A(reset),
    .B(_259_),
    .Y(_260_)
  );
  NOR _661_ (
    .A(_257_),
    .B(_260_),
    .Y(_011_[6])
  );
  NOR _662_ (
    .A(inEtapaL2[8]),
    .B(_020_),
    .Y(_261_)
  );
  NAND _663_ (
    .A(inEtapaL2[8]),
    .B(inEtapaL2[7]),
    .Y(_262_)
  );
  NAND _664_ (
    .A(selectorL2),
    .B(_262_),
    .Y(_263_)
  );
  NOR _665_ (
    .A(_261_),
    .B(_263_),
    .Y(_264_)
  );
  NOR _666_ (
    .A(outEtapaL1L2_1[7]),
    .B(selectorL2),
    .Y(_265_)
  );
  NOT _667_ (
    .A(_265_),
    .Y(_266_)
  );
  NAND _668_ (
    .A(reset),
    .B(_266_),
    .Y(_267_)
  );
  NOR _669_ (
    .A(_264_),
    .B(_267_),
    .Y(_011_[7])
  );
  NAND _670_ (
    .A(_087_),
    .B(_211_),
    .Y(_268_)
  );
  NOR _671_ (
    .A(inEtapaL2[8]),
    .B(etapa2_inData1[8]),
    .Y(_269_)
  );
  NAND _672_ (
    .A(selectorL2),
    .B(_269_),
    .Y(_270_)
  );
  NAND _673_ (
    .A(_268_),
    .B(_270_),
    .Y(_271_)
  );
  NOT _674_ (
    .A(_271_),
    .Y(_011_[8])
  );
  NOR _675_ (
    .A(inEtapaL2[8]),
    .B(_021_),
    .Y(_272_)
  );
  NAND _676_ (
    .A(_081_),
    .B(_216_),
    .Y(_273_)
  );
  NOR _677_ (
    .A(_272_),
    .B(_273_),
    .Y(_274_)
  );
  NAND _678_ (
    .A(_029_),
    .B(selectorL2),
    .Y(_275_)
  );
  NAND _679_ (
    .A(reset),
    .B(_275_),
    .Y(_276_)
  );
  NOR _680_ (
    .A(_274_),
    .B(_276_),
    .Y(_010_[0])
  );
  NOR _681_ (
    .A(inEtapaL2[8]),
    .B(_022_),
    .Y(_277_)
  );
  NAND _682_ (
    .A(_081_),
    .B(_220_),
    .Y(_278_)
  );
  NOR _683_ (
    .A(_277_),
    .B(_278_),
    .Y(_279_)
  );
  NAND _684_ (
    .A(_031_),
    .B(selectorL2),
    .Y(_280_)
  );
  NAND _685_ (
    .A(reset),
    .B(_280_),
    .Y(_281_)
  );
  NOR _686_ (
    .A(_279_),
    .B(_281_),
    .Y(_010_[1])
  );
  NOR _687_ (
    .A(inEtapaL2[8]),
    .B(_023_),
    .Y(_282_)
  );
  NAND _688_ (
    .A(_081_),
    .B(_227_),
    .Y(_283_)
  );
  NOR _689_ (
    .A(_282_),
    .B(_283_),
    .Y(_284_)
  );
  NAND _690_ (
    .A(_032_),
    .B(selectorL2),
    .Y(_285_)
  );
  NAND _691_ (
    .A(reset),
    .B(_285_),
    .Y(_286_)
  );
  NOR _692_ (
    .A(_284_),
    .B(_286_),
    .Y(_010_[2])
  );
  NOR _693_ (
    .A(inEtapaL2[8]),
    .B(_024_),
    .Y(_287_)
  );
  NAND _694_ (
    .A(_081_),
    .B(_234_),
    .Y(_288_)
  );
  NOR _695_ (
    .A(_287_),
    .B(_288_),
    .Y(_289_)
  );
  NAND _696_ (
    .A(_033_),
    .B(selectorL2),
    .Y(_290_)
  );
  NAND _697_ (
    .A(reset),
    .B(_290_),
    .Y(_291_)
  );
  NOR _698_ (
    .A(_289_),
    .B(_291_),
    .Y(_010_[3])
  );
  NOR _699_ (
    .A(inEtapaL2[8]),
    .B(_025_),
    .Y(_292_)
  );
  NAND _700_ (
    .A(_081_),
    .B(_241_),
    .Y(_293_)
  );
  NOR _701_ (
    .A(_292_),
    .B(_293_),
    .Y(_294_)
  );
  NAND _702_ (
    .A(_034_),
    .B(selectorL2),
    .Y(_295_)
  );
  NAND _703_ (
    .A(reset),
    .B(_295_),
    .Y(_296_)
  );
  NOR _704_ (
    .A(_294_),
    .B(_296_),
    .Y(_010_[4])
  );
  NOR _705_ (
    .A(inEtapaL2[8]),
    .B(_026_),
    .Y(_297_)
  );
  NAND _706_ (
    .A(_081_),
    .B(_248_),
    .Y(_298_)
  );
  NOR _707_ (
    .A(_297_),
    .B(_298_),
    .Y(_299_)
  );
  NAND _708_ (
    .A(_035_),
    .B(selectorL2),
    .Y(_300_)
  );
  NAND _709_ (
    .A(reset),
    .B(_300_),
    .Y(_301_)
  );
  NOR _710_ (
    .A(_299_),
    .B(_301_),
    .Y(_010_[5])
  );
  NOR _711_ (
    .A(inEtapaL2[8]),
    .B(_027_),
    .Y(_302_)
  );
  NAND _712_ (
    .A(_081_),
    .B(_255_),
    .Y(_303_)
  );
  NOR _713_ (
    .A(_302_),
    .B(_303_),
    .Y(_304_)
  );
  NAND _714_ (
    .A(_036_),
    .B(selectorL2),
    .Y(_305_)
  );
  NAND _715_ (
    .A(reset),
    .B(_305_),
    .Y(_306_)
  );
  NOR _716_ (
    .A(_304_),
    .B(_306_),
    .Y(_010_[6])
  );
  NOR _717_ (
    .A(inEtapaL2[8]),
    .B(_028_),
    .Y(_307_)
  );
  NAND _718_ (
    .A(_081_),
    .B(_262_),
    .Y(_308_)
  );
  NOR _719_ (
    .A(_307_),
    .B(_308_),
    .Y(_309_)
  );
  NAND _720_ (
    .A(_037_),
    .B(selectorL2),
    .Y(_310_)
  );
  NAND _721_ (
    .A(reset),
    .B(_310_),
    .Y(_311_)
  );
  NOR _722_ (
    .A(_309_),
    .B(_311_),
    .Y(_010_[7])
  );
  NOR _723_ (
    .A(_008_[8]),
    .B(_013_),
    .Y(_312_)
  );
  NOR _724_ (
    .A(inEtapaL2[8]),
    .B(etapa2_inData0[8]),
    .Y(_313_)
  );
  NOT _725_ (
    .A(_313_),
    .Y(_314_)
  );
  NOR _726_ (
    .A(selectorL2),
    .B(_314_),
    .Y(_315_)
  );
  NOR _727_ (
    .A(_312_),
    .B(_315_),
    .Y(_010_[8])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _728_ (
    .C(clk_f),
    .D(_000_[0]),
    .Q(data0[0])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _729_ (
    .C(clk_f),
    .D(_000_[1]),
    .Q(data0[1])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _730_ (
    .C(clk_f),
    .D(_000_[2]),
    .Q(data0[2])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _731_ (
    .C(clk_f),
    .D(_000_[3]),
    .Q(data0[3])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _732_ (
    .C(clk_f),
    .D(_000_[4]),
    .Q(data0[4])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _733_ (
    .C(clk_f),
    .D(_000_[5]),
    .Q(data0[5])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _734_ (
    .C(clk_f),
    .D(_000_[6]),
    .Q(data0[6])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _735_ (
    .C(clk_f),
    .D(_000_[7]),
    .Q(data0[7])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _736_ (
    .C(clk_f),
    .D(_000_[8]),
    .Q(data0[8])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _737_ (
    .C(clk_f),
    .D(_001_[0]),
    .Q(data1[0])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _738_ (
    .C(clk_f),
    .D(_001_[1]),
    .Q(data1[1])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _739_ (
    .C(clk_f),
    .D(_001_[2]),
    .Q(data1[2])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _740_ (
    .C(clk_f),
    .D(_001_[3]),
    .Q(data1[3])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _741_ (
    .C(clk_f),
    .D(_001_[4]),
    .Q(data1[4])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _742_ (
    .C(clk_f),
    .D(_001_[5]),
    .Q(data1[5])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _743_ (
    .C(clk_f),
    .D(_001_[6]),
    .Q(data1[6])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _744_ (
    .C(clk_f),
    .D(_001_[7]),
    .Q(data1[7])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _745_ (
    .C(clk_f),
    .D(_001_[8]),
    .Q(data1[8])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _746_ (
    .C(clk_f),
    .D(_002_[0]),
    .Q(data2[0])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _747_ (
    .C(clk_f),
    .D(_002_[1]),
    .Q(data2[1])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _748_ (
    .C(clk_f),
    .D(_002_[2]),
    .Q(data2[2])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _749_ (
    .C(clk_f),
    .D(_002_[3]),
    .Q(data2[3])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _750_ (
    .C(clk_f),
    .D(_002_[4]),
    .Q(data2[4])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _751_ (
    .C(clk_f),
    .D(_002_[5]),
    .Q(data2[5])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _752_ (
    .C(clk_f),
    .D(_002_[6]),
    .Q(data2[6])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _753_ (
    .C(clk_f),
    .D(_002_[7]),
    .Q(data2[7])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _754_ (
    .C(clk_f),
    .D(_002_[8]),
    .Q(data2[8])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _755_ (
    .C(clk_f),
    .D(_003_[0]),
    .Q(data3[0])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _756_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(data3[1])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _757_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(data3[2])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _758_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(data3[3])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _759_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(data3[4])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _760_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(data3[5])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _761_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(data3[6])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _762_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(data3[7])
  );
  (* src = "demuxEstructural.v:67" *)
  DFF _763_ (
    .C(clk_f),
    .D(_003_[8]),
    .Q(data3[8])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _764_ (
    .C(clk_2f),
    .D(_012_),
    .Q(selectorL1)
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _765_ (
    .C(clk_2f),
    .D(_004_[0]),
    .Q(etapa1_inData0[0])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _766_ (
    .C(clk_2f),
    .D(_004_[1]),
    .Q(etapa1_inData0[1])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _767_ (
    .C(clk_2f),
    .D(_004_[2]),
    .Q(etapa1_inData0[2])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _768_ (
    .C(clk_2f),
    .D(_004_[3]),
    .Q(etapa1_inData0[3])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _769_ (
    .C(clk_2f),
    .D(_004_[4]),
    .Q(etapa1_inData0[4])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _770_ (
    .C(clk_2f),
    .D(_004_[5]),
    .Q(etapa1_inData0[5])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _771_ (
    .C(clk_2f),
    .D(_004_[6]),
    .Q(etapa1_inData0[6])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _772_ (
    .C(clk_2f),
    .D(_004_[7]),
    .Q(etapa1_inData0[7])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _773_ (
    .C(clk_2f),
    .D(_004_[8]),
    .Q(etapa1_inData0[8])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _774_ (
    .C(clk_2f),
    .D(_005_[0]),
    .Q(etapa1_inData1[0])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _775_ (
    .C(clk_2f),
    .D(_005_[1]),
    .Q(etapa1_inData1[1])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _776_ (
    .C(clk_2f),
    .D(_005_[2]),
    .Q(etapa1_inData1[2])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _777_ (
    .C(clk_2f),
    .D(_005_[3]),
    .Q(etapa1_inData1[3])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _778_ (
    .C(clk_2f),
    .D(_005_[4]),
    .Q(etapa1_inData1[4])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _779_ (
    .C(clk_2f),
    .D(_005_[5]),
    .Q(etapa1_inData1[5])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _780_ (
    .C(clk_2f),
    .D(_005_[6]),
    .Q(etapa1_inData1[6])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _781_ (
    .C(clk_2f),
    .D(_005_[7]),
    .Q(etapa1_inData1[7])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _782_ (
    .C(clk_2f),
    .D(_005_[8]),
    .Q(etapa1_inData1[8])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _783_ (
    .C(clk_2f),
    .D(_006_[0]),
    .Q(etapa1_inData2[0])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _784_ (
    .C(clk_2f),
    .D(_006_[1]),
    .Q(etapa1_inData2[1])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _785_ (
    .C(clk_2f),
    .D(_006_[2]),
    .Q(etapa1_inData2[2])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _786_ (
    .C(clk_2f),
    .D(_006_[3]),
    .Q(etapa1_inData2[3])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _787_ (
    .C(clk_2f),
    .D(_006_[4]),
    .Q(etapa1_inData2[4])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _788_ (
    .C(clk_2f),
    .D(_006_[5]),
    .Q(etapa1_inData2[5])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _789_ (
    .C(clk_2f),
    .D(_006_[6]),
    .Q(etapa1_inData2[6])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _790_ (
    .C(clk_2f),
    .D(_006_[7]),
    .Q(etapa1_inData2[7])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _791_ (
    .C(clk_2f),
    .D(_006_[8]),
    .Q(etapa1_inData2[8])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _792_ (
    .C(clk_2f),
    .D(_007_[0]),
    .Q(etapa1_inData3[0])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _793_ (
    .C(clk_2f),
    .D(_007_[1]),
    .Q(etapa1_inData3[1])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _794_ (
    .C(clk_2f),
    .D(_007_[2]),
    .Q(etapa1_inData3[2])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _795_ (
    .C(clk_2f),
    .D(_007_[3]),
    .Q(etapa1_inData3[3])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _796_ (
    .C(clk_2f),
    .D(_007_[4]),
    .Q(etapa1_inData3[4])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _797_ (
    .C(clk_2f),
    .D(_007_[5]),
    .Q(etapa1_inData3[5])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _798_ (
    .C(clk_2f),
    .D(_007_[6]),
    .Q(etapa1_inData3[6])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _799_ (
    .C(clk_2f),
    .D(_007_[7]),
    .Q(etapa1_inData3[7])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _800_ (
    .C(clk_2f),
    .D(_007_[8]),
    .Q(etapa1_inData3[8])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _801_ (
    .C(clk_2f),
    .D(_008_[0]),
    .Q(etapa2_inData0[0])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _802_ (
    .C(clk_2f),
    .D(_008_[1]),
    .Q(etapa2_inData0[1])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _803_ (
    .C(clk_2f),
    .D(_008_[2]),
    .Q(etapa2_inData0[2])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _804_ (
    .C(clk_2f),
    .D(_008_[3]),
    .Q(etapa2_inData0[3])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _805_ (
    .C(clk_2f),
    .D(_008_[4]),
    .Q(etapa2_inData0[4])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _806_ (
    .C(clk_2f),
    .D(_008_[5]),
    .Q(etapa2_inData0[5])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _807_ (
    .C(clk_2f),
    .D(_008_[6]),
    .Q(etapa2_inData0[6])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _808_ (
    .C(clk_2f),
    .D(_008_[7]),
    .Q(etapa2_inData0[7])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _809_ (
    .C(clk_2f),
    .D(_008_[8]),
    .Q(etapa2_inData0[8])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _810_ (
    .C(clk_2f),
    .D(_009_[0]),
    .Q(etapa2_inData1[0])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _811_ (
    .C(clk_2f),
    .D(_009_[1]),
    .Q(etapa2_inData1[1])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _812_ (
    .C(clk_2f),
    .D(_009_[2]),
    .Q(etapa2_inData1[2])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _813_ (
    .C(clk_2f),
    .D(_009_[3]),
    .Q(etapa2_inData1[3])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _814_ (
    .C(clk_2f),
    .D(_009_[4]),
    .Q(etapa2_inData1[4])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _815_ (
    .C(clk_2f),
    .D(_009_[5]),
    .Q(etapa2_inData1[5])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _816_ (
    .C(clk_2f),
    .D(_009_[6]),
    .Q(etapa2_inData1[6])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _817_ (
    .C(clk_2f),
    .D(_009_[7]),
    .Q(etapa2_inData1[7])
  );
  (* src = "demuxEstructural.v:36" *)
  DFF _818_ (
    .C(clk_2f),
    .D(_009_[8]),
    .Q(etapa2_inData1[8])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _819_ (
    .C(clk_4f),
    .D(_010_[0]),
    .Q(outEtapaL1L2_0[0])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _820_ (
    .C(clk_4f),
    .D(_010_[1]),
    .Q(outEtapaL1L2_0[1])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _821_ (
    .C(clk_4f),
    .D(_010_[2]),
    .Q(outEtapaL1L2_0[2])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _822_ (
    .C(clk_4f),
    .D(_010_[3]),
    .Q(outEtapaL1L2_0[3])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _823_ (
    .C(clk_4f),
    .D(_010_[4]),
    .Q(outEtapaL1L2_0[4])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _824_ (
    .C(clk_4f),
    .D(_010_[5]),
    .Q(outEtapaL1L2_0[5])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _825_ (
    .C(clk_4f),
    .D(_010_[6]),
    .Q(outEtapaL1L2_0[6])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _826_ (
    .C(clk_4f),
    .D(_010_[7]),
    .Q(outEtapaL1L2_0[7])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _827_ (
    .C(clk_4f),
    .D(_010_[8]),
    .Q(outEtapaL1L2_0[8])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _828_ (
    .C(clk_4f),
    .D(_011_[0]),
    .Q(outEtapaL1L2_1[0])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _829_ (
    .C(clk_4f),
    .D(_011_[1]),
    .Q(outEtapaL1L2_1[1])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _830_ (
    .C(clk_4f),
    .D(_011_[2]),
    .Q(outEtapaL1L2_1[2])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _831_ (
    .C(clk_4f),
    .D(_011_[3]),
    .Q(outEtapaL1L2_1[3])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _832_ (
    .C(clk_4f),
    .D(_011_[4]),
    .Q(outEtapaL1L2_1[4])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _833_ (
    .C(clk_4f),
    .D(_011_[5]),
    .Q(outEtapaL1L2_1[5])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _834_ (
    .C(clk_4f),
    .D(_011_[6]),
    .Q(outEtapaL1L2_1[6])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _835_ (
    .C(clk_4f),
    .D(_011_[7]),
    .Q(outEtapaL1L2_1[7])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _836_ (
    .C(clk_4f),
    .D(_011_[8]),
    .Q(outEtapaL1L2_1[8])
  );
  (* src = "demuxEstructural.v:18" *)
  DFF _837_ (
    .C(clk_4f),
    .D(_013_),
    .Q(selectorL2)
  );
endmodule
